/* Generated by tools/reference/gen_params.py -- do not edit.
 *
 * Montgomery parameters, one block per curve. R = 2^(64*FP_LIMBS).
 *   FP_MONT_N0 = -p^-1 mod 2^64   the REDC multiplier
 *   FP_R2      = R^2 mod p        converts a plain residue into Montgomery form
 *   FP_ONE     = R mod p          the Montgomery representation of 1
 */
#ifndef ELIPS_FP_PARAMS_H
#define ELIPS_FP_PARAMS_H

#include <stdint.h>
#include <gmp.h>

/* Alias GMP's limb type rather than uint64_t. They are both 64 bits wide on the
 * platforms we target, but they are distinct C types (unsigned long vs unsigned
 * long long on LP64), and passing one where the other is expected is a
 * constraint violation that happens to work. The mpn_* calls in fp.c need the
 * real thing. */
typedef mp_limb_t limb_t;

#if GMP_LIMB_BITS != 64
#  error "These parameters are generated for 64-bit GMP limbs."
#endif

#if defined(ELIPS_CURVE_BLS12_381)
  #define ELIPS_CURVE_NAME   "BLS12-381"
  #define FP_LIMBS           6
  #define FP_BITS            381
  #define FP_MONT_N0         UINT64_C(0x89f3fffcfffcfffd)
  /* y^2 = x^3 + 4 */
  #define ELIPS_CURVE_B_SIGN (1)
  #define ELIPS_CURVE_B      4
  #define ELIPS_HAS_CURVE    1
  static const limb_t FP_MODULUS[6] = {
        UINT64_C(0xb9feffffffffaaab),
        UINT64_C(0x1eabfffeb153ffff),
        UINT64_C(0x6730d2a0f6b0f624),
        UINT64_C(0x64774b84f38512bf),
        UINT64_C(0x4b1ba7b6434bacd7),
        UINT64_C(0x1a0111ea397fe69a)
  };
  static const limb_t FP_R2[6] = {
        UINT64_C(0xf4df1f341c341746),
        UINT64_C(0x0a76e6a609d104f1),
        UINT64_C(0x8de5476c4c95b6d5),
        UINT64_C(0x67eb88a9939d83c0),
        UINT64_C(0x9a793e85b519952d),
        UINT64_C(0x11988fe592cae3aa)
  };
  static const limb_t FP_ONE[6] = {
        UINT64_C(0x760900000002fffd),
        UINT64_C(0xebf4000bc40c0002),
        UINT64_C(0x5f48985753c758ba),
        UINT64_C(0x77ce585370525745),
        UINT64_C(0x5c071a97a256ec6d),
        UINT64_C(0x15f65ec3fa80e493)
  };
#endif

#if defined(ELIPS_CURVE_BLS12_461)
  #define ELIPS_CURVE_NAME   "BLS12-461"
  #define FP_LIMBS           8
  #define FP_BITS            461
  #define FP_MONT_N0         UINT64_C(0x000c0005fffffffd)
  /* y^2 = x^3 + 4 */
  #define ELIPS_CURVE_B_SIGN (1)
  #define ELIPS_CURVE_B      4
  #define ELIPS_HAS_CURVE    1
  static const limb_t FP_MODULUS[8] = {
        UINT64_C(0xaaac0000aaaaaaab),
        UINT64_C(0x0020000555554aaa),
        UINT64_C(0x0f26aa91557f0040),
        UINT64_C(0x8b42a8dffa5c1cc0),
        UINT64_C(0x32d8bacca47b1484),
        UINT64_C(0xd69414935fbd6f1e),
        UINT64_C(0x5545554d5a555a55),
        UINT64_C(0x0000000000001555)
  };
  static const limb_t FP_R2[8] = {
        UINT64_C(0x153ec6ddf1aa9f33),
        UINT64_C(0xf626d1e77e495542),
        UINT64_C(0x85dd4824b3d3f472),
        UINT64_C(0x0b5ef771a76b22fe),
        UINT64_C(0xae4c86a65967e304),
        UINT64_C(0xa6778f9c2b94cbae),
        UINT64_C(0xc3706d5e2fe7a37a),
        UINT64_C(0x00000000000004b7)
  };
  static const limb_t FP_ONE[8] = {
        UINT64_C(0xf3f7fcfdfcfffe7f),
        UINT64_C(0xbf9fe840002813ff),
        UINT64_C(0x858af9c903c0bf3f),
        UINT64_C(0x797222a6b311eb88),
        UINT64_C(0x702e5bdd554d59be),
        UINT64_C(0x7e1f20063af2566a),
        UINT64_C(0x53fd14e37575bd1e),
        UINT64_C(0x0000000000001400)
  };
#endif

#if defined(ELIPS_CURVE_BN_462)
  #define ELIPS_CURVE_NAME   "BN-462"
  #define FP_LIMBS           8
  #define FP_BITS            462
  #define FP_MONT_N0         UINT64_C(0xe718ce9e711bb5e5)
  /* y^2 = x^3 - 4 */
  #define ELIPS_CURVE_B_SIGN (-1)
  #define ELIPS_CURVE_B      4
  #define ELIPS_HAS_CURVE    1
  static const limb_t FP_MODULUS[8] = {
        UINT64_C(0x2401b00840138013),
        UINT64_C(0xf687f64000000000),
        UINT64_C(0xfffffff6ff66fc6f),
        UINT64_C(0x12908f41c8020fff),
        UINT64_C(0xbfca0000000000d8),
        UINT64_C(0xfffff6ff0cf6b7d9),
        UINT64_C(0x80360120023fffff),
        UINT64_C(0x0000000000002404)
  };
  static const limb_t FP_R2[8] = {
        UINT64_C(0xffb1ffb6caf1880b),
        UINT64_C(0xba49f8b9c4c1a8b2),
        UINT64_C(0x9000c34490b9933a),
        UINT64_C(0x4284c26b4ec54698),
        UINT64_C(0x74c63c7da0391584),
        UINT64_C(0x9cdcd35003bb0cd6),
        UINT64_C(0x5763230bbc44e2af),
        UINT64_C(0x0000000000000273)
  };
  static const limb_t FP_ONE[8] = {
        UINT64_C(0x3e11eeb41eee70a8),
        UINT64_C(0x2eea3e13fec5661f),
        UINT64_C(0x31530e1535b28153),
        UINT64_C(0x68ceb6920acb7c40),
        UINT64_C(0xfd303bfd856dff73),
        UINT64_C(0xffaffe8680658205),
        UINT64_C(0xfde7f1801dfec009),
        UINT64_C(0x0000000000000fe5)
  };
#endif

#ifndef ELIPS_HAS_CURVE
#  error "No curve selected: define ELIPS_CURVE_BLS12_381, ELIPS_CURVE_BLS12_461 or ELIPS_CURVE_BN_462"
#endif

#endif /* ELIPS_FP_PARAMS_H */
