/* Generated by tools/reference/gen_h2c_params.py -- do not edit.
 *
 * RFC 9380 hash-to-curve constants. Field elements are in Montgomery form, so
 * the library needs no initialisation step for them.
 *
 * BLS12-381 uses simplified SWU over an isogenous curve, which is the suite
 * RFC 9380 registers, so its output matches every conforming implementation.
 * BLS12-461 and BN-462 have no registered suite and use Shallue-van de
 * Woestijne, which RFC 9380 defines for exactly this case (A = 0, no isogeny
 * available) and uses itself for BN254.
 *
 * Everything here except the BLS12-381 isogeny tables is derived from the curve
 * parameters. The isogeny tables come from tools/reference/h2c_iso_bls12_381.json
 * and are verified to be an isogeny -- and to reproduce the RFC's own test
 * vectors -- before this file is written.
 */
#ifndef ELIPS_H2C_PARAMS_H
#define ELIPS_H2C_PARAMS_H

#include "elips/fp_params.h"


#if defined(ELIPS_CURVE_BLS12_381)
  #define ELIPS_H2C_SUITE_G1 "BLS12381G1_XMD:SHA-256_SSWU_RO_"
  #define ELIPS_H2C_SUITE_G2 "BLS12381G2_XMD:SHA-256_SSWU_RO_"
  /* RFC 9380 5.3: ceil((ceil(log2(p)) + 128) / 8). */
  #define ELIPS_H2C_L        64
  #define ELIPS_H2C_SSWU     1
  /* The map runs on a curve isogenous to this one, because
   * simplified SWU needs A*B != 0 and these curves have A = 0. */
  static const limb_t H2C_G1_ISO_A[6] = {
        UINT64_C(0x2f65aa0e9af5aa51),
        UINT64_C(0x86464c2d1e8416c3),
        UINT64_C(0xb85ce591b7bd31e2),
        UINT64_C(0x27e11c91b5f24e7c),
        UINT64_C(0x28376eda6bfc1835),
        UINT64_C(0x155455c3e5071d85)
  };
  static const limb_t H2C_G1_ISO_B[6] = {
        UINT64_C(0xfb996971fe22a1e0),
        UINT64_C(0x9aa93eb35b742d6f),
        UINT64_C(0x8c476013de99c5c4),
        UINT64_C(0x873e27c3a221e571),
        UINT64_C(0xca72b5e45a52d888),
        UINT64_C(0x06824061418a386b)
  };
  static const limb_t H2C_G1_Z[6] = {
        UINT64_C(0x886c00000023ffdc),
        UINT64_C(0x0f70008d3090001d),
        UINT64_C(0x77672417ed5828c3),
        UINT64_C(0x9dac23e943dc1740),
        UINT64_C(0x50553f1b9c131521),
        UINT64_C(0x078c712fbe0ab6e8)
  };
  static const limb_t H2C_G1_MB_OVER_A[6] = {
        UINT64_C(0x052583c93555a7fe),
        UINT64_C(0x3b40d72430f93c82),
        UINT64_C(0x1b75faa0105ec983),
        UINT64_C(0x2527e7dc63851767),
        UINT64_C(0x99fffd1f34fc181d),
        UINT64_C(0x097cab54770ca0d3)
  };
  static const limb_t H2C_G1_B_OVER_ZA[6] = {
        UINT64_C(0xaefbc579583dc22f),
        UINT64_C(0x70cca69e8ca26edc),
        UINT64_C(0xaf05f2a3b113ce57),
        UINT64_C(0x4ed257417860c764),
        UINT64_C(0xbb16a0c0d526ff96),
        UINT64_C(0x1469e7cf3b7ec553)
  };
  #define H2C_G1_ISO_XNUM_LEN 12
  static const limb_t H2C_G1_ISO_XNUM[12][6] = {
    { UINT64_C(0x4d18b6f3af00131c),
        UINT64_C(0x19fa219793fee28c),
        UINT64_C(0x3f2885f1467f19ae),
        UINT64_C(0x23dcea34f2ffb304),
        UINT64_C(0xd15b58d2ffc00054),
        UINT64_C(0x0913be200a20bef4) },
    { UINT64_C(0x898985385cdbbd8b),
        UINT64_C(0x3c79e43cc7d966aa),
        UINT64_C(0x1597e193f4cd233a),
        UINT64_C(0x8637ef1e4d6623ad),
        UINT64_C(0x11b22deed20d827b),
        UINT64_C(0x07097bc5998784ad) },
    { UINT64_C(0xa542583a480b664b),
        UINT64_C(0xfc7169c026e568c6),
        UINT64_C(0x5ba2ef314ed8b5a6),
        UINT64_C(0x5b5491c05102f0e7),
        UINT64_C(0xdf6e99707d2a0079),
        UINT64_C(0x0784151ed7605524) },
    { UINT64_C(0x494e212870f72741),
        UINT64_C(0xab9be52fbda43021),
        UINT64_C(0x26f5577994e34c3d),
        UINT64_C(0x049dfee82aefbd60),
        UINT64_C(0x65dadd7828505289),
        UINT64_C(0x0e93d431ea011aeb) },
    { UINT64_C(0x90ee774bd6a74d45),
        UINT64_C(0x7ada1c8a41bfb185),
        UINT64_C(0x0f1a8953b325f464),
        UINT64_C(0x104c24211be4805c),
        UINT64_C(0x169139d319ea7a8f),
        UINT64_C(0x09f20ead8e532bf6) },
    { UINT64_C(0x6ddd93e2f43626b7),
        UINT64_C(0xa5482c9aa1ccd7bd),
        UINT64_C(0x143245631883f4bd),
        UINT64_C(0x2e0a94ccf77ec0db),
        UINT64_C(0xb0282d480e56489f),
        UINT64_C(0x18f4bfcbb4368929) },
    { UINT64_C(0x23c5f0c953402dfd),
        UINT64_C(0x7a43ff6958ce4fe9),
        UINT64_C(0x2c390d3d2da5df63),
        UINT64_C(0xd0df5c98e1f9d70f),
        UINT64_C(0xffd89869a572b297),
        UINT64_C(0x1277ffc72f25e8fe) },
    { UINT64_C(0x79f4f0490f06a8a6),
        UINT64_C(0x85f894a88030fd81),
        UINT64_C(0x12da3054b18b6410),
        UINT64_C(0xe2a57f6505880d65),
        UINT64_C(0xbba074f260e400f1),
        UINT64_C(0x08b76279f621d028) },
    { UINT64_C(0xe67245ba78d5b00b),
        UINT64_C(0x8456ba9a1f186475),
        UINT64_C(0x7888bff6e6b33bb4),
        UINT64_C(0xe21585b9a30f86cb),
        UINT64_C(0x05a69cdcef55feee),
        UINT64_C(0x09e699dd9adfa5ac) },
    { UINT64_C(0x0de5c357bff57107),
        UINT64_C(0x0a0db4ae6b1a10b2),
        UINT64_C(0xe256bb67b3b3cd8d),
        UINT64_C(0x8ad456574e9db24f),
        UINT64_C(0x0443915f50fd4179),
        UINT64_C(0x098c4bf7de8b6375) },
    { UINT64_C(0xe6b0617e7dd929c7),
        UINT64_C(0xfe6e37d442537375),
        UINT64_C(0x1dafdeda137a489e),
        UINT64_C(0xe4efd1ad3f767ceb),
        UINT64_C(0x4a51d8667f0fe1cf),
        UINT64_C(0x054fdf4bbf1d821c) },
    { UINT64_C(0x72db2a50658d767b),
        UINT64_C(0x8abf91faa257b3d5),
        UINT64_C(0xe969d6833764ab47),
        UINT64_C(0x464170142a1009eb),
        UINT64_C(0xb14f01aadb30be2f),
        UINT64_C(0x18ae6a856f40715d) }
  };
  #define H2C_G1_ISO_XDEN_LEN 11
  static const limb_t H2C_G1_ISO_XDEN[11][6] = {
    { UINT64_C(0xb962a077fdb0f945),
        UINT64_C(0xa6a9740fefda13a0),
        UINT64_C(0xc14d568c3ed6c544),
        UINT64_C(0xb43fc37b908b133e),
        UINT64_C(0x9c0b3ac929599016),
        UINT64_C(0x0165aa6c93ad115f) },
    { UINT64_C(0x23279a3ba506c1d9),
        UINT64_C(0x92cfca0a9465176a),
        UINT64_C(0x3b294ab13755f0ff),
        UINT64_C(0x116dda1c5070ae93),
        UINT64_C(0xed4530924cec2045),
        UINT64_C(0x083383d6ed81f1ce) },
    { UINT64_C(0x9885c2a6449fecfc),
        UINT64_C(0x4a2b54ccd37733f0),
        UINT64_C(0x17da9ffd8738c142),
        UINT64_C(0xa0fba72732b3fafd),
        UINT64_C(0xff364f36e54b6812),
        UINT64_C(0x0f29c13c660523e2) },
    { UINT64_C(0xe349cc118278f041),
        UINT64_C(0xd487228f2f3204fb),
        UINT64_C(0xc9d325849ade5150),
        UINT64_C(0x43a92bd69c15c2df),
        UINT64_C(0x1c2c7844bc417be4),
        UINT64_C(0x12025184f407440c) },
    { UINT64_C(0x587f65ae6acb057b),
        UINT64_C(0x1444ef325140201f),
        UINT64_C(0xfbf995e71270da49),
        UINT64_C(0xccda066072436a42),
        UINT64_C(0x7408904f0f186bb2),
        UINT64_C(0x13b93c63edf6c015) },
    { UINT64_C(0xfb918622cd141920),
        UINT64_C(0x4a4c64423ecaddb4),
        UINT64_C(0x0beb232927f7fb26),
        UINT64_C(0x30f94df6f83a3dc2),
        UINT64_C(0xaeedd424d780f388),
        UINT64_C(0x06cc402dd594bbeb) },
    { UINT64_C(0xd41f761151b23f8f),
        UINT64_C(0x32a92465435719b3),
        UINT64_C(0x64f436e888c62cb9),
        UINT64_C(0xdf70a9a1f757c6e4),
        UINT64_C(0x6933a38d5b594c81),
        UINT64_C(0x0c6f7f7237b46606) },
    { UINT64_C(0x693c08747876c8f7),
        UINT64_C(0x22c9850bf9cf80f0),
        UINT64_C(0x8e9071dab950c124),
        UINT64_C(0x89bc62d61c7baf23),
        UINT64_C(0xbc6be2d8dad57c23),
        UINT64_C(0x17916987aa14a122) },
    { UINT64_C(0x1be3ff439c1316fd),
        UINT64_C(0x9965243a7571dfa7),
        UINT64_C(0xc7f7f62962f5cd81),
        UINT64_C(0x32c6aa9af394361c),
        UINT64_C(0xbbc2ee18e1c227f4),
        UINT64_C(0x0c102cbac531bb34) },
    { UINT64_C(0x997614c97bacbf07),
        UINT64_C(0x61f86372b99192c0),
        UINT64_C(0x5b8c95fc14353fc3),
        UINT64_C(0xca2b066c2a87492f),
        UINT64_C(0x16178f5bbf698711),
        UINT64_C(0x12a6dcd7f0f4e0e8) },
    { UINT64_C(0x760900000002fffd),
        UINT64_C(0xebf4000bc40c0002),
        UINT64_C(0x5f48985753c758ba),
        UINT64_C(0x77ce585370525745),
        UINT64_C(0x5c071a97a256ec6d),
        UINT64_C(0x15f65ec3fa80e493) }
  };
  #define H2C_G1_ISO_YNUM_LEN 16
  static const limb_t H2C_G1_ISO_YNUM[16][6] = {
    { UINT64_C(0x2b567ff3e2837267),
        UINT64_C(0x1d4d9e57b958a767),
        UINT64_C(0xce028fea04bd7373),
        UINT64_C(0xcc31a30a0b6cd3df),
        UINT64_C(0x7d7b18a682692693),
        UINT64_C(0x0d300744d42a0310) },
    { UINT64_C(0x99c2555fa542493f),
        UINT64_C(0xfe7f53cc4874f878),
        UINT64_C(0x5df0608b8f97608a),
        UINT64_C(0x14e03832052b49c8),
        UINT64_C(0x706326a6957dd5a4),
        UINT64_C(0x0a8dadd9c2414555) },
    { UINT64_C(0x13d942922a5cf63a),
        UINT64_C(0x357e33e36e261e7d),
        UINT64_C(0xcf05a27c8456088d),
        UINT64_C(0x0000bd1de7ba50f0),
        UINT64_C(0x83d0c7532f8c1fde),
        UINT64_C(0x13f70bf38bbf2905) },
    { UINT64_C(0x5c57fd95bfafbdbb),
        UINT64_C(0x28a359a65e541707),
        UINT64_C(0x3983ceb4f6360b6d),
        UINT64_C(0xafe19ff6f97e6d53),
        UINT64_C(0xb3468f4550192bf7),
        UINT64_C(0x0bb6cde49d8ba257) },
    { UINT64_C(0x590b62c7ff8a513f),
        UINT64_C(0x314b4ce372cacefd),
        UINT64_C(0x6bef32ce94b8a800),
        UINT64_C(0x6ddf84a095713d5f),
        UINT64_C(0x64eace4cb0982191),
        UINT64_C(0x0386213c651b888d) },
    { UINT64_C(0xa5310a31111bbcdd),
        UINT64_C(0xa14ac0f5da148982),
        UINT64_C(0xf9ad9cc95423d2e9),
        UINT64_C(0xaa6ec095283ee4a7),
        UINT64_C(0xcf5b1f022e1c9107),
        UINT64_C(0x01fddf5aed881793) },
    { UINT64_C(0x65a572b0d7a7d950),
        UINT64_C(0xe25c2d8183473a19),
        UINT64_C(0xc2fcebe7cb877dbd),
        UINT64_C(0x05b2d36c769a89b0),
        UINT64_C(0xba12961be86e9efb),
        UINT64_C(0x07eb1b29c1dfde1f) },
    { UINT64_C(0x93e09572f7c4cd24),
        UINT64_C(0x364e929076795091),
        UINT64_C(0x8569467e68af51b5),
        UINT64_C(0xa47da89439f5340f),
        UINT64_C(0xf4fa918082e44d64),
        UINT64_C(0x0ad52ba3e6695a79) },
    { UINT64_C(0x911429844e0d5f54),
        UINT64_C(0xd03f51a3516bb233),
        UINT64_C(0x3d587e5640536e66),
        UINT64_C(0xfa86d2a3a9a73482),
        UINT64_C(0xa90ed5adf1ed5537),
        UINT64_C(0x149c9c326a5e7393) },
    { UINT64_C(0x462bbeb03c12921a),
        UINT64_C(0xdc9af5fa0a274a17),
        UINT64_C(0x9a558ebde836ebed),
        UINT64_C(0x649ef8f11a4fae46),
        UINT64_C(0x8100e1652b3cdc62),
        UINT64_C(0x1862bd62c291dacb) },
    { UINT64_C(0x05c9b8ca89f12c26),
        UINT64_C(0x0194160fa9b9ac4f),
        UINT64_C(0x6a643d5a6879fa2c),
        UINT64_C(0x14665bdd8846e19d),
        UINT64_C(0xbb1d0d53af3ff6bf),
        UINT64_C(0x12c7e1c3b28962e5) },
    { UINT64_C(0xb55ebf900b8a3e17),
        UINT64_C(0xfedc77ec1a9201c4),
        UINT64_C(0x1f07db10ea1a4df4),
        UINT64_C(0x0dfbd15dc41a594d),
        UINT64_C(0x389547f2334a5391),
        UINT64_C(0x02419f98165871a4) },
    { UINT64_C(0xb416af000745fc20),
        UINT64_C(0x8e563e9d1ea6d0f5),
        UINT64_C(0x7c763e17763a0652),
        UINT64_C(0x01458ef0159ebbef),
        UINT64_C(0x8346fe421f96bb13),
        UINT64_C(0x0d2d7b829ce324d2) },
    { UINT64_C(0x93096bb538d64615),
        UINT64_C(0x6f2a2619951d823a),
        UINT64_C(0x8f66b3ea59514fa4),
        UINT64_C(0xf563e63704f7092f),
        UINT64_C(0x724b136c4cf2d9fa),
        UINT64_C(0x046959cfcfd0bf49) },
    { UINT64_C(0xea748d4b6e405346),
        UINT64_C(0x91e9079c2c02d58f),
        UINT64_C(0x41064965946d9b59),
        UINT64_C(0xa06731f1d2bbe1ee),
        UINT64_C(0x07f897e267a33f1b),
        UINT64_C(0x1017290919210e5f) },
    { UINT64_C(0x872aa6c17d985097),
        UINT64_C(0xeecc53161264562a),
        UINT64_C(0x07afe37afff55002),
        UINT64_C(0x54759078e5be6838),
        UINT64_C(0xc4b92d15db8acca8),
        UINT64_C(0x106d87d1b51d13b9) }
  };
  #define H2C_G1_ISO_YDEN_LEN 16
  static const limb_t H2C_G1_ISO_YDEN[16][6] = {
    { UINT64_C(0xeb6c359d47e52b1c),
        UINT64_C(0x18ef5f8a10634d60),
        UINT64_C(0xddfa71a0889d5b7e),
        UINT64_C(0x723e71dcc5fc1323),
        UINT64_C(0x52f45700b70d5c69),
        UINT64_C(0x0a8b981ee47691f1) },
    { UINT64_C(0x616a3c4f5535b9fb),
        UINT64_C(0x6f5f037395dbd911),
        UINT64_C(0xf25f4cc5e35c65da),
        UINT64_C(0x3e50dffea3c62658),
        UINT64_C(0x6a33dca523560776),
        UINT64_C(0x0fadeff77b6bfe3e) },
    { UINT64_C(0x2be9b66df470059c),
        UINT64_C(0x24a2c159a3d36742),
        UINT64_C(0x115dbe7ad10c2a37),
        UINT64_C(0xb6634a652ee5884d),
        UINT64_C(0x04fe8bb2b8d81af4),
        UINT64_C(0x01c2a7a256fe9c41) },
    { UINT64_C(0xf27bf8ef3b75a386),
        UINT64_C(0x898b367476c9073f),
        UINT64_C(0x24482e6b8c2f4e5f),
        UINT64_C(0xc8e0bbd6fe110806),
        UINT64_C(0x59b0c17f7631448a),
        UINT64_C(0x11037cd58b3dbfbd) },
    { UINT64_C(0x31c7912ea267eec6),
        UINT64_C(0x1dbf6f1c5fcdb700),
        UINT64_C(0xd30d4fe3ba86fdb1),
        UINT64_C(0x3cae528fbee9a2a4),
        UINT64_C(0xb1cce69b6aa9ad9a),
        UINT64_C(0x044393bb632d94fb) },
    { UINT64_C(0xc66ef6efeeb5c7e8),
        UINT64_C(0x9824c289dd72bb55),
        UINT64_C(0x71b1a4d2f119981d),
        UINT64_C(0x104fc1aafb0919cc),
        UINT64_C(0x0e49df01d942a628),
        UINT64_C(0x096c3a09773272d4) },
    { UINT64_C(0x9abc11eb5fadeff4),
        UINT64_C(0x32dca50a885728f0),
        UINT64_C(0xfb1fa3721569734c),
        UINT64_C(0xc4b76271ea6506b3),
        UINT64_C(0xd466a75599ce728e),
        UINT64_C(0x0c81d4645f4cb6ed) },
    { UINT64_C(0x4199f10e5b8be45b),
        UINT64_C(0xda64e495b1e87930),
        UINT64_C(0xcb353efe9b33e4ff),
        UINT64_C(0x9e9efb24aa6424c6),
        UINT64_C(0xf08d33680a237465),
        UINT64_C(0x0d3378023e4c7406) },
    { UINT64_C(0x7eb4ae92ec74d3a5),
        UINT64_C(0xc341b4aa9fac3497),
        UINT64_C(0x5be603899e907687),
        UINT64_C(0x03bfd9cca75cbdeb),
        UINT64_C(0x564c2935a96bfa93),
        UINT64_C(0x0ef3c33371e2fdb5) },
    { UINT64_C(0x7ee91fd449f6ac2e),
        UINT64_C(0xe5d5bd5cb9357a30),
        UINT64_C(0x773a8ca5196b1380),
        UINT64_C(0xd0fda172174ed023),
        UINT64_C(0x6cb95e0fa776aead),
        UINT64_C(0x0d22d5a40cec7cff) },
    { UINT64_C(0xf727e09285fd8519),
        UINT64_C(0xdc9d55a83017897b),
        UINT64_C(0x7549d8bd057894ae),
        UINT64_C(0x178419613d90d8f8),
        UINT64_C(0xfce95ebdeb5b490a),
        UINT64_C(0x0467ffaef23fc49e) },
    { UINT64_C(0xc1769e6a7c385f1b),
        UINT64_C(0x79bc930deac01c03),
        UINT64_C(0x5461c75a23ede3b5),
        UINT64_C(0x6e20829e5c230c45),
        UINT64_C(0x828e0f1e772a53cd),
        UINT64_C(0x116aefa749127bff) },
    { UINT64_C(0x101c10bf2744c10a),
        UINT64_C(0xbbf18d053a6a3154),
        UINT64_C(0xa0ecf39ef026f602),
        UINT64_C(0xfc009d4996dc5153),
        UINT64_C(0xb9000209d5bd08d3),
        UINT64_C(0x189e5fe4470cd73c) },
    { UINT64_C(0x7ebd546ca1575ed2),
        UINT64_C(0xe47d5a981d081b55),
        UINT64_C(0x57b2b625b6d4ca21),
        UINT64_C(0xb0a1ba04228520cc),
        UINT64_C(0x98738983c2107ff3),
        UINT64_C(0x13dddbc4799d81d6) },
    { UINT64_C(0x09319f2e39834935),
        UINT64_C(0x039e952cbdb05c21),
        UINT64_C(0x55ba77a9a2f76493),
        UINT64_C(0xfd04e3dfc6086467),
        UINT64_C(0xfb95832e7d78742e),
        UINT64_C(0x0ef9c24eccaf5e0e) },
    { UINT64_C(0x760900000002fffd),
        UINT64_C(0xebf4000bc40c0002),
        UINT64_C(0x5f48985753c758ba),
        UINT64_C(0x77ce585370525745),
        UINT64_C(0x5c071a97a256ec6d),
        UINT64_C(0x15f65ec3fa80e493) }
  };
  static const limb_t H2C_G2_ISO_A[2][6] = {
    { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) },
    { UINT64_C(0xe53a000003135242),
        UINT64_C(0x01080c0fdef80285),
        UINT64_C(0xe7889edbe340f6bd),
        UINT64_C(0x0b51375126310601),
        UINT64_C(0x02d6985717c744ab),
        UINT64_C(0x1220b4e979ea5467) }
  };
  static const limb_t H2C_G2_ISO_B[2][6] = {
    { UINT64_C(0x22ea00000cf89db2),
        UINT64_C(0x6ec832df71380aa4),
        UINT64_C(0x6e1b94403db5a66e),
        UINT64_C(0x75bf3c53a79473ba),
        UINT64_C(0x3dd3a569412c0a34),
        UINT64_C(0x125cdb5e74dc4fd1) },
    { UINT64_C(0x22ea00000cf89db2),
        UINT64_C(0x6ec832df71380aa4),
        UINT64_C(0x6e1b94403db5a66e),
        UINT64_C(0x75bf3c53a79473ba),
        UINT64_C(0x3dd3a569412c0a34),
        UINT64_C(0x125cdb5e74dc4fd1) }
  };
  static const limb_t H2C_G2_Z[2][6] = {
    { UINT64_C(0x87ebfffffff9555c),
        UINT64_C(0x656fffe5da8ffffa),
        UINT64_C(0x0fd0749345d33ad2),
        UINT64_C(0xd951e663066576f4),
        UINT64_C(0xde291a3d41e980d3),
        UINT64_C(0x0815664c7dfe040d) },
    { UINT64_C(0x43f5fffffffcaaae),
        UINT64_C(0x32b7fff2ed47fffd),
        UINT64_C(0x07e83a49a2e99d69),
        UINT64_C(0xeca8f3318332bb7a),
        UINT64_C(0xef148d1ea0f4c069),
        UINT64_C(0x040ab3263eff0206) }
  };
  static const limb_t H2C_G2_MB_OVER_A[2][6] = {
    { UINT64_C(0x903c555555474fb3),
        UINT64_C(0x5f98cc95ce451105),
        UINT64_C(0x9f8e582eefe0fade),
        UINT64_C(0xc68946b6aebbd062),
        UINT64_C(0x467a4ad10ee6de53),
        UINT64_C(0x0e7146f483e23a05) },
    { UINT64_C(0x29c2aaaaaab85af8),
        UINT64_C(0xbf133368e30eeefa),
        UINT64_C(0xc7a27a7206cffb45),
        UINT64_C(0x9dee04ce44c9425c),
        UINT64_C(0x04a15ce53464ce83),
        UINT64_C(0x0b8fcaf5b59dac95) }
  };
  static const limb_t H2C_G2_B_OVER_ZA[2][6] = {
    { UINT64_C(0xf2d8444444414324),
        UINT64_C(0x2585c28393a69d00),
        UINT64_C(0x5dd35cd05d972c42),
        UINT64_C(0xfd963b744ea89b53),
        UINT64_C(0x07f5d9fd91c1fa91),
        UINT64_C(0x127db28a3ce062c4) },
    { UINT64_C(0x55743333333b3695),
        UINT64_C(0xeb72b871590828fc),
        UINT64_C(0x1c186171cb4d5da5),
        UINT64_C(0x34a33031ee956644),
        UINT64_C(0xc971692a149d16d0),
        UINT64_C(0x168a1e1ff5de8b82) }
  };
  #define H2C_G2_ISO_XNUM_LEN 4
  static const limb_t H2C_G2_ISO_XNUM[4][2][6] = {
    { { UINT64_C(0x47f671c71ce05e62),
        UINT64_C(0x06dd57071206393e),
        UINT64_C(0x7c80cd2af3fd71a2),
        UINT64_C(0x048103ea9e6cd062),
        UINT64_C(0xc54516acc8d037f6),
        UINT64_C(0x13808f550920ea41) },
      { UINT64_C(0x47f671c71ce05e62),
        UINT64_C(0x06dd57071206393e),
        UINT64_C(0x7c80cd2af3fd71a2),
        UINT64_C(0x048103ea9e6cd062),
        UINT64_C(0xc54516acc8d037f6),
        UINT64_C(0x13808f550920ea41) } },
    { { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) },
      { UINT64_C(0x5fe55555554c71d0),
        UINT64_C(0x873fffdd236aaaa3),
        UINT64_C(0x6a6b4619b26ef918),
        UINT64_C(0x21c2888408874945),
        UINT64_C(0x2836cda7028cabc5),
        UINT64_C(0x0ac73310a7fd5abd) } },
    { { UINT64_C(0x0a0c5555555971c3),
        UINT64_C(0xdb0c00101f9eaaae),
        UINT64_C(0xb1fb2f941d797997),
        UINT64_C(0xd3960742ef416e1c),
        UINT64_C(0xb70040e2c20556f4),
        UINT64_C(0x149d7861e581393b) },
      { UINT64_C(0xaff2aaaaaaa638e8),
        UINT64_C(0x439fffee91b55551),
        UINT64_C(0xb535a30cd9377c8c),
        UINT64_C(0x90e144420443a4a2),
        UINT64_C(0x941b66d3814655e2),
        UINT64_C(0x0563998853fead5e) } },
    { { UINT64_C(0x40aac71c71c725ed),
        UINT64_C(0x190955557a84e38e),
        UINT64_C(0xd817050a8f41abc3),
        UINT64_C(0xd86485d4c87f6fb1),
        UINT64_C(0x696eb479f885d059),
        UINT64_C(0x198e1a74328002d2) },
      { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) } }
  };
  #define H2C_G2_ISO_XDEN_LEN 4
  static const limb_t H2C_G2_ISO_XDEN[4][2][6] = {
    { { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) },
      { UINT64_C(0x1f3affffff13ab97),
        UINT64_C(0xf25bfc611da3ff3e),
        UINT64_C(0xca3757cb3819b208),
        UINT64_C(0x3e6427366f8cec18),
        UINT64_C(0x03977bc86095b089),
        UINT64_C(0x04f69db13f39a952) } },
    { { UINT64_C(0x447600000027552e),
        UINT64_C(0xdcb8009a43480020),
        UINT64_C(0x6f7ee9ce4a6e8b59),
        UINT64_C(0xb10330b7c0a95bc6),
        UINT64_C(0x6140b1fcfb1e54b7),
        UINT64_C(0x0381be097f0bb4e1) },
      { UINT64_C(0x7588ffffffd8557d),
        UINT64_C(0x41f3ff646e0bffdf),
        UINT64_C(0xf7b1e8d2ac426aca),
        UINT64_C(0xb3741acd32dbb6f8),
        UINT64_C(0xe9daf5b9482d581f),
        UINT64_C(0x167f53e0ba7431b8) } },
    { { UINT64_C(0x760900000002fffd),
        UINT64_C(0xebf4000bc40c0002),
        UINT64_C(0x5f48985753c758ba),
        UINT64_C(0x77ce585370525745),
        UINT64_C(0x5c071a97a256ec6d),
        UINT64_C(0x15f65ec3fa80e493) },
      { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) } },
    { { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) },
      { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) } }
  };
  #define H2C_G2_ISO_YNUM_LEN 4
  static const limb_t H2C_G2_ISO_YNUM[4][2][6] = {
    { { UINT64_C(0x96d8f684bdfc77be),
        UINT64_C(0xb530e4f43b66d0e2),
        UINT64_C(0x184a88ff379652fd),
        UINT64_C(0x57cb23ecfae804e1),
        UINT64_C(0x0fd2e39eada3eba9),
        UINT64_C(0x08c8055e31c5d5c3) },
      { UINT64_C(0x96d8f684bdfc77be),
        UINT64_C(0xb530e4f43b66d0e2),
        UINT64_C(0x184a88ff379652fd),
        UINT64_C(0x57cb23ecfae804e1),
        UINT64_C(0x0fd2e39eada3eba9),
        UINT64_C(0x08c8055e31c5d5c3) } },
    { { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) },
      { UINT64_C(0xbf0a71c71c91b406),
        UINT64_C(0x4d6d55d28b7638fd),
        UINT64_C(0x9d82f98e5f205aee),
        UINT64_C(0xa27aa27b1d1a18d5),
        UINT64_C(0x02c3b2b2d2938e86),
        UINT64_C(0x0c7d13420b09807f) } },
    { { UINT64_C(0xd7f9555555531c74),
        UINT64_C(0x21cffff748daaaa8),
        UINT64_C(0x5a9ad1866c9bbe46),
        UINT64_C(0x4870a2210221d251),
        UINT64_C(0x4a0db369c0a32af1),
        UINT64_C(0x02b1ccc429ff56af) },
      { UINT64_C(0xe205aaaaaaac8e37),
        UINT64_C(0xfcdc000768795556),
        UINT64_C(0x0c96011a8a1537dd),
        UINT64_C(0x1c06a963f163406e),
        UINT64_C(0x010df44c82a881e6),
        UINT64_C(0x174f45260f808feb) } },
    { { UINT64_C(0xa470bda12f67f35c),
        UINT64_C(0xc0fe38e23327b425),
        UINT64_C(0xc9d3d0f2c6f0678d),
        UINT64_C(0x1c55c9935b5a982e),
        UINT64_C(0x27f6c0e2f0746764),
        UINT64_C(0x117c5e6e28aa9054) },
      { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) } }
  };
  #define H2C_G2_ISO_YDEN_LEN 4
  static const limb_t H2C_G2_ISO_YDEN[4][2][6] = {
    { { UINT64_C(0x0162fffffa765adf),
        UINT64_C(0x8f7bea480083fb75),
        UINT64_C(0x561b3c2259e93611),
        UINT64_C(0x11e19fc1a9c875d5),
        UINT64_C(0xca713efc00367660),
        UINT64_C(0x03c6a03d41da1151) },
      { UINT64_C(0x0162fffffa765adf),
        UINT64_C(0x8f7bea480083fb75),
        UINT64_C(0x561b3c2259e93611),
        UINT64_C(0x11e19fc1a9c875d5),
        UINT64_C(0xca713efc00367660),
        UINT64_C(0x03c6a03d41da1151) } },
    { { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) },
      { UINT64_C(0x5db0fffffd3b02c5),
        UINT64_C(0xd713f52358ebfdba),
        UINT64_C(0x5ea60761a84d161a),
        UINT64_C(0xbb2c75a34ea6c44a),
        UINT64_C(0x0ac6735921c1119b),
        UINT64_C(0x0ee3d913bdacfbf6) } },
    { { UINT64_C(0x66b10000003affc5),
        UINT64_C(0xcb1400e764ec0030),
        UINT64_C(0xa73e5eb56fa5d106),
        UINT64_C(0x8984c913a0fe09a9),
        UINT64_C(0x11e10afb78ad7f13),
        UINT64_C(0x05429d0e3e918f52) },
      { UINT64_C(0x534dffffffc4aae6),
        UINT64_C(0x5397ff174c67ffcf),
        UINT64_C(0xbff273eb870b251d),
        UINT64_C(0xdaf2827152870915),
        UINT64_C(0x393a9cbaca9e2dc3),
        UINT64_C(0x14be74dbfaee5748) } },
    { { UINT64_C(0x760900000002fffd),
        UINT64_C(0xebf4000bc40c0002),
        UINT64_C(0x5f48985753c758ba),
        UINT64_C(0x77ce585370525745),
        UINT64_C(0x5c071a97a256ec6d),
        UINT64_C(0x15f65ec3fa80e493) },
      { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) } }
  };
  /* Budroni-Pintore (ePrint 2017/419):
   *   [h_eff]Q = [x^2-x-1]Q + [x-1]psi(Q) + psi^2([2]Q)
   * Two ladders over the short parameter replace one over h_eff.
   * Verified against [h_eff] on random points of the twist before
   * these constants were emitted. */
  #define ELIPS_H2C_G2_FAST_CLEAR 1
  #define H2C_G2_CLEAR_A_BITS 128
  #define H2C_G2_CLEAR_A_NEG  0
  static const limb_t H2C_G2_CLEAR_A[2] = {
        UINT64_C(0xd20100010000ffff),
        UINT64_C(0xac45a4010001a402)
  };
  #define H2C_G2_CLEAR_B_BITS 64
  #define H2C_G2_CLEAR_B_NEG  1
  static const limb_t H2C_G2_CLEAR_B[1] = {
        UINT64_C(0xd201000000010001)
  };
  /* clear_cofactor multipliers. */
  #define H2C_HEFF_G1_BITS  64
  static const limb_t H2C_HEFF_G1[1] = {
        UINT64_C(0xd201000000010001)
  };
  #define H2C_HEFF_G2_BITS  636
  static const limb_t H2C_HEFF_G2[10] = {
        UINT64_C(0xe8020005aaa95551),
        UINT64_C(0x59894c0adebbf6b4),
        UINT64_C(0xe954cbc06689f6a3),
        UINT64_C(0x2ec0ec69d7477c1a),
        UINT64_C(0x6d82bf015d1212b0),
        UINT64_C(0x329c2f178731db95),
        UINT64_C(0x9986ff031508ffe1),
        UINT64_C(0x88e2a8e9145ad768),
        UINT64_C(0x584c6a0ea91b3528),
        UINT64_C(0x0bc69f08f2ee75b3)
  };
#endif

#if defined(ELIPS_CURVE_BLS12_461)
  #define ELIPS_H2C_SUITE_G1 "BLS12461G1_XMD:SHA-256_SVDW_RO_"
  #define ELIPS_H2C_SUITE_G2 "BLS12461G2_XMD:SHA-256_SVDW_RO_"
  /* RFC 9380 5.3: ceil((ceil(log2(p)) + 128) / 8). */
  #define ELIPS_H2C_L        74
  #define ELIPS_H2C_SVDW     1
  /* Shallue-van de Woestijne needs no isogeny; c1..c4 are the
   * precomputed values of RFC 9380 6.6.1. Z was chosen by the
   * Appendix H.1 search, not picked by hand. */
  #define ELIPS_H2C_G1_Z_INT -3
  static const limb_t H2C_G1_Z[8] = {
        UINT64_C(0x241c090809000484),
        UINT64_C(0xc180474fff87a400),
        UINT64_C(0x9cd31258f53ac300),
        UINT64_C(0x357192abd5de93a6),
        UINT64_C(0x47ff1ccded893052),
        UINT64_C(0x095edda76e614a1b),
        UINT64_C(0x03d8c13dae9ed7a6),
        UINT64_C(0x00000000000003ff)
  };
  static const limb_t H2C_G1_C1[8] = {
        UINT64_C(0xbf80453cefaacd49),
        UINT64_C(0xcb6222b551ba9eab),
        UINT64_C(0x4dd6376e0298d6c5),
        UINT64_C(0x0e7966456d4e4f3d),
        UINT64_C(0x4a75ccb378a0b347),
        UINT64_C(0x1bede41aee81c908),
        UINT64_C(0xc838743635c1c5a3),
        UINT64_C(0x000000000000094d)
  };
  static const limb_t H2C_G1_C2[8] = {
        UINT64_C(0x989dfb7ca62aa869),
        UINT64_C(0x9f5fdc5d559178aa),
        UINT64_C(0xc0bd2164dae19ebf),
        UINT64_C(0x7089df8a0f6cd2ec),
        UINT64_C(0x8ed92c65adb67c5b),
        UINT64_C(0xd1e4a5bfa88cca10),
        UINT64_C(0xd358f4ae8305ee82),
        UINT64_C(0x0000000000001355)
  };
  static const limb_t H2C_G1_C3[8] = {
        UINT64_C(0x679058ff690e8a43),
        UINT64_C(0x2f49ff7e931e500b),
        UINT64_C(0x1dc1cc1671707ef4),
        UINT64_C(0x0c89eb3ab4a980b8),
        UINT64_C(0x7b5d78225a423743),
        UINT64_C(0xa23aff91c696e477),
        UINT64_C(0xbf70e58e06348f9e),
        UINT64_C(0x000000000000131e)
  };
  static const limb_t H2C_G1_C4[8] = {
        UINT64_C(0x1632a068ccb0f7b6),
        UINT64_C(0x40b1761e6bfda22c),
        UINT64_C(0xff128929e005ba46),
        UINT64_C(0x4a8aa8064e341c50),
        UINT64_C(0xc953ef82cae7d3ff),
        UINT64_C(0x61172219e3c1ea72),
        UINT64_C(0xafc3e2239fe99d8f),
        UINT64_C(0x0000000000000033)
  };
  #define ELIPS_H2C_G2_Z_INT 1
  static const limb_t H2C_G2_Z[2][8] = {
    { UINT64_C(0xf3f7fcfdfcfffe7f),
        UINT64_C(0xbf9fe840002813ff),
        UINT64_C(0x858af9c903c0bf3f),
        UINT64_C(0x797222a6b311eb88),
        UINT64_C(0x702e5bdd554d59be),
        UINT64_C(0x7e1f20063af2566a),
        UINT64_C(0x53fd14e37575bd1e),
        UINT64_C(0x0000000000001400) },
    { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) }
  };
  static const limb_t H2C_G2_C1[2][8] = {
    { UINT64_C(0x1927f0f346554dcf),
        UINT64_C(0xbd9f892aab733955),
        UINT64_C(0x5f1c36a7bcc7bb3e),
        UINT64_C(0x323009c195e926aa),
        UINT64_C(0x6584e02018966ea6),
        UINT64_C(0x1c4b4dd1a7c5f39b),
        UINT64_C(0x4edc133be1f74841),
        UINT64_C(0x0000000000000eac) },
    { UINT64_C(0xcfdbf3f5f3fff9fb),
        UINT64_C(0xfe1fa0f000a06fff),
        UINT64_C(0xe8b7e7700e85fc3e),
        UINT64_C(0x44008ffadd3357e1),
        UINT64_C(0x282f3f0f67c4296c),
        UINT64_C(0x74c0425ecc910c4f),
        UINT64_C(0x502453a5c6d6e578),
        UINT64_C(0x0000000000001001) }
  };
  static const limb_t H2C_G2_C2[2][8] = {
    { UINT64_C(0x5b5a018156d55616),
        UINT64_C(0x20400be2aa969b55),
        UINT64_C(0xc4cdd86428df2080),
        UINT64_C(0x08e8431ca3a5189b),
        UINT64_C(0xe1552f77a796dd63),
        UINT64_C(0xac3a7a4692658c59),
        UINT64_C(0x80a42034f26fce9b),
        UINT64_C(0x00000000000000aa) },
    { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) }
  };
  static const limb_t H2C_G2_C3[2][8] = {
    { UINT64_C(0x9fa23464d52b18ff),
        UINT64_C(0xe2d860ba0eb57fe6),
        UINT64_C(0x41f63bb18c7384b6),
        UINT64_C(0xe39a80a8bc5bf635),
        UINT64_C(0x5bab8889cfa9efb5),
        UINT64_C(0xfc8945242be1ffbd),
        UINT64_C(0x73d7834a41001ecc),
        UINT64_C(0x0000000000000b12) },
    { UINT64_C(0xb31bb4d9a8744826),
        UINT64_C(0xaaa05ca11b0eba82),
        UINT64_C(0xa83e2cc3bdcdbc29),
        UINT64_C(0xd0f3f22bdad4e2c8),
        UINT64_C(0xcf1cc9639cbff03e),
        UINT64_C(0xd007def3c2116d2b),
        UINT64_C(0xd6e53f04c6132796),
        UINT64_C(0x0000000000000db9) }
  };
  static const limb_t H2C_G2_C4[2][8] = {
    { UINT64_C(0x6cb01411db1c7bd0),
        UINT64_C(0xae009e78e282c1c7),
        UINT64_C(0x400defe220f45c01),
        UINT64_C(0xcc18d42885ee9d72),
        UINT64_C(0x11c52390ba86327d),
        UINT64_C(0xf86109024a9f4f59),
        UINT64_C(0x5de1ad6ca07d6d70),
        UINT64_C(0x00000000000008e1) },
    { UINT64_C(0x23c0100e48e39640),
        UINT64_C(0x58007ec71b9bce39),
        UINT64_C(0x333e5981b3f6b001),
        UINT64_C(0x09ad7686d18bb128),
        UINT64_C(0x0e374fa6fb9e8ecb),
        UINT64_C(0x2d1a6d9b6ee5d914),
        UINT64_C(0xb181578a19fdf127),
        UINT64_C(0x000000000000071a) }
  };
  /* Budroni-Pintore (ePrint 2017/419):
   *   [h_eff]Q = [x^2-x-1]Q + [x-1]psi(Q) + psi^2([2]Q)
   * Two ladders over the short parameter replace one over h_eff.
   * Verified against [h_eff] on random points of the twist before
   * these constants were emitted. */
  #define ELIPS_H2C_G2_FAST_CLEAR 1
  #define H2C_G2_CLEAR_A_BITS 154
  #define H2C_G2_CLEAR_A_NEG  0
  static const limb_t H2C_G2_CLEAR_A[3] = {
        UINT64_C(0xfffbfffdffffffff),
        UINT64_C(0xffff801000102003),
        UINT64_C(0x0000000003fffffe)
  };
  #define H2C_G2_CLEAR_B_BITS 77
  #define H2C_G2_CLEAR_B_NEG  1
  static const limb_t H2C_G2_CLEAR_B[2] = {
        UINT64_C(0xfffbfffe00000001),
        UINT64_C(0x0000000000001fff)
  };
  /* clear_cofactor multipliers. */
  #define H2C_HEFF_G1_BITS  77
  static const limb_t H2C_HEFF_G1[2] = {
        UINT64_C(0xfffbfffe00000001),
        UINT64_C(0x0000000000001fff)
  };
  #define H2C_HEFF_G2_BITS  769
  static const limb_t H2C_HEFF_G2[13] = {
        UINT64_C(0x555aaaad55555551),
        UINT64_C(0xff5d2aeaab052ac1),
        UINT64_C(0x07e955a96b2fa964),
        UINT64_C(0xc267e8b56040be95),
        UINT64_C(0x9ebbc31309c3dafc),
        UINT64_C(0xef5e397e93e9a158),
        UINT64_C(0x716d34faeb33db41),
        UINT64_C(0x4f273e05862a6ae2),
        UINT64_C(0x9211afd9f5694b10),
        UINT64_C(0x7a51735abcbbfec7),
        UINT64_C(0x45303b87e1440b0b),
        UINT64_C(0x555553aaa9d64556),
        UINT64_C(0x0000000000000001)
  };
#endif

#if defined(ELIPS_CURVE_BN_462)
  #define ELIPS_H2C_SUITE_G1 "BN462G1_XMD:SHA-256_SVDW_RO_"
  #define ELIPS_H2C_SUITE_G2 "BN462G2_XMD:SHA-256_SVDW_RO_"
  /* RFC 9380 5.3: ceil((ceil(log2(p)) + 128) / 8). */
  #define ELIPS_H2C_L        74
  #define ELIPS_H2C_SVDW     1
  /* Shallue-van de Woestijne needs no isogeny; c1..c4 are the
   * precomputed values of RFC 9380 6.6.1. Z was chosen by the
   * Appendix H.1 search, not picked by hand. */
  #define ELIPS_H2C_G1_Z_INT 1
  static const limb_t H2C_G1_Z[8] = {
        UINT64_C(0x3e11eeb41eee70a8),
        UINT64_C(0x2eea3e13fec5661f),
        UINT64_C(0x31530e1535b28153),
        UINT64_C(0x68ceb6920acb7c40),
        UINT64_C(0xfd303bfd856dff73),
        UINT64_C(0xffaffe8680658205),
        UINT64_C(0xfde7f1801dfec009),
        UINT64_C(0x0000000000000fe5)
  };
  static const limb_t H2C_G1_C1[8] = {
        UINT64_C(0x8dcd93f4235bae2e),
        UINT64_C(0x6051324403afcda2),
        UINT64_C(0x6c06d5ae5db674e6),
        UINT64_C(0xeab4facd6fa1ab3f),
        UINT64_C(0x88034c076fb60355),
        UINT64_C(0x00eff26a98bce9a1),
        UINT64_C(0x06b42dbfaa83bfe2),
        UINT64_C(0x0000000000001857)
  };
  static const limb_t H2C_G1_C2[8] = {
        UINT64_C(0x84f8b8ae309c47bf),
        UINT64_C(0x5f12d736009d4cf0),
        UINT64_C(0xe75678ec648dbbc6),
        UINT64_C(0x5e2933f8c29c51df),
        UINT64_C(0xc131e2013d49011e),
        UINT64_C(0x0027f7bbccc3f6d6),
        UINT64_C(0x8142085ff3409ffb),
        UINT64_C(0x0000000000001c11)
  };
  static const limb_t H2C_G1_C3[8] = {
        UINT64_C(0x8dcd93f4235bae2e),
        UINT64_C(0x6051324403afcda2),
        UINT64_C(0x6c06d5ae5db674e6),
        UINT64_C(0xeab4facd6fa1ab3f),
        UINT64_C(0x88034c076fb60355),
        UINT64_C(0x00eff26a98bce9a1),
        UINT64_C(0x06b42dbfaa83bfe2),
        UINT64_C(0x0000000000001857)
  };
  static const limb_t H2C_G1_C4[8] = {
        UINT64_C(0xd4460ac83ba6428d),
        UINT64_C(0xc521020ffb15987c),
        UINT64_C(0xc54c385dd76308dc),
        UINT64_C(0x90aa4b06632be100),
        UINT64_C(0x34f6eff615b7fcf5),
        UINT64_C(0xfec0031af49f503e),
        UINT64_C(0x7769c4e075bb0027),
        UINT64_C(0x0000000000001b93)
  };
  #define ELIPS_H2C_G2_Z_INT 1
  static const limb_t H2C_G2_Z[2][8] = {
    { UINT64_C(0x3e11eeb41eee70a8),
        UINT64_C(0x2eea3e13fec5661f),
        UINT64_C(0x31530e1535b28153),
        UINT64_C(0x68ceb6920acb7c40),
        UINT64_C(0xfd303bfd856dff73),
        UINT64_C(0xffaffe8680658205),
        UINT64_C(0xfde7f1801dfec009),
        UINT64_C(0x0000000000000fe5) },
    { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) }
  };
  static const limb_t H2C_G2_C1[2][8] = {
    { UINT64_C(0x8dcd93f4235bae2e),
        UINT64_C(0x6051324403afcda2),
        UINT64_C(0x6c06d5ae5db674e6),
        UINT64_C(0xeab4facd6fa1ab3f),
        UINT64_C(0x88034c076fb60355),
        UINT64_C(0x00eff26a98bce9a1),
        UINT64_C(0x06b42dbfaa83bfe2),
        UINT64_C(0x0000000000001857) },
    { UINT64_C(0x4fbba540046d3d86),
        UINT64_C(0x3166f43004ea6783),
        UINT64_C(0x3ab3c7992803f393),
        UINT64_C(0x81e6443b64d62eff),
        UINT64_C(0x8ad31009ea4803e2),
        UINT64_C(0x013ff3e41857679b),
        UINT64_C(0x08cc3c3f8c84ffd8),
        UINT64_C(0x0000000000000871) }
  };
  static const limb_t H2C_G2_C2[2][8] = {
    { UINT64_C(0x84f8b8ae309c47bf),
        UINT64_C(0x5f12d736009d4cf0),
        UINT64_C(0xe75678ec648dbbc6),
        UINT64_C(0x5e2933f8c29c51df),
        UINT64_C(0xc131e2013d49011e),
        UINT64_C(0x0027f7bbccc3f6d6),
        UINT64_C(0x8142085ff3409ffb),
        UINT64_C(0x0000000000001c11) },
    { UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000) }
  };
  static const limb_t H2C_G2_C3[2][8] = {
    { UINT64_C(0x6634d0ce0af27638),
        UINT64_C(0xfcb77bdb1d24832f),
        UINT64_C(0xf654cb4a5afc4857),
        UINT64_C(0xce099f5673646ca2),
        UINT64_C(0xfc5cf598c33666e8),
        UINT64_C(0x00bff53aaa896f74),
        UINT64_C(0x610179f90a02ffe8),
        UINT64_C(0x00000000000010d6) },
    { UINT64_C(0x57980e6c2a2e93a3),
        UINT64_C(0xfd18fe89c5b6f9a1),
        UINT64_C(0x13566962496e6bbf),
        UINT64_C(0x767d5094e13936ba),
        UINT64_C(0xc71014ce79933306),
        UINT64_C(0xfe800c89b7e3d8ef),
        UINT64_C(0xbe330d2dee3a002f),
        UINT64_C(0x0000000000000257) }
  };
  static const limb_t H2C_G2_C4[2][8] = {
    { UINT64_C(0xd4460ac83ba6428d),
        UINT64_C(0xc521020ffb15987c),
        UINT64_C(0xc54c385dd76308dc),
        UINT64_C(0x90aa4b06632be100),
        UINT64_C(0x34f6eff615b7fcf5),
        UINT64_C(0xfec0031af49f503e),
        UINT64_C(0x7769c4e075bb0027),
        UINT64_C(0x0000000000001b93) },
    { UINT64_C(0xf7065e580f74d8a9),
        UINT64_C(0x104eb72aa41ccb50),
        UINT64_C(0xb1baf5db751d0f61),
        UINT64_C(0x58fd2a1c118dc6ab),
        UINT64_C(0x86d495481cf5506f),
        UINT64_C(0x53aab7cf8e885dce),
        UINT64_C(0x1f01b00b45640035),
        UINT64_C(0x00000000000000c0) }
  };
  /* clear_cofactor multipliers. */
  #define H2C_HEFF_G1_BITS  1
  static const limb_t H2C_HEFF_G1[1] = {
        UINT64_C(0x0000000000000001)
  };
  #define H2C_HEFF_G2_BITS  462
  static const limb_t H2C_HEFF_G2[8] = {
        UINT64_C(0x2401b008a0168019),
        UINT64_C(0xf5f7f4c000000000),
        UINT64_C(0xfffffff6ff66fc63),
        UINT64_C(0x12908fa1ce0227ff),
        UINT64_C(0xbfca0000000000d8),
        UINT64_C(0xfffff6ff0cf6b7d9),
        UINT64_C(0x80360120023fffff),
        UINT64_C(0x0000000000002404)
  };
#endif


#ifndef ELIPS_H2C_L
#  error "No curve selected, or this curve has no hash-to-curve parameters."
#endif

#endif /* ELIPS_H2C_PARAMS_H */
