src/bls12_timeprint.c File Reference
#include <ELiPS_bn_bls/bls12_timeprint.h>
Functions
void bls12_print_tate_time ()
void bls12_print_plain_ate_time ()
void bls12_print_opt_ate_time ()
void bls12_print_final_exp_plain_time ()
void bls12_print_final_exp_optimal_time ()
void bls12_print_plain_G1_scm_time ()
void bls12_print_2split_G1_scm_time ()
void bls12_print_plain_G2_scm_time ()
void bls12_print_2split_G2_scm_time ()
void bls12_print_4split_G2_scm_time ()
void bls12_print_plain_G3_exp_time ()
void bls12_print_2split_G3_exp_time ()
void bls12_print_4split_G3_exp_time ()
Variables
double bls12_MILLER_TATE
double bls12_MILLER_PLAINATE
double bls12_MILLER_OPTATE
double bls12_FINALEXP_PLAIN
double bls12_FINALEXP_OPT
double bls12_G1SCM_PLAIN
double bls12_G1SCM_2SPLIT
double bls12_G2SCM_PLAIN
double bls12_G2SCM_2SPLIT
double bls12_G2SCM_4SPLIT
double bls12_G3EXP_PLAIN
double bls12_G3EXP_2SPLIT
double bls12_G3EXP_4SPLIT
Function Documentation
bls12_print_2split_G1_scm_time()
void bls12_print_2split_G1_scm_time (void)
Prints 2 split of scalr G1 scm time: BLS12 curve
References bls12_G1SCM_2SPLIT.
Referenced by bls12_test_G1_scm().
                                     {
    printf("2split-G1-SCM time:%.2f[ms]\n",bls12_G1SCM_2SPLIT);
}
bls12_print_2split_G2_scm_time()
void bls12_print_2split_G2_scm_time (void)
Prints 2 split of scalr G2 scm time: BLS12 curve
References bls12_G2SCM_2SPLIT.
Referenced by bls12_test_G2_scm().
                                     {
    printf("2split-G2-SCM time:%.2f[ms]\n",bls12_G2SCM_2SPLIT);
}
bls12_print_2split_G3_exp_time()
void bls12_print_2split_G3_exp_time (void)
Prints 2 split of scalr G3 exponentiation time: BLS12 curve
References bls12_G3EXP_2SPLIT.
Referenced by bls12_test_G3_exp().
                                     {
    printf("2split-G3-SCM time:%.2f[ms]\n",bls12_G3EXP_2SPLIT);
}
bls12_print_4split_G2_scm_time()
void bls12_print_4split_G2_scm_time (void)
Prints 4 split of scalr G2 scm time: BLS12 curve
References bls12_G2SCM_4SPLIT.
Referenced by bls12_test_G2_scm().
                                     {
    printf("4split-G2-SCM time:%.2f[ms]\n",bls12_G2SCM_4SPLIT);
}
bls12_print_4split_G3_exp_time()
void bls12_print_4split_G3_exp_time (void)
Prints 2 split of scalr G3 exponentiation time: BLS12 curve
References bls12_G3EXP_4SPLIT.
Referenced by bls12_test_G3_exp().
                                     {
    printf("4split-G3-SCM time:%.2f[ms]\n",bls12_G3EXP_4SPLIT);
}
bls12_print_final_exp_optimal_time()
void bls12_print_final_exp_optimal_time (void)
Prints efficient final exp time: BLS12 curve
References bls12_FINALEXP_OPT.
Referenced by bls12_test_opt_ate_pairing(), bls12_test_plain_ate_pairing(), and bls12_test_tate_pairing().
                                         {
    printf("optimal-final exp time:%.2f[ms]\n",bls12_FINALEXP_OPT);
}
bls12_print_final_exp_plain_time()
void bls12_print_final_exp_plain_time (void)
Prints plain final exp time: BLS12 curve
References bls12_FINALEXP_PLAIN.
                                       {
    printf("plain-final exp time:%.2f[ms]\n",bls12_FINALEXP_PLAIN);
}
bls12_print_opt_ate_time()
void bls12_print_opt_ate_time (void)
Prints opt-ate paring time: BLS12 curve
References bls12_MILLER_OPTATE.
Referenced by bls12_test_opt_ate_pairing().
                               {
    printf("miller opt-ate time:%.2f[ms]\n",bls12_MILLER_OPTATE);
}
bls12_print_plain_ate_time()
void bls12_print_plain_ate_time (void)
Prints ate paring time: BLS12 curve
References bls12_MILLER_PLAINATE.
Referenced by bls12_test_plain_ate_pairing().
                                 {
    printf("miller plain-ate time:%.2f[ms]\n",bls12_MILLER_PLAINATE);
}
bls12_print_plain_G1_scm_time()
void bls12_print_plain_G1_scm_time (void)
Prints plain G1 scm time: BLS12 curve
References bls12_G1SCM_PLAIN.
Referenced by bls12_test_G1_scm().
                                    {
    printf("plain-G1-SCM time:%.2f[ms]\n",bls12_G1SCM_PLAIN);
}
bls12_print_plain_G2_scm_time()
void bls12_print_plain_G2_scm_time (void)
Prints plain G2 scm time: BLS12 curve
References bls12_G2SCM_PLAIN.
Referenced by bls12_test_G2_scm().
                                    {
    printf("plain-G2-SCM time:%.2f[ms]\n",bls12_G2SCM_PLAIN);
}
bls12_print_plain_G3_exp_time()
void bls12_print_plain_G3_exp_time (void)
Prints no split of scalr G3 exponentiation time: BLS12 curve
References bls12_G3EXP_PLAIN.
Referenced by bls12_test_G3_exp().
                                    {
    printf("plain-G3-SCM time:%.2f[ms]\n",bls12_G3EXP_PLAIN);
}
bls12_print_tate_time()
void bls12_print_tate_time (void)
Prints Tate paring time: BLS12 curve
References bls12_MILLER_TATE.
Referenced by bls12_test_tate_pairing().
                            {
    printf("miller tate time:%.2f[ms]\n",bls12_MILLER_TATE);
}
Variable Documentation
bls12_FINALEXP_OPT
double bls12_FINALEXP_OPT
Referenced by bls12_opt_ate(), bls12_plain_ate(), bls12_print_final_exp_optimal_time(), and bls12_tate().
bls12_FINALEXP_PLAIN
double bls12_FINALEXP_PLAIN
Referenced by bls12_print_final_exp_plain_time().
bls12_G1SCM_2SPLIT
double bls12_G1SCM_2SPLIT
Referenced by bls12_2split_G1_scm(), and bls12_print_2split_G1_scm_time().
bls12_G1SCM_PLAIN
double bls12_G1SCM_PLAIN
Referenced by bls12_plain_G1_scm(), and bls12_print_plain_G1_scm_time().
bls12_G2SCM_2SPLIT
double bls12_G2SCM_2SPLIT
Referenced by bls12_2split_G2_scm(), and bls12_print_2split_G2_scm_time().
bls12_G2SCM_4SPLIT
double bls12_G2SCM_4SPLIT
Referenced by bls12_4split_G2_scm(), and bls12_print_4split_G2_scm_time().
bls12_G2SCM_PLAIN
double bls12_G2SCM_PLAIN
Referenced by bls12_plain_G2_scm(), and bls12_print_plain_G2_scm_time().
bls12_G3EXP_2SPLIT
double bls12_G3EXP_2SPLIT
Referenced by bls12_2split_G3_exp(), and bls12_print_2split_G3_exp_time().
bls12_G3EXP_4SPLIT
double bls12_G3EXP_4SPLIT
Referenced by bls12_4split_G3_exp(), and bls12_print_4split_G3_exp_time().
bls12_G3EXP_PLAIN
double bls12_G3EXP_PLAIN
Referenced by bls12_plain_G3_exp(), and bls12_print_plain_G3_exp_time().
bls12_MILLER_OPTATE
double bls12_MILLER_OPTATE
Referenced by bls12_opt_ate(), and bls12_print_opt_ate_time().
bls12_MILLER_PLAINATE
double bls12_MILLER_PLAINATE
Referenced by bls12_plain_ate(), and bls12_print_plain_ate_time().
bls12_MILLER_TATE
double bls12_MILLER_TATE
Time types of different operations.
Referenced by bls12_print_tate_time(), and bls12_tate().