src/bls12_pairings.c File Reference
#include <ELiPS_bn_bls/bls12_pairings.h>
Functions
void bls12_tate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
void bls12_plain_ate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
void bls12_opt_ate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
Function Documentation
bls12_opt_ate()
void bls12_opt_ate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
Calculate optimal ate pairing in BLS12 curve.
Parameters
out ANS - output
in P - P in G1 mapped to Fp12.
in Q - Q in G2.
References bls12_FINALEXP_OPT, bls12_finalexp_optimal(), bls12_Miller_algo_for_opt_ate(), bls12_MILLER_OPTATE, t1, and timedifference_msec().
Referenced by bls12_test_G3_exp(), and bls12_test_opt_ate_pairing().
                                                {
    //miller
    gettimeofday(&t0,NULL);
    bls12_Miller_algo_for_opt_ate(ANS,P,Q);
    gettimeofday(&t1,NULL);
    bls12_MILLER_OPTATE=timedifference_msec(t0,
      t1);
    
    //final exp
    gettimeofday(&t0,NULL);
    bls12_finalexp_optimal(ANS,ANS);
    gettimeofday(&t1,NULL);
    bls12_FINALEXP_OPT=timedifference_msec(t0,
      t1);
}
bls12_plain_ate()
void bls12_plain_ate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
Calculate ate pairing in BLS12 curve.
Parameters
out ANS - output
in P - P in G1 mapped to Fp12.
in Q - Q in G2.
References bls12_FINALEXP_OPT, bls12_finalexp_optimal(), bls12_Miller_algo_for_plain_ate(), bls12_MILLER_PLAINATE, t1, and timedifference_msec().
Referenced by bls12_test_plain_ate_pairing().
                                                 {
    //miller
    gettimeofday(&t0,NULL);
    bls12_Miller_algo_for_plain_ate(ANS,P,Q);
    gettimeofday(&t1,NULL);
    bls12_MILLER_PLAINATE=timedifference_msec(t0,
      t1);
    
    //final exp
    gettimeofday(&t0,NULL);
    bls12_finalexp_optimal(ANS,ANS);
    gettimeofday(&t1,NULL);
    bls12_FINALEXP_OPT=timedifference_msec(t0,
      t1);
}
bls12_tate()
void bls12_tate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
Calculate tate pairing in BLS12 curve.
Parameters
out ANS - output
in P - P in G1 mapped to Fp12.
in Q - Q in G2.
References bls12_FINALEXP_OPT, bls12_finalexp_optimal(), bls12_Miller_algo_for_tate(), bls12_MILLER_TATE, t1, and timedifference_msec().
Referenced by bls12_test_tate_pairing().
                                             {
    //miller
    gettimeofday(&t0,NULL);
    bls12_Miller_algo_for_tate(ANS,P,Q);
    gettimeofday(&t1,NULL);
    bls12_MILLER_TATE=timedifference_msec(t0,
      t1);
    
    //final exp
    gettimeofday(&t0,NULL);
    bls12_finalexp_optimal(ANS,ANS);
    gettimeofday(&t1,NULL);
    bls12_FINALEXP_OPT=timedifference_msec(t0,
      t1);
}