src/bls12_line_ate.c File Reference
#include <ELiPS_bn_bls/bls12_line_ate.h>
Functions
void bls12_ff_ltt (Fp12 *f, EFp2 *T, EFp *P, Fp *L)
void bls12_f_ltq (Fp12 *f, EFp2 *T, EFp2 *Q, EFp *P, Fp *L)
Function Documentation
bls12_f_ltq()
void bls12_f_ltq (Fp12 * f, EFp2 * T, EFp2 * Q, EFp * P, Fp * L)
Calculate line equation ltq that goes through T,Q and P in Miller's algo.
Parameters
out f - output in Fp12
in T - Input rational point T in Fp2.
in Q - Input rational point Q mapped in Fp2.
in P - Input rational point P mapped in Fp.
in L - Input element L in mapped Fp after precomputation in Miller's algo.
References bls12_Pseudo_8_sparse_mul(), EFp2_clear(), EFp2_init(), EFp2_set(), Fp12_clear(), Fp12_init(), Fp2_add(), Fp2_clear(), Fp2_init(), Fp2_inv(), Fp2_inv_basis(), Fp2_mul(), Fp2_mul_mpz(), Fp2_set_neg(), Fp2_sqr(), Fp2_sub(), Fp_set_ui(), EFp2::x, Fp::x0, Fp6::x0, Fp12::x0, Fp6::x1, Fp12::x1, Fp6::x2, and EFp2::y.
Referenced by bls12_Miller_algo_for_opt_ate(), and bls12_Miller_algo_for_plain_ate().
                                                      {
    EFp2 Tmp_T;
    EFp2_init(&Tmp_T);
    Fp12 ltq;
    Fp12_init(&ltq);
    Fp2 A,B,C,D,E;
    Fp2_init(&A);
    Fp2_init(&B);
    Fp2_init(&C);
    Fp2_init(&D);
    Fp2_init(&E);
    EFp2_set(&Tmp_T,T);
    
    //ltq
    Fp2_sub(&A,&Q->x,&Tmp_T.x); //A=(Q->x-T.x)^-1
    Fp2_inv(&A,&A);
    Fp2_sub(&B,&Q->y,&Tmp_T.y); //B=(Q->y-T.y)
    Fp2_mul(&C,&A,&B); //C=A*B
    Fp2_add(&D,&Tmp_T.x,&Q->x); //D=Q->x+T.x
    Fp2_sqr(&T->x,&C); //next_T.x=C^2-D
    Fp2_sub(&T->x,&T->x,&D);
    Fp2_mul(&E,&C,&Tmp_T.x); //E=C*T.x-T.y
    Fp2_sub(&E,&E,&Tmp_T.y);
    Fp2_mul(&T->y,&C,&T->x); //next_T.y=E-C*next_T.x
    Fp2_sub(&T->y,&E,&T->y);
    
    //set ltq
    Fp_set_ui(&ltq.x0.x0.x0,1);
    Fp2_set_neg(&ltq.x1.x2,&C);
    Fp2_inv_basis(&ltq.x1.x2,&ltq.x1.x2);
    Fp2_mul_mpz(&ltq.x1.x1,&E,L->x0);
    Fp2_inv_basis(&ltq.x1.x1,&ltq.x1.x1);
    
    bls12_Pseudo_8_sparse_mul(f,f,&ltq);
    
    EFp2_clear(&Tmp_T);
    Fp12_clear(&ltq);
    Fp2_clear(&A);
    Fp2_clear(&B);
    Fp2_clear(&C);
    Fp2_clear(&D);
}
bls12_ff_ltt()
void bls12_ff_ltt (Fp12 * f, EFp2 * T, EFp * P, Fp * L)
Calculate line equation ltt that goes through T and P in Miller's algo.
Parameters
out f - output in Fp12
in T - Input rational point T in Fp2.
in P - Input rational point P in mapped Fp.
in L - Input element L in mapped Fp after precomputation in Miller's algo.
References bls12_Pseudo_8_sparse_mul(), EFp2_clear(), EFp2_init(), EFp2_set(), Fp12_clear(), Fp12_init(), Fp12_sqr(), Fp2_add(), Fp2_clear(), Fp2_init(), Fp2_inv(), Fp2_inv_basis(), Fp2_mul(), Fp2_mul_mpz(), Fp2_mul_ui(), Fp2_set_neg(), Fp2_sqr(), Fp2_sub(), Fp_set_ui(), EFp2::x, Fp::x0, Fp6::x0, Fp12::x0, Fp6::x1, Fp12::x1, Fp6::x2, and EFp2::y.
Referenced by bls12_Miller_algo_for_opt_ate(), and bls12_Miller_algo_for_plain_ate().
                                               {
    EFp2 Tmp_T;
    EFp2_init(&Tmp_T);
    Fp12 ff,ltt;
    Fp12_init(&ff);
    Fp12_init(&ltt);
    Fp2 A,B,C,D,E;
    Fp2_init(&A);
    Fp2_init(&B);
    Fp2_init(&C);
    Fp2_init(&D);
    Fp2_init(&E);
    EFp2_set(&Tmp_T,T);
    
    Fp12_sqr(&ff,f);
    
    //ltt
    Fp2_add(&A,&Tmp_T.y,&Tmp_T.y); //A=1/(2*T.y)
    Fp2_inv(&A,&A);
    Fp2_sqr(&B,&Tmp_T.x); //B=3(T.x)^2
    Fp2_mul_ui(&B,&B,3);
    Fp2_mul(&C,&A,&B); //C=A*B
    Fp2_add(&D,&Tmp_T.x,&Tmp_T.x); //D=2T.x
    Fp2_sqr(&T->x,&C); //next_T.x=C^2-D
    Fp2_sub(&T->x,&T->x,&D);
    Fp2_mul(&E,&C,&Tmp_T.x); //E=C*T.x-T.y
    Fp2_sub(&E,&E,&Tmp_T.y);
    Fp2_mul(&T->y,&C,&T->x); //next_T.y=E-C*next_T.x
    Fp2_sub(&T->y,&E,&T->y);
    
    //set ltt
    Fp_set_ui(&ltt.x0.x0.x0,1);
    Fp2_set_neg(&ltt.x1.x2,&C);
    Fp2_inv_basis(&ltt.x1.x2,&ltt.x1.x2);
    Fp2_mul_mpz(&ltt.x1.x1,&E,L->x0);
    Fp2_inv_basis(&ltt.x1.x1,&ltt.x1.x1);
    
    bls12_Pseudo_8_sparse_mul(f,&ff,&ltt);
    
    EFp2_clear(&Tmp_T);
    Fp2_clear(&A);
    Fp2_clear(&B);
    Fp2_clear(&C);
    Fp2_clear(&D);
    Fp2_clear(&E);
    Fp12_clear(&ff);
    Fp12_clear(&ltt);
}