src/bls12_twist.c File Reference
#include <ELiPS_bn_bls/bls12_twist.h>
Functions
void bls12_EFp12_to_EFp (EFp *ANS, EFp12 *P)
void bls12_EFp_to_EFp12 (EFp12 *ANS, EFp *P)
void bls12_EFp12_to_EFp2 (EFp2 *ANS, EFp12 *P)
void bls12_EFp2_to_EFp12 (EFp12 *ANS, EFp2 *P)
Function Documentation
bls12_EFp12_to_EFp()
void bls12_EFp12_to_EFp (EFp * ANS, EFp12 * P)
Calculate primary twist of G1 rational point
Parameters
out ANS - output in EFp
in P - input P in EFp12.
References Fp_set(), EFp::infinity, EFp12::infinity, EFp::x, EFp12::x, Fp6::x0, Fp12::x0, EFp::y, and EFp12::y.
Referenced by bls12_2split_G1_scm(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_Miller_algo_for_tate(), and bls12_plain_G1_scm().
                                          {
    Fp_set(&ANS->x,&P->x.x0.x0.x0);
    Fp_set(&ANS->y,&P->y.x0.x0.x0);
    ANS->infinity=P->infinity;
}
bls12_EFp12_to_EFp2()
void bls12_EFp12_to_EFp2 (EFp2 * ANS, EFp12 * P)
Calculate sextic twisted map G2 rational point
Parameters
out ANS - output in EFp2
in P - input P in EFp12.
References Fp2_mul_basis(), Fp2_set(), Fp2_set_ui(), EFp2::infinity, EFp12::infinity, EFp2::x, EFp12::x, Fp12::x0, Fp6::x1, Fp12::x1, Fp6::x2, EFp2::y, and EFp12::y.
Referenced by bls12_2split_G2_scm(), bls12_4split_G2_scm(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), and bls12_plain_G2_scm().
                                            {
    Fp2_set_ui(&ANS->x,0);
    Fp2_set(&ANS->x,&P->x.x0.x2);
    Fp2_mul_basis(&ANS->x,&ANS->x);
    Fp2_set_ui(&ANS->y,0);
    Fp2_set(&ANS->y,&P->y.x1.x1);
    Fp2_mul_basis(&ANS->y,&ANS->y);
    ANS->infinity=P->infinity;
}
bls12_EFp2_to_EFp12()
void bls12_EFp2_to_EFp12 (EFp12 * ANS, EFp2 * P)
Calculate sextic twisted map G2 rational point
Parameters
out ANS - output in EFp12
in P - input P in EFp2.
References Fp12_set_ui(), Fp2_inv_basis(), Fp2_set(), EFp2::infinity, EFp12::infinity, EFp2::x, EFp12::x, Fp12::x0, Fp6::x1, Fp12::x1, Fp6::x2, EFp2::y, and EFp12::y.
Referenced by bls12_2split_G2_scm(), bls12_4split_G2_scm(), and bls12_plain_G2_scm().
                                            {
    Fp12_set_ui(&ANS->x,0);
    Fp2_set(&ANS->x.x0.x2,&P->x);
    Fp2_inv_basis(&ANS->x.x0.x2,&ANS->x.x0.x2);
    Fp12_set_ui(&ANS->y,0);
    Fp2_set(&ANS->y.x1.x1,&P->y);
    Fp2_inv_basis(&ANS->y.x1.x1,&ANS->y.x1.x1);
    ANS->infinity=P->infinity;
}
bls12_EFp_to_EFp12()
void bls12_EFp_to_EFp12 (EFp12 * ANS, EFp * P)
Calculate primary twist of G1 rational point
Parameters
out ANS - output in EFp12
in P - input P in EFp.
References Fp_set(), EFp::infinity, EFp12::infinity, EFp::x, EFp12::x, Fp6::x0, Fp12::x0, EFp::y, and EFp12::y.
Referenced by bls12_2split_G1_scm(), bls12_generate_G1_point(), and bls12_plain_G1_scm().
                                          {
    Fp_set(&ANS->x.x0.x0.x0,&P->x);
    Fp_set(&ANS->y.x0.x0.x0,&P->y);
    ANS->infinity=P->infinity;
}