src/bls12_frobenius.c File Reference
#include <ELiPS_bn_bls/bls12_frobenius.h>
Functions
void bls12_Fp12_frobenius_map_p1 (Fp12 *ANS, Fp12 *A)
void bls12_Fp12_frobenius_map_p2 (Fp12 *ANS, Fp12 *A)
void bls12_Fp12_frobenius_map_p3 (Fp12 *ANS, Fp12 *A)
void bls12_Fp12_frobenius_map_p4 (Fp12 *ANS, Fp12 *A)
void bls12_Fp12_frobenius_map_p6 (Fp12 *ANS, Fp12 *A)
void bls12_Fp12_frobenius_map_p8 (Fp12 *ANS, Fp12 *A)
void bls12_Fp12_frobenius_map_p10 (Fp12 *ANS, Fp12 *A)
Function Documentation
bls12_Fp12_frobenius_map_p1()
void bls12_Fp12_frobenius_map_p1 (Fp12 * ANS, Fp12 * A)
Calculate Frobenius map of A in Fp12 extension field as A^p where p is the BLS12 prime.
Parameters
out ANS - the result.
in A - the input vecotr.
References d12_frobenius_constant, f_p1, Fp2_mul(), Fp2_mul_mpz(), Fp_clear(), Fp_init(), Fp_set(), Fp_set_neg(), Fp::x0, Fp6::x0, Fp12::x0, Fp2::x1, Fp6::x1, Fp12::x1, and Fp6::x2.
Referenced by bls12_4split_G3_exp(), bls12_finalexp_optimal(), and bls12_generate_G2_point().
                                                   {
    Fp tmp;
    Fp_init(&tmp);
    
    //x0
    Fp_set(&ANS->x0.x0.x0,&A->x0.x0.x0);
    Fp_set_neg(&ANS->x0.x0.x1,&A->x0.x0.x1);
    Fp_set(&tmp,&A->x0.x1.x0);
    Fp_set(&ANS->x0.x1.x0,&A->x0.x1.x1);
    Fp_set(&ANS->x0.x1.x1,&tmp);
    Fp2_mul_mpz(&ANS->x0.x1,&ANS->x0.x1,
      d12_frobenius_constant[f_p1][1].x1.x0);
    Fp_set(&ANS->x0.x2.x0,&A->x0.x2.x0);
    Fp_set_neg(&ANS->x0.x2.x1,&A->x0.x2.x1);
    Fp2_mul_mpz(&ANS->x0.x2,&ANS->x0.x2,
      d12_frobenius_constant[f_p1][2].x0.x0);
    //x1
    Fp_set(&ANS->x1.x0.x0,&A->x1.x0.x0);
    Fp_set_neg(&ANS->x1.x0.x1,&A->x1.x0.x1);
    Fp2_mul(&ANS->x1.x0,&ANS->x1.x0,&d12_frobenius_constant[
      f_p1][3]);
    Fp_set(&ANS->x1.x1.x0,&A->x1.x1.x0);
    Fp_set_neg(&ANS->x1.x1.x1,&A->x1.x1.x1);
    Fp2_mul(&ANS->x1.x1,&ANS->x1.x1,&d12_frobenius_constant[
      f_p1][4]);
    Fp_set(&ANS->x1.x2.x0,&A->x1.x2.x0);
    Fp_set_neg(&ANS->x1.x2.x1,&A->x1.x2.x1);
    Fp2_mul(&ANS->x1.x2,&ANS->x1.x2,&d12_frobenius_constant[
      f_p1][5]);
    
    Fp_clear(&tmp);
}
bls12_Fp12_frobenius_map_p10()
void bls12_Fp12_frobenius_map_p10 (Fp12 * ANS, Fp12 * A)
Calculate Frobenius map of A in Fp12 extension field as A^p^10 where p is the BLS12 prime.
Parameters
out ANS - the result.
in A - the input vecotr.
References d12_frobenius_constant, f_p10, Fp2_mul_mpz(), Fp2_set(), Fp2_set_neg(), Fp6::x0, Fp12::x0, Fp6::x1, Fp12::x1, and Fp6::x2.
                                                    {
    //x0
    Fp2_set(&ANS->x0.x0,&A->x0.x0);
    Fp2_mul_mpz(&ANS->x0.x1,&A->x0.x1,d12_frobenius_constant[
      f_p10][1].x0.x0);
    Fp2_mul_mpz(&ANS->x0.x2,&A->x0.x2,d12_frobenius_constant[
      f_p10][2].x0.x0);
    //x1
    Fp2_mul_mpz(&ANS->x1.x0,&A->x1.x0,d12_frobenius_constant[
      f_p10][3].x0.x0);
    Fp2_set_neg(&ANS->x1.x1,&A->x1.x1);
    Fp2_mul_mpz(&ANS->x1.x2,&A->x1.x2,d12_frobenius_constant[
      f_p10][5].x0.x0);
}
bls12_Fp12_frobenius_map_p2()
void bls12_Fp12_frobenius_map_p2 (Fp12 * ANS, Fp12 * A)
Calculate Frobenius map of A in Fp12 extension field as A^p^2 where p is the BLS12 prime.
Parameters
out ANS - the result.
in A - the input vecotr.
References d12_frobenius_constant, f_p2, Fp2_mul_mpz(), Fp2_set(), Fp2_set_neg(), Fp6::x0, Fp12::x0, Fp6::x1, Fp12::x1, and Fp6::x2.
Referenced by bls12_2split_G3_exp(), bls12_4split_G3_exp(), bls12_finalexp_optimal(), and bls12_finalexp_plain().
                                                   {
    //x0
    Fp2_set(&ANS->x0.x0,&A->x0.x0);
    Fp2_mul_mpz(&ANS->x0.x1,&A->x0.x1,d12_frobenius_constant[
      f_p2][1].x0.x0);
    Fp2_mul_mpz(&ANS->x0.x2,&A->x0.x2,d12_frobenius_constant[
      f_p2][2].x0.x0);
    //x1
    Fp2_mul_mpz(&ANS->x1.x0,&A->x1.x0,d12_frobenius_constant[
      f_p2][3].x0.x0);
    Fp2_set_neg(&ANS->x1.x1,&A->x1.x1);
    Fp2_mul_mpz(&ANS->x1.x2,&A->x1.x2,d12_frobenius_constant[
      f_p2][5].x0.x0);
}
bls12_Fp12_frobenius_map_p3()
void bls12_Fp12_frobenius_map_p3 (Fp12 * ANS, Fp12 * A)
Calculate Frobenius map of A in Fp12 extension field as A^p^3 where p is the BLS12 prime.
Parameters
out ANS - the result.
in A - the input vecotr.
References d12_frobenius_constant, f_p3, Fp2_mul(), Fp_clear(), Fp_init(), Fp_set(), Fp_set_neg(), Fp6::x0, Fp12::x0, Fp2::x1, Fp6::x1, Fp12::x1, and Fp6::x2.
Referenced by bls12_4split_G3_exp(), and bls12_finalexp_optimal().
                                                   {
    Fp tmp;
    Fp_init(&tmp);
    
    //x0
    Fp_set(&ANS->x0.x0.x0,&A->x0.x0.x0);
    Fp_set_neg(&ANS->x0.x0.x1,&A->x0.x0.x1);
    Fp_set(&tmp,&A->x0.x1.x0);
    Fp_set(&ANS->x0.x1.x0,&A->x0.x1.x1);
    Fp_set(&ANS->x0.x1.x1,&tmp);
    Fp_set_neg(&ANS->x0.x2.x0,&A->x0.x2.x0);
    Fp_set(&ANS->x0.x2.x1,&A->x0.x2.x1);
    //x1
    Fp_set(&ANS->x1.x0.x0,&A->x1.x0.x0);
    Fp_set_neg(&ANS->x1.x0.x1,&A->x1.x0.x1);
    Fp2_mul(&ANS->x1.x0,&ANS->x1.x0,&d12_frobenius_constant[
      f_p3][3]);
    Fp_set(&ANS->x1.x1.x0,&A->x1.x1.x0);
    Fp_set_neg(&ANS->x1.x1.x1,&A->x1.x1.x1);
    Fp2_mul(&ANS->x1.x1,&ANS->x1.x1,&d12_frobenius_constant[
      f_p3][4]);
    Fp_set(&ANS->x1.x2.x0,&A->x1.x2.x0);
    Fp_set_neg(&ANS->x1.x2.x1,&A->x1.x2.x1);
    Fp2_mul(&ANS->x1.x2,&ANS->x1.x2,&d12_frobenius_constant[
      f_p3][5]);
    
    Fp_clear(&tmp);
}
bls12_Fp12_frobenius_map_p4()
void bls12_Fp12_frobenius_map_p4 (Fp12 * ANS, Fp12 * A)
Calculate Frobenius map of A in Fp12 extension field as A^p^4 where p is the BLS12 prime.
Parameters
out ANS - the result.
in A - the input vecotr.
References d12_frobenius_constant, f_p4, Fp2_mul_mpz(), Fp2_set(), Fp6::x0, Fp12::x0, Fp6::x1, Fp12::x1, and Fp6::x2.
                                                   {
    //x0
    Fp2_set(&ANS->x0.x0,&A->x0.x0);
    Fp2_mul_mpz(&ANS->x0.x1,&A->x0.x1,d12_frobenius_constant[
      f_p4][1].x0.x0);
    Fp2_mul_mpz(&ANS->x0.x2,&A->x0.x2,d12_frobenius_constant[
      f_p4][2].x0.x0);
    //x1
    Fp2_mul_mpz(&ANS->x1.x0,&A->x1.x0,d12_frobenius_constant[
      f_p4][3].x0.x0);
    Fp2_set(&ANS->x1.x1,&A->x1.x1);
    Fp2_mul_mpz(&ANS->x1.x2,&A->x1.x2,d12_frobenius_constant[
      f_p4][5].x0.x0);
}
bls12_Fp12_frobenius_map_p6()
void bls12_Fp12_frobenius_map_p6 (Fp12 * ANS, Fp12 * A)
Calculate Frobenius map of A in Fp12 extension field as A^p^6 where p is the BLS12 prime.
Parameters
out ANS - the result.
in A - the input vecotr.
References Fp6_set(), Fp6_set_neg(), Fp12::x0, and Fp12::x1.
Referenced by bls12_finalexp_optimal(), bls12_finalexp_plain(), and bls12_Fp12_pow_motherparam().
                                                   {
    //x0
    Fp6_set(&ANS->x0,&A->x0);
    //x1
    Fp6_set_neg(&ANS->x1,&A->x1);
}
bls12_Fp12_frobenius_map_p8()
void bls12_Fp12_frobenius_map_p8 (Fp12 * ANS, Fp12 * A)
Calculate Frobenius map of A in Fp12 extension field as A^p^8 where p is the BLS12 prime.
Parameters
out ANS - the result.
in A - the input vecotr.
References d12_frobenius_constant, f_p8, Fp2_mul_mpz(), Fp2_set(), Fp6::x0, Fp12::x0, Fp6::x1, Fp12::x1, and Fp6::x2.
                                                   {
    //x0
    Fp2_set(&ANS->x0.x0,&A->x0.x0);
    Fp2_mul_mpz(&ANS->x0.x1,&A->x0.x1,d12_frobenius_constant[
      f_p8][1].x0.x0);
    Fp2_mul_mpz(&ANS->x0.x2,&A->x0.x2,d12_frobenius_constant[
      f_p8][2].x0.x0);
    //x1
    Fp2_mul_mpz(&ANS->x1.x0,&A->x1.x0,d12_frobenius_constant[
      f_p8][3].x0.x0);
    Fp2_set(&ANS->x1.x1,&A->x1.x1);
    Fp2_mul_mpz(&ANS->x1.x2,&A->x1.x2,d12_frobenius_constant[
      f_p8][5].x0.x0);
}