src/bn_inits.c File Reference
#include <ELiPS_bn_bls/bn_inits.h>
Functions
void init_bn (void)
Function Documentation
init_bn()
void init_bn (void)
This methods needs to be called before using the BN curve for pairing. It initialized the curve as y^2=x^3-4 with parameters suggested in https://eprint.iacr.org/2017/334.
References init_bn_settings(), and init_precoms().
Referenced by main().
                  {
    init_bn_settings();
    init_precoms(1);
}