src/bn_twist.c File Reference
#include <ELiPS_bn_bls/bn_twist.h>
Functions
void EFp12_to_EFp2 (EFp2 *ANS, EFp12 *P)
void EFp2_to_EFp12 (EFp12 *ANS, EFp2 *P)
Function Documentation
EFp12_to_EFp2()
void EFp12_to_EFp2 (EFp2 * ANS, EFp12 * P)
References Fp2_mul_basis(), Fp2_set(), Fp2_set_ui(), EFp2::infinity, EFp12::infinity, EFp2::x, EFp12::x, Fp12::x0, Fp6::x1, Fp12::x1, Fp6::x2, EFp2::y, and EFp12::y.
Referenced by Miller_algo_for_opt_ate(), Miller_algo_for_plain_ate(), and Miller_algo_for_x_ate().
                                      {
    Fp2_set_ui(&ANS->x,0);
    Fp2_set(&ANS->x,&P->x.x0.x2);
    Fp2_mul_basis(&ANS->x,&ANS->x);
    Fp2_set_ui(&ANS->y,0);
    Fp2_set(&ANS->y,&P->y.x1.x1);
    Fp2_mul_basis(&ANS->y,&ANS->y);
    ANS->infinity=P->infinity;
}
EFp2_to_EFp12()
void EFp2_to_EFp12 (EFp12 * ANS, EFp2 * P)
References Fp12_set_ui(), Fp2_inv_basis(), Fp2_set(), EFp2::infinity, EFp12::infinity, EFp2::x, EFp12::x, Fp12::x0, Fp6::x1, Fp12::x1, Fp6::x2, EFp2::y, and EFp12::y.
                                      {
    Fp12_set_ui(&ANS->x,0);
    Fp2_set(&ANS->x.x0.x2,&P->x);
    Fp2_inv_basis(&ANS->x.x0.x2,&ANS->x.x0.x2);
    Fp12_set_ui(&ANS->y,0);
    Fp2_set(&ANS->y.x1.x1,&P->y);
    Fp2_inv_basis(&ANS->y.x1.x1,&ANS->y.x1.x1);
    ANS->infinity=P->infinity;
}