include/ELiPS_bn_bls/bn_pairings.h File Reference
#include <ELiPS_bn_bls/bn_miller_ate.h>
#include <ELiPS_bn_bls/bn_miller_tate.h>
#include <ELiPS_bn_bls/bn_miller_xate.h>
#include <ELiPS_bn_bls/bn_miller_optate.h>
#include <ELiPS_bn_bls/bn_final_exp.h>
#include <ELiPS_bn_bls/bn_utils.h>
Functions
void bn12_tate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
void bn12_plain_ate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
void bn12_opt_ate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
void bn12_x_ate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
Function Documentation
bn12_opt_ate()
void bn12_opt_ate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
References Final_exp_optimal(), FINALEXP_OPT, Miller_algo_for_opt_ate(), MILLER_OPTATE, t1, and timedifference_msec().
Referenced by bn12_test_opt_ate_pairing().
                                               {
    //miller
    gettimeofday(&t0,NULL);
    Miller_algo_for_opt_ate(ANS,P,Q);
    gettimeofday(&t1,NULL);
    MILLER_OPTATE=timedifference_msec(t0,t1);
    
    //final exp
    gettimeofday(&t0,NULL);
    Final_exp_optimal(ANS,ANS);
    gettimeofday(&t1,NULL);
    FINALEXP_OPT=timedifference_msec(t0,t1);
}
bn12_plain_ate()
void bn12_plain_ate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
References Final_exp_optimal(), FINALEXP_OPT, Miller_algo_for_plain_ate(), MILLER_PLAINATE, t1, and timedifference_msec().
Referenced by bn12_test_plain_ate_pairing().
                                                {
    //miller
    gettimeofday(&t0,NULL);
    Miller_algo_for_plain_ate(ANS,P,Q);
    gettimeofday(&t1,NULL);
    MILLER_PLAINATE=timedifference_msec(t0,t1);
    
    //final exp
    gettimeofday(&t0,NULL);
    Final_exp_optimal(ANS,ANS);
    gettimeofday(&t1,NULL);
    FINALEXP_OPT=timedifference_msec(t0,t1);
}
bn12_tate()
void bn12_tate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
References Final_exp_optimal(), FINALEXP_OPT, Miller_algo_for_tate(), MILLER_TATE, t1, and timedifference_msec().
Referenced by bn12_test_tate_pairing().
                                            {
    //miller
    gettimeofday(&t0,NULL);
    Miller_algo_for_tate(ANS,P,Q);
    gettimeofday(&t1,NULL);
    MILLER_TATE=timedifference_msec(t0,t1);
    
    //final exp
    gettimeofday(&t0,NULL);
    Final_exp_optimal(ANS,ANS);
    gettimeofday(&t1,NULL);
    FINALEXP_OPT=timedifference_msec(t0,t1);
}
bn12_x_ate()
void bn12_x_ate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
References Final_exp_optimal(), FINALEXP_OPT, Miller_algo_for_x_ate(), MILLER_XATE, t1, and timedifference_msec().
Referenced by bn12_test_x_ate_pairing().
                                             {
    //miller
    gettimeofday(&t0,NULL);
    Miller_algo_for_x_ate(ANS,P,Q);
    gettimeofday(&t1,NULL);
    MILLER_XATE=timedifference_msec(t0,t1);
    
    //final exp
    gettimeofday(&t0,NULL);
    Final_exp_optimal(ANS,ANS);
    gettimeofday(&t1,NULL);
    FINALEXP_OPT=timedifference_msec(t0,t1);
}