include/ELiPS_bn_bls/bn_skew_frobenius.h File Reference
#include <ELiPS_bn_bls/bn_bls12_precoms.h>
#include <ELiPS_bn_bls/bn_efp12.h>
Functions
void EFp_skew_frobenius_map_p2 (EFp *ANS, EFp *A)
void EFp2_skew_frobenius_map_p1 (EFp2 *ANS, EFp2 *A)
void EFp2_skew_frobenius_map_p2 (EFp2 *ANS, EFp2 *A)
void EFp2_skew_frobenius_map_p3 (EFp2 *ANS, EFp2 *A)
void EFp2_skew_frobenius_map_p10 (EFp2 *ANS, EFp2 *A)
Function Documentation
EFp2_skew_frobenius_map_p1()
void EFp2_skew_frobenius_map_p1 (EFp2 * ANS, EFp2 * A)
References d12_skew_frobenius_constant, f_p1, Fp2_mul(), Fp_set(), Fp_set_neg(), EFp2::x, Fp2::x1, and EFp2::y.
Referenced by Miller_algo_for_opt_ate().
                                                  {
    //x
    Fp_set(&ANS->x.x0,&A->x.x0);
    Fp_set_neg(&ANS->x.x1,&A->x.x1);
    Fp2_mul(&ANS->x,&ANS->x,&d12_skew_frobenius_constant[
      f_p1][0]);
    //y
    Fp_set(&ANS->y.x0,&A->y.x0);
    Fp_set_neg(&ANS->y.x1,&A->y.x1);
    Fp2_mul(&ANS->y,&ANS->y,&d12_skew_frobenius_constant[
      f_p1][1]);
}
EFp2_skew_frobenius_map_p10()
void EFp2_skew_frobenius_map_p10 (EFp2 * ANS, EFp2 * A)
References d12_skew_frobenius_constant, f_p10, Fp2_mul(), EFp2::x, and EFp2::y.
Referenced by Miller_algo_for_x_ate().
                                                   {
    //x
    Fp2_mul(&ANS->x,&A->x,&d12_skew_frobenius_constant[
      f_p10][0]);
    //y
    Fp2_mul(&ANS->y,&A->y,&d12_skew_frobenius_constant[
      f_p10][1]);
}
EFp2_skew_frobenius_map_p2()
void EFp2_skew_frobenius_map_p2 (EFp2 * ANS, EFp2 * A)
References d12_skew_frobenius_constant, f_p2, Fp2_mul(), EFp2::x, and EFp2::y.
Referenced by Miller_algo_for_opt_ate().
                                                  {
    //x
    Fp2_mul(&ANS->x,&A->x,&d12_skew_frobenius_constant[
      f_p2][0]);
    //y
    Fp2_mul(&ANS->y,&A->y,&d12_skew_frobenius_constant[
      f_p2][1]);
}
EFp2_skew_frobenius_map_p3()
void EFp2_skew_frobenius_map_p3 (EFp2 * ANS, EFp2 * A)
References d12_skew_frobenius_constant, f_p3, Fp2_mul(), Fp_set(), Fp_set_neg(), EFp2::x, Fp2::x1, and EFp2::y.
Referenced by Miller_algo_for_x_ate().
                                                  {
    //x
    Fp_set(&ANS->x.x0,&A->x.x0);
    Fp_set_neg(&ANS->x.x1,&A->x.x1);
    Fp2_mul(&ANS->x,&ANS->x,&d12_skew_frobenius_constant[
      f_p3][0]);
    //y
    Fp_set(&ANS->y.x0,&A->y.x0);
    Fp_set_neg(&ANS->y.x1,&A->y.x1);
    Fp2_mul(&ANS->y,&ANS->y,&d12_skew_frobenius_constant[
      f_p3][1]);
}
EFp_skew_frobenius_map_p2()
void EFp_skew_frobenius_map_p2 (EFp * ANS, EFp * A)
References epsilon1, Fp_mul_mpz(), Fp_set_neg(), EFp::x, and EFp::y.
                                               {
    Fp_mul_mpz(&ANS->x,&A->x,epsilon1);
    Fp_set_neg(&ANS->y,&A->y);
}