src/bn_miller_tate.c File Reference
#include <ELiPS_bn_bls/bn_miller_tate.h>
Functions
void Miller_algo_for_tate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
Function Documentation
Miller_algo_for_tate()
void Miller_algo_for_tate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
References curve_parameters, EFp_clear(), EFp_init(), EFp_set(), f_ltp_vtp_for_tate(), ff_ltt_vtt_for_tate(), Fp12_clear(), Fp12_init(), Fp12_set(), Fp12_set_ui(), Fp_set(), Fp_set_ui(), EFp::infinity, EFp12::infinity, curve_params::order, EFp::x, EFp12::x, Fp6::x0, Fp12::x0, EFp::y, and EFp12::y.
Referenced by bn12_tate().
                                                      {
    EFp Tmp_P,T;
    EFp_init(&Tmp_P);
    EFp_init(&T);
    Fp12 f;
    Fp12_init(&f);
    int i,length;
    length=(int)mpz_sizeinbase(curve_parameters.order,2);
    char binary[length];
    mpz_get_str(binary,2,curve_parameters.order);
    
    //set
    Fp_set(&Tmp_P.x,&P->x.x0.x0.x0);
    Fp_set(&Tmp_P.y,&P->y.x0.x0.x0);
    Tmp_P.infinity=P->infinity;
    EFp_set(&T,&Tmp_P);
    Fp12_set_ui(&f,0);
    Fp_set_ui(&f.x0.x0.x0,1);
    
    //miller
    for(i=1; i<length; i++){
        ff_ltt_vtt_for_tate(&f,&T,Q);
        if(binary[i]=='1'){
            f_ltp_vtp_for_tate(&f,&T,&Tmp_P,Q);
        }
    }
    Fp12_set(ANS,&f);
    
    Fp12_clear(&f);
    EFp_clear(&T);
    EFp_clear(&Tmp_P);
}