include/ELiPS_bn_bls/bn_fp2.h File Reference
#include <ELiPS_bn_bls/bn_fp.h>
#include <ELiPS_bn_bls/field_dtype.h>
#include <ELiPS_bn_bls/bn_bls12_precoms.h>
Functions
void Fp2_init (Fp2 *A)
void Fp2_clear (Fp2 *A)
void Fp2_printf (Fp2 *A, char *str)
void Fp2_set (Fp2 *ANS, Fp2 *A)
void Fp2_set_ui (Fp2 *ANS, unsigned long int UI)
void Fp2_set_mpz (Fp2 *ANS, mpz_t A)
void Fp2_set_neg (Fp2 *ANS, Fp2 *A)
void Fp2_set_random (Fp2 *ANS, gmp_randstate_t state)
void Fp2_mul (Fp2 *ANS, Fp2 *A, Fp2 *B)
void Fp2_mul_ui (Fp2 *ANS, Fp2 *A, unsigned long int UI)
void Fp2_mul_mpz (Fp2 *ANS, Fp2 *A, mpz_t B)
void Fp2_mul_Fp (Fp2 *ANS, Fp2 *A, Fp *B)
void Fp2_mul_basis (Fp2 *ANS, Fp2 *A)
void Fp2_inv_basis (Fp2 *ANS, Fp2 *A)
void Fp2_sqr (Fp2 *ANS, Fp2 *A)
void Fp2_add (Fp2 *ANS, Fp2 *A, Fp2 *B)
void Fp2_add_ui (Fp2 *ANS, Fp2 *A, unsigned long int UI)
void Fp2_add_mpz (Fp2 *ANS, Fp2 *A, mpz_t B)
void Fp2_sub (Fp2 *ANS, Fp2 *A, Fp2 *B)
void Fp2_sub_ui (Fp2 *ANS, Fp2 *A, unsigned long int UI)
void Fp2_sub_mpz (Fp2 *ANS, Fp2 *A, mpz_t B)
void Fp2_inv (Fp2 *ANS, Fp2 *A)
int Fp2_legendre (Fp2 *A)
int Fp2_isCNR (Fp2 *A)
void Fp2_sqrt (Fp2 *ANS, Fp2 *A)
void Fp2_pow (Fp2 *ANS, Fp2 *A, mpz_t scalar)
int Fp2_cmp (Fp2 *A, Fp2 *B)
int Fp2_cmp_ui (Fp2 *A, unsigned long int UI)
int Fp2_cmp_mpz (Fp2 *A, mpz_t B)
int Fp2_cmp_zero (Fp2 *A)
int Fp2_cmp_one (Fp2 *A)
void Fp2_neg (Fp2 *ans, Fp2 *a)
void Fp2_mul_KSS16 (Fp2 *ANS, Fp2 *A, Fp2 *B)
void Fp2_mul_basis_KSS16 (Fp2 *ANS, Fp2 *A)
void Fp2_invert_kss16 (Fp2 *ANS, Fp2 *A)
Function Documentation
Fp2_add()
void Fp2_add (Fp2 * ANS, Fp2 * A, Fp2 * B)
References Fp_add(), and Fp2::x1.
Referenced by bls12_f_ltq(), bls12_ff_ltt(), bls12_Pseudo_8_sparse_mul(), f_ltq(), ff_ltt(), Fp4_add(), Fp4_mul(), Fp4_sqr(), Fp6_add(), Fp6_mul(), Fp6_sqr(), and Pseudo_8_sparse_mul().
                                    {
    Fp_add(&ANS->x0,&A->x0,&B->x0);
    Fp_add(&ANS->x1,&A->x1,&B->x1);
}
Fp2_add_mpz()
void Fp2_add_mpz (Fp2 * ANS, Fp2 * A, mpz_t B)
References Fp_add_mpz(), and Fp2::x1.
Referenced by Fp6_add_mpz().
                                         {
    Fp_add_mpz(&ANS->x0,&A->x0,B);
    Fp_add_mpz(&ANS->x1,&A->x1,B);
}
Fp2_add_ui()
void Fp2_add_ui (Fp2 * ANS, Fp2 * A, unsigned long int UI)
References Fp_add_ui(), and Fp2::x1.
Referenced by Fp4_add_ui(), and Fp6_add_ui().
                                                     {
    Fp_add_ui(&ANS->x0,&A->x0,UI);
    Fp_add_ui(&ANS->x1,&A->x1,UI);
}
Fp2_clear()
void Fp2_clear (Fp2 * A)
References Fp_clear(), and Fp2::x1.
Referenced by bls12_f_ltq(), bls12_ff_ltt(), bls12_Pseudo_8_sparse_mul(), clear_parameters(), EFp2_clear(), EFp2_ECA(), EFp2_ECD(), EFp2_rational_point(), f_ltq(), ff_ltt(), Fp2_inv(), Fp2_inv_basis(), Fp2_invert_kss16(), Fp2_isCNR(), Fp2_legendre(), Fp2_pow(), Fp2_sqrt(), Fp4_clear(), Fp4_mul(), Fp4_sqr(), Fp6_clear(), Fp6_mul(), Fp6_sqr(), Pseudo_8_sparse_mul(), and set_frobenius_constant().
                      {
    Fp_clear(&A->x0);
    Fp_clear(&A->x1);
}
Fp2_cmp()
int Fp2_cmp (Fp2 * A, Fp2 * B)
References Fp_cmp(), and Fp2::x1.
Referenced by EFp2_ECA(), Fp4_cmp(), and Fp6_cmp().
                           {
    if(Fp_cmp(&A->x0,&B->x0)==0 && Fp_cmp(&A->x1,&B->x1)==0){
        return 0;
    }
    return 1;
}
Fp2_cmp_mpz()
int Fp2_cmp_mpz (Fp2 * A, mpz_t B)
References Fp_cmp_mpz(), and Fp2::x1.
Referenced by Fp4_cmp_mpz(), and Fp6_cmp_mpz().
                                {
    if(Fp_cmp_mpz(&A->x0,B)==0 && Fp_cmp_mpz(&A->x1,B)==0){
        return 0;
    }
    return 1;
}
Fp2_cmp_one()
int Fp2_cmp_one (Fp2 * A)
References Fp_cmp_one(), Fp_cmp_zero(), and Fp2::x1.
Referenced by Fp2_isCNR(), Fp2_legendre(), Fp2_sqrt(), and Fp6_cmp_one().
                        {
    if(Fp_cmp_one(&A->x0)==0 && Fp_cmp_zero(&A->x1)==0){
        return 0;
    }
    return 1;
}
Fp2_cmp_ui()
int Fp2_cmp_ui (Fp2 * A, unsigned long int UI)
References Fp_cmp_ui(), and Fp2::x1.
Referenced by Fp6_cmp_ui().
                                            {
    if(Fp_cmp_ui(&A->x0,UI)==0 && Fp_cmp_ui(&A->x1,UI)==0){
        return 0;
    }
    return 1;
}
Fp2_cmp_zero()
int Fp2_cmp_zero (Fp2 * A)
References Fp_cmp_zero(), and Fp2::x1.
Referenced by EFp2_ECD(), Fp6_cmp_one(), and Fp6_cmp_zero().
                         {
    if(Fp_cmp_zero(&A->x0)==0 && Fp_cmp_zero(&A->x1)==0){
        return 0;
    }
    return 1;
}
Fp2_init()
void Fp2_init (Fp2 * A)
References Fp_init(), and Fp2::x1.
Referenced by bls12_f_ltq(), bls12_ff_ltt(), bls12_Pseudo_8_sparse_mul(), EFp2_ECA(), EFp2_ECD(), EFp2_init(), EFp2_rational_point(), f_ltq(), ff_ltt(), Fp2_inv(), Fp2_inv_basis(), Fp2_invert_kss16(), Fp2_isCNR(), Fp2_legendre(), Fp2_pow(), Fp2_sqrt(), Fp4_init(), Fp4_mul(), Fp4_sqr(), Fp6_init(), Fp6_mul(), Fp6_sqr(), init_precoms(), Pseudo_8_sparse_mul(), and set_frobenius_constant().
                     {
    Fp_init(&A->x0);
    Fp_init(&A->x1);
}
Fp2_inv()
void Fp2_inv (Fp2 * ANS, Fp2 * A)
References Fp2_clear(), Fp2_init(), Fp2_mul(), Fp2_mul_mpz(), Fp_inv(), Fp_set(), Fp_set_neg(), and Fp2::x1.
Referenced by bls12_f_ltq(), bls12_ff_ltt(), EFp2_ECA(), EFp2_ECD(), f_ltq(), ff_ltt(), Fp6_inv(), Fp6_sqrt(), set_basis(), and set_frobenius_constant().
                             {
    Fp2 frob,tmp;
    Fp2_init(&frob);
    Fp2_init(&tmp);
    
    Fp_set(&frob.x0,&A->x0);
    Fp_set_neg(&frob.x1,&A->x1);
    
    Fp2_mul(&tmp,A,&frob);
    Fp_inv(&tmp.x0,&tmp.x0);
    Fp2_mul_mpz(ANS,&frob,tmp.x0.x0);
    
    Fp2_clear(&frob);
    Fp2_clear(&tmp);
}
Fp2_inv_basis()
void Fp2_inv_basis (Fp2 * ANS, Fp2 * A)
References Fp2_basis_inv, Fp2_clear(), Fp2_init(), Fp2_set(), Fp_add(), Fp_mul_mpz(), Fp_sub(), and Fp2::x1.
Referenced by bls12_EFp2_to_EFp12(), bls12_f_ltq(), bls12_ff_ltt(), EFp2_to_EFp12(), f_ltq(), and ff_ltt().
                                   {
    //Fp2_mul(ANS,A,&Fp2_basis_inv);
    Fp2 tmp;
    Fp2_init(&tmp);
    Fp2_set(&tmp,A);
    //TODO
    Fp_add(&ANS->x0,&tmp.x0,&tmp.x1);
    Fp_mul_mpz(&ANS->x0,&ANS->x0,Fp2_basis_inv.x0.x0);
    Fp_sub(&ANS->x1,&tmp.x1,&tmp.x0);
    Fp_mul_mpz(&ANS->x1,&ANS->x1,Fp2_basis_inv.x0.x0);
    
    Fp2_clear(&tmp);
}
Fp2_invert_kss16()
void Fp2_invert_kss16 (Fp2 * ANS, Fp2 * A)
References curve_parameters, Fp2_clear(), Fp2_init(), Fp2_mul_KSS16(), Fp2_mul_mpz(), Fp_neg(), Fp_set(), curve_params::prime, and Fp2::x1.
Referenced by Fp4_invert().
                                      {
    struct Fp2 frob,buf;
    Fp2_init(&frob);
    Fp2_init(&buf);
    
    Fp_set(&frob.x0,&A->x0);
    Fp_neg(&frob.x1,&A->x1);
    Fp2_mul_KSS16(&buf,A,&frob);
    mpz_invert(buf.x0.x0,buf.x0.x0,curve_parameters.prime);
    Fp2_mul_mpz(ANS,&frob,buf.x0.x0);
    
    Fp2_clear(&frob);
    Fp2_clear(&buf);
}
Fp2_isCNR()
int Fp2_isCNR (Fp2 * A)
References curve_parameters, Fp2_clear(), Fp2_cmp_one(), Fp2_init(), Fp2_pow(), and curve_params::prime.
                      {
    Fp2 tmp;
    Fp2_init(&tmp);
    mpz_t exp;
    mpz_init(exp);
    
    mpz_pow_ui(exp,curve_parameters.prime,2);
    mpz_sub_ui(exp,exp,1);
    mpz_tdiv_q_ui(exp,exp,3);
    Fp2_pow(&tmp,A,exp);
    
    if(Fp2_cmp_one(&tmp)==0){
        mpz_clear(exp);
        Fp2_clear(&tmp);
        return 1;
    }else{
        mpz_clear(exp);
        Fp2_clear(&tmp);
        return -1;
    }
    
}
Fp2_legendre()
int Fp2_legendre (Fp2 * A)
References curve_parameters, Fp2_clear(), Fp2_cmp_one(), Fp2_init(), Fp2_pow(), and curve_params::prime.
Referenced by EFp2_rational_point(), and Fp2_sqrt().
                         {
    Fp2 tmp;
    Fp2_init(&tmp);
    
    mpz_t exp;
    mpz_init(exp);
    mpz_pow_ui(exp,curve_parameters.prime,2);
    mpz_sub_ui(exp,exp,1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp,A,exp);
    
    if(Fp2_cmp_one(&tmp)==0){
        mpz_clear(exp);
        Fp2_clear(&tmp);
        return 1;
    }else{
        mpz_clear(exp);
        Fp2_clear(&tmp);
        return -1;
    }
}
Fp2_mul()
void Fp2_mul (Fp2 * ANS, Fp2 * A, Fp2 * B)
References Fp_add(), Fp_clear(), Fp_init(), Fp_mul(), Fp_mul_basis(), Fp_sub(), and Fp2::x1.
Referenced by bls12_EFp2_skew_frobenius_map_p1(), bls12_EFp2_skew_frobenius_map_p10(), bls12_EFp2_skew_frobenius_map_p2(), bls12_EFp2_skew_frobenius_map_p3(), bls12_f_ltq(), bls12_ff_ltt(), bls12_Fp12_frobenius_map_p1(), bls12_Fp12_frobenius_map_p3(), bls12_Pseudo_8_sparse_mul(), EFp2_ECA(), EFp2_ECD(), EFp2_rational_point(), EFp2_skew_frobenius_map_p1(), EFp2_skew_frobenius_map_p10(), EFp2_skew_frobenius_map_p2(), EFp2_skew_frobenius_map_p3(), f_ltq(), ff_ltt(), Fp12_frobenius_map_p1(), Fp12_frobenius_map_p3(), Fp2_inv(), Fp2_pow(), Fp2_sqrt(), Fp4_invert(), Fp4_mul(), Fp4_sqr(), Fp6_inv(), Fp6_mul(), Fp6_sqr(), Pseudo_8_sparse_mul(), and set_frobenius_constant().
                                    {
    Fp tmp1,tmp2,tmp3,tmp4;
    Fp_init(&tmp1);
    Fp_init(&tmp2);
    Fp_init(&tmp3);
    Fp_init(&tmp4);
    
    //set
    Fp_mul(&tmp1,&A->x0,&B->x0);//a*c
    Fp_mul(&tmp2,&A->x1,&B->x1);//b*d
    Fp_add(&tmp3,&A->x0,&A->x1);//a+b
    Fp_add(&tmp4,&B->x0,&B->x1);//c+d
    //x0
    Fp_mul_basis(&ANS->x0,&tmp2);//b*d*v
    Fp_add(&ANS->x0,&ANS->x0,&tmp1);//a*c+b*d*v
    //x1
    Fp_mul(&ANS->x1,&tmp3,&tmp4);//(a+b)(c+d)
    Fp_sub(&ANS->x1,&ANS->x1,&tmp1);
    Fp_sub(&ANS->x1,&ANS->x1,&tmp2);
    
    //clear
    Fp_clear(&tmp1);
    Fp_clear(&tmp2);
    Fp_clear(&tmp3);
    Fp_clear(&tmp4);
}
Fp2_mul_basis()
void Fp2_mul_basis (Fp2 * ANS, Fp2 * A)
References Fp_add(), Fp_clear(), Fp_init(), Fp_set(), Fp_sub(), and Fp2::x1.
Referenced by bls12_EFp12_to_EFp2(), bls12_Pseudo_8_sparse_mul(), EFp12_to_EFp2(), Fp6_mul(), Fp6_sqr(), and Pseudo_8_sparse_mul().
                                   {
    Fp tmp;
    Fp_init(&tmp);
    Fp_set(&tmp,&A->x0);
    
    Fp_sub(&ANS->x0,&tmp,&A->x1);
    Fp_add(&ANS->x1,&tmp,&A->x1);
    
    Fp_clear(&tmp);
}
Fp2_mul_basis_KSS16()
void Fp2_mul_basis_KSS16 (Fp2 * ANS, Fp2 * A)
References Fp_mul_basis_KSS16(), Fp_set(), and Fp2::x1.
Referenced by Fp4_mul(), and Fp4_sqr().
                                          {
    Fp_mul_basis_KSS16(&ANS->x0,&A->x1);
    Fp_set(&ANS->x1,&A->x0);
}
Fp2_mul_Fp()
void Fp2_mul_Fp (Fp2 * ANS, Fp2 * A, Fp * B)
References Fp_mul(), and Fp2::x1.
Referenced by Fp4_mul_Fp().
                                                           {
    Fp_mul(&ANS->x0,&ANS->x0,B);
    Fp_mul(&ANS->x1,&ANS->x1,B);
}
Fp2_mul_KSS16()
void Fp2_mul_KSS16 (Fp2 * ANS, Fp2 * A, Fp2 * B)
References Fp_add(), Fp_clear(), Fp_init(), Fp_mul(), Fp_mul_basis_KSS16(), Fp_sub(), and Fp2::x1.
Referenced by Fp2_invert_kss16().
                                          {
    struct Fp tmp1,tmp2;
    Fp_init(&tmp1);
    Fp_init(&tmp2);
    
    //set
    Fp_mul(&tmp2,&A->x1,&B->x1);//b*d
    Fp_add(&tmp1,&A->x0,&A->x1);//a+b
    Fp_add(&ANS->x1,&B->x0,&B->x1);//c+d
    Fp_mul(&ANS->x1,&tmp1,&ANS->x1);//(a+b)(c+d)
    Fp_mul(&tmp1,&A->x0,&B->x0);//a*c
    //x0
    Fp_mul_basis_KSS16(&ANS->x0,&tmp2);//b*d*v
    Fp_add(&ANS->x0,&ANS->x0,&tmp1);//a*c+b*d*v
    //x1
    Fp_sub(&ANS->x1,&ANS->x1,&tmp1);
    Fp_sub(&ANS->x1,&ANS->x1,&tmp2);
    
    //clear
    Fp_clear(&tmp1);
    Fp_clear(&tmp2);
}
Fp2_mul_mpz()
void Fp2_mul_mpz (Fp2 * ANS, Fp2 * A, mpz_t B)
References Fp_mul_mpz(), and Fp2::x1.
Referenced by bls12_f_ltq(), bls12_ff_ltt(), bls12_Fp12_frobenius_map_p1(), bls12_Fp12_frobenius_map_p10(), bls12_Fp12_frobenius_map_p2(), bls12_Fp12_frobenius_map_p4(), bls12_Fp12_frobenius_map_p8(), bls12_Pseudo_8_sparse_mapping(), f_ltq(), ff_ltt(), Fp12_frobenius_map_p1(), Fp12_frobenius_map_p10(), Fp12_frobenius_map_p2(), Fp12_frobenius_map_p4(), Fp12_frobenius_map_p8(), Fp2_inv(), Fp2_invert_kss16(), Fp4_mul_mpz(), Fp6_inv(), Fp6_mul_mpz(), and Pseudo_8_sparse_mapping().
                                         {
    Fp_mul_mpz(&ANS->x0,&A->x0,B);
    Fp_mul_mpz(&ANS->x1,&A->x1,B);
}
Fp2_mul_ui()
void Fp2_mul_ui (Fp2 * ANS, Fp2 * A, unsigned long int UI)
References Fp_mul_ui(), and Fp2::x1.
Referenced by bls12_ff_ltt(), EFp2_ECD(), ff_ltt(), Fp4_mul_ui(), and Fp6_mul_ui().
                                                     {
    Fp_mul_ui(&ANS->x0,&A->x0,UI);
    Fp_mul_ui(&ANS->x1,&A->x1,UI);
}
Fp2_neg()
void Fp2_neg (Fp2 * ans, Fp2 * a)
References Fp_neg(), and Fp2::x1.
Referenced by Fp4_invert(), and Fp4_neg().
                             {
    Fp_neg(&ans->x0,&a->x0);
    Fp_neg(&ans->x1,&a->x1);
}
Fp2_pow()
void Fp2_pow (Fp2 * ANS, Fp2 * A, mpz_t scalar)
References Fp2_clear(), Fp2_init(), Fp2_mul(), Fp2_set(), and Fp2_sqr().
Referenced by Fp2_isCNR(), Fp2_legendre(), Fp2_sqrt(), and set_frobenius_constant().
                                          {
    int i,length;
    length=(int)mpz_sizeinbase(scalar,2);
    char binary[length];
    mpz_get_str(binary,2,scalar);
    Fp2 tmp;
    Fp2_init(&tmp);
    Fp2_set(&tmp,A);
    
    for(i=1; i<length; i++){
        Fp2_sqr(&tmp,&tmp);
        if(binary[i]=='1'){
            Fp2_mul(&tmp,A,&tmp);
        }
    }
    
    Fp2_set(ANS,&tmp);
    Fp2_clear(&tmp);
}
Fp2_printf()
void Fp2_printf (Fp2 * A, char * str)
References Fp_printf(), and Fp2::x1.
Referenced by EFp2_printf(), and Fp6_printf().
                                 {
    gmp_printf("%s(",str);
    Fp_printf(&A->x0,"");
    gmp_printf(",");
    Fp_printf(&A->x1,"");
    gmp_printf(")");
}
Fp2_set()
void Fp2_set (Fp2 * ANS, Fp2 * A)
References Fp_set(), and Fp2::x1.
Referenced by bls12_EFp12_to_EFp2(), bls12_EFp2_to_EFp12(), bls12_Fp12_frobenius_map_p10(), bls12_Fp12_frobenius_map_p2(), bls12_Fp12_frobenius_map_p4(), bls12_Fp12_frobenius_map_p8(), EFp12_to_EFp2(), EFp2_set(), EFp2_set_neg(), EFp2_to_EFp12(), Fp12_frobenius_map_p10(), Fp12_frobenius_map_p2(), Fp12_frobenius_map_p4(), Fp12_frobenius_map_p8(), Fp2_inv_basis(), Fp2_pow(), Fp2_sqrt(), Fp4_invert(), Fp4_set(), Fp6_inv(), Fp6_set(), Fp6_sqrt(), and set_frobenius_constant().
                             {
    Fp_set(&ANS->x0,&A->x0);
    Fp_set(&ANS->x1,&A->x1);
}
Fp2_set_mpz()
void Fp2_set_mpz (Fp2 * ANS, mpz_t A)
References Fp_set_mpz(), and Fp2::x1.
Referenced by EFp2_set_mpz(), and Fp6_set_mpz().
                                  {
    Fp_set_mpz(&ANS->x0,A);
    Fp_set_mpz(&ANS->x1,A);
}
Fp2_set_neg()
void Fp2_set_neg (Fp2 * ANS, Fp2 * A)
References Fp_set_neg(), and Fp2::x1.
Referenced by bls12_f_ltq(), bls12_ff_ltt(), bls12_Fp12_frobenius_map_p10(), bls12_Fp12_frobenius_map_p2(), EFp2_set_neg(), f_ltq(), ff_ltt(), Fp12_frobenius_map_p10(), Fp12_frobenius_map_p2(), Fp6_set_neg(), Miller_algo_for_opt_ate(), and Miller_algo_for_x_ate().
                                 {
    Fp_set_neg(&ANS->x0,&A->x0);
    Fp_set_neg(&ANS->x1,&A->x1);
}
Fp2_set_random()
void Fp2_set_random (Fp2 * ANS, gmp_randstate_t state)
References Fp_set_random(), and Fp2::x1.
Referenced by EFp2_rational_point(), Fp2_sqrt(), Fp4_set_random(), and Fp6_set_random().
                                                   {
    Fp_set_random(&ANS->x0,state);
    Fp_set_random(&ANS->x1,state);
}
Fp2_set_ui()
void Fp2_set_ui (Fp2 * ANS, unsigned long int UI)
References Fp_set_ui(), and Fp2::x1.
Referenced by bls12_EFp12_to_EFp2(), EFp12_to_EFp2(), EFp2_set_ui(), Fp4_set_ui(), Fp6_set_ui(), and set_basis().
                                              {
    Fp_set_ui(&ANS->x0,UI);
    Fp_set_ui(&ANS->x1,UI);
}
Fp2_sqr()
void Fp2_sqr (Fp2 * ANS, Fp2 * A)
References Fp_add(), Fp_clear(), Fp_init(), Fp_mul(), Fp_sub(), and Fp2::x1.
Referenced by bls12_f_ltq(), bls12_ff_ltt(), EFp2_ECA(), EFp2_ECD(), EFp2_rational_point(), f_ltq(), ff_ltt(), Fp2_pow(), and Fp6_sqr().
                             {
    Fp tmp1,tmp2;
    Fp_init(&tmp1);
    Fp_init(&tmp2);
    
    Fp_add(&tmp1,&A->x0,&A->x1);
    Fp_sub(&tmp2,&A->x0,&A->x1);
    //x1
    Fp_mul(&ANS->x1,&A->x0,&A->x1);
    Fp_add(&ANS->x1,&ANS->x1,&ANS->x1);
    //x0
    Fp_mul(&ANS->x0,&tmp1,&tmp2);
    
    Fp_clear(&tmp1);
    Fp_clear(&tmp2);
}
Fp2_sqrt()
void Fp2_sqrt (Fp2 * ANS, Fp2 * A)
References curve_parameters, Fp2_clear(), Fp2_cmp_one(), Fp2_init(), Fp2_legendre(), Fp2_mul(), Fp2_pow(), Fp2_set(), Fp2_set_random(), and curve_params::prime.
Referenced by EFp2_rational_point(), and Fp6_sqrt().
                              {
    Fp2 x,y,t,k,n,tmp;
    Fp2_init(&x);
    Fp2_init(&y);
    Fp2_init(&t);
    Fp2_init(&k);
    Fp2_init(&n);
    Fp2_init(&tmp);
    unsigned long int e,m;
    mpz_t exp,q,z,result;
    mpz_init(exp);
    mpz_init(q);
    mpz_init(z);
    mpz_init(result);
    gmp_randstate_t state;
    gmp_randinit_default(state);
    gmp_randseed_ui(state,(unsigned long)time(NULL));
    
    Fp2_set_random(&n,state);
    while(Fp2_legendre(&n)!=-1){
        Fp2_set_random(&n,state);
    }
    mpz_pow_ui(q,curve_parameters.prime,2);
    mpz_sub_ui(q,q,1);
    mpz_mod_ui(result,q,2);
    e=0;
    while(mpz_cmp_ui(result,0)==0){
        mpz_tdiv_q_ui(q,q,2);
        mpz_mod_ui(result,q,2);
        e++;
    }
    Fp2_pow(&y,&n,q);
    mpz_set_ui(z,e);
    mpz_sub_ui(exp,q,1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&x,A,exp);
    Fp2_mul(&tmp,&x,&x);
    Fp2_mul(&k,&tmp,A);
    Fp2_mul(&x,&x,A);
    while(Fp2_cmp_one(&k)!=0){
        m=1;
        mpz_ui_pow_ui(exp,2,m);
        Fp2_pow(&tmp,&k,exp);
        while(Fp2_cmp_one(&tmp)!=0){
            m++;
            mpz_ui_pow_ui(exp,2,m);
            Fp2_pow(&tmp,&k,exp);
        }
        mpz_sub_ui(exp,z,m);
        mpz_sub_ui(exp,exp,1);
        mpz_ui_pow_ui(result,2,mpz_get_ui(exp));
        Fp2_pow(&t,&y,result);
        Fp2_mul(&y,&t,&t);
        mpz_set_ui(z,m);
        Fp2_mul(&x,&x,&t);
        Fp2_mul(&k,&k,&y);
    }
    Fp2_set(ANS,&x);
    
    mpz_clear(exp);
    mpz_clear(q);
    mpz_clear(z);
    mpz_clear(result);
    Fp2_clear(&x);
    Fp2_clear(&y);
    Fp2_clear(&t);
    Fp2_clear(&k);
    Fp2_clear(&n);
    Fp2_clear(&tmp);
}
Fp2_sub()
void Fp2_sub (Fp2 * ANS, Fp2 * A, Fp2 * B)
References Fp_sub(), and Fp2::x1.
Referenced by bls12_f_ltq(), bls12_ff_ltt(), bls12_Pseudo_8_sparse_mul(), EFp2_ECA(), EFp2_ECD(), f_ltq(), ff_ltt(), Fp4_mul(), Fp4_sqr(), Fp4_sub(), Fp6_mul(), Fp6_sqr(), Fp6_sub(), and Pseudo_8_sparse_mul().
                                    {
    Fp_sub(&ANS->x0,&A->x0,&B->x0);
    Fp_sub(&ANS->x1,&A->x1,&B->x1);
}
Fp2_sub_mpz()
void Fp2_sub_mpz (Fp2 * ANS, Fp2 * A, mpz_t B)
References Fp_sub_mpz(), and Fp2::x1.
Referenced by Fp6_sub_mpz().
                                         {
    Fp_sub_mpz(&ANS->x0,&A->x0,B);
    Fp_sub_mpz(&ANS->x1,&A->x1,B);
}
Fp2_sub_ui()
void Fp2_sub_ui (Fp2 * ANS, Fp2 * A, unsigned long int UI)
References Fp_sub_ui(), and Fp2::x1.
Referenced by Fp6_sub_ui().
                                                     {
    Fp_sub_ui(&ANS->x0,&A->x0,UI);
    Fp_sub_ui(&ANS->x1,&A->x1,UI);
}