include/ELiPS_bn_bls/bn_utils.h File Reference
#include <stdio.h>
#include <sys/time.h>
Functions
double timedifference_msec (struct timeval t0, struct timeval t1)
double timedifference_usec (struct timeval t0, struct timeval t1)
void bn12_print_parameters (void)
void bn12_print_G1_point (void)
void bn12_print_G2_point (void)
void bn12_print_tate_time (void)
void bn12_print_plain_ate_time (void)
void bn12_print_opt_ate_time (void)
void bn12_print_x_ate_time (void)
void bn12_print_final_exp_plain_time (void)
void bn12_print_final_exp_optimal_time (void)
void bn12_print_G1_plain_time (void)
void bn12_print_G1_2split_time (void)
void bn12_print_G2_plain_time (void)
void bn12_print_G2_2split_time (void)
void bn12_print_G2_4split_time (void)
void bn12_print_G3_plain_time (void)
void bn12_print_G3_2split_time (void)
void bn12_print_G3_4split_time (void)
Variables
struct timeval t0 t1
double MILLER_TATE
double MILLER_PLAINATE
double MILLER_OPTATE
double MILLER_XATE
double FINALEXP_PLAIN
double FINALEXP_OPT
double G1SCM_PLAIN
double G1SCM_2SPLIT
double G2SCM_PLAIN
double G2SCM_2SPLIT
double G2SCM_4SPLIT
double G3SCM_PLAIN
double G3SCM_2SPLIT
double G3SCM_4SPLIT
Function Documentation
bn12_print_final_exp_optimal_time()
void bn12_print_final_exp_optimal_time (void)
References FINALEXP_OPT.
Referenced by bn12_test_opt_ate_pairing(), bn12_test_plain_ate_pairing(), bn12_test_tate_pairing(), and bn12_test_x_ate_pairing().
                                        {
    printf("optimal-final exp time:%.2f[ms]\n",FINALEXP_OPT);
}
bn12_print_final_exp_plain_time()
void bn12_print_final_exp_plain_time (void)
References FINALEXP_PLAIN.
                                      {
    printf("plain-final exp time:%.2f[ms]\n",FINALEXP_PLAIN);
}
bn12_print_G1_2split_time()
void bn12_print_G1_2split_time (void)
References G1SCM_2SPLIT.
                                {
    printf("2split-G1-SCM time:%.2f[ms]\n",G1SCM_2SPLIT);
}
bn12_print_G1_plain_time()
void bn12_print_G1_plain_time (void)
References G1SCM_PLAIN.
                               {
    printf("plain-G1-SCM time:%.2f[ms]\n",G1SCM_PLAIN);
}
bn12_print_G1_point()
void bn12_print_G1_point (void)
References EFp12_printf(), and G1_P.
                          {
    EFp12_printf(&G1_P,"G1_P\n");
    printf("\n");
}
bn12_print_G2_2split_time()
void bn12_print_G2_2split_time (void)
References G2SCM_2SPLIT.
                                {
    printf("2split-G2-SCM time:%.2f[ms]\n",G2SCM_2SPLIT);
}
bn12_print_G2_4split_time()
void bn12_print_G2_4split_time (void)
References G2SCM_4SPLIT.
                                {
    printf("4split-G2-SCM time:%.2f[ms]\n",G2SCM_4SPLIT);
}
bn12_print_G2_plain_time()
void bn12_print_G2_plain_time (void)
References G2SCM_PLAIN.
                               {
    printf("plain-G2-SCM time:%.2f[ms]\n",G2SCM_PLAIN);
}
bn12_print_G2_point()
void bn12_print_G2_point (void)
References EFp12_printf(), and G2_Q.
                          {
    EFp12_printf(&G2_Q,"G2_Q\n");
    printf("\n");
}
bn12_print_G3_2split_time()
void bn12_print_G3_2split_time (void)
References G3SCM_2SPLIT.
                                {
    printf("2split-G3-SCM time:%.2f[ms]\n",G3SCM_2SPLIT);
}
bn12_print_G3_4split_time()
void bn12_print_G3_4split_time (void)
References G3SCM_4SPLIT.
                                {
    printf("4split-G3-SCM time:%.2f[ms]\n",G3SCM_4SPLIT);
}
bn12_print_G3_plain_time()
void bn12_print_G3_plain_time (void)
References G3SCM_PLAIN.
                               {
    printf("plain-G3-SCM time:%.2f[ms]\n",G3SCM_PLAIN);
}
bn12_print_opt_ate_time()
void bn12_print_opt_ate_time (void)
References MILLER_OPTATE.
Referenced by bn12_test_opt_ate_pairing().
                              {
    printf("miller opt-ate time:%.2f[ms]\n",MILLER_OPTATE);
}
bn12_print_parameters()
void bn12_print_parameters (void)
bn12_print_plain_ate_time()
void bn12_print_plain_ate_time (void)
References MILLER_PLAINATE.
Referenced by bn12_test_plain_ate_pairing().
                                {
    printf("miller plain-ate time:%.2f[ms]\n",MILLER_PLAINATE);
}
bn12_print_tate_time()
void bn12_print_tate_time (void)
References MILLER_TATE.
Referenced by bn12_test_tate_pairing().
                           {
    printf("miller tate time:%.2f[ms]\n",MILLER_TATE);
}
bn12_print_x_ate_time()
void bn12_print_x_ate_time (void)
References MILLER_XATE.
Referenced by bn12_test_x_ate_pairing().
                            {
    printf("miller x-ate time:%.2f[ms]\n",MILLER_XATE);
}
timedifference_msec()
double timedifference_msec (struct timeval t0, struct timeval t1)
Referenced by bls12_2split_G1_scm(), bls12_2split_G2_scm(), bls12_2split_G3_exp(), bls12_4split_G2_scm(), bls12_4split_G3_exp(), bls12_opt_ate(), bls12_plain_ate(), bls12_plain_G1_scm(), bls12_plain_G2_scm(), bls12_plain_G3_exp(), bls12_tate(), bn12_opt_ate(), bn12_plain_ate(), bn12_tate(), and bn12_x_ate().
                                                                {
    return (double)(t1.tv_sec - t0.tv_sec) * 1000.0f + (double)(t1.tv_usec - t0.tv_usec) / 1000.0f;
}
timedifference_usec()
double timedifference_usec (struct timeval t0, struct timeval t1)
                                                                {
    return (double)(t1.tv_sec - t0.tv_sec) * 1000000.0f + (t1.tv_usec - t0.tv_usec);
}
Variable Documentation
FINALEXP_OPT
double FINALEXP_OPT
Referenced by bn12_opt_ate(), bn12_plain_ate(), bn12_print_final_exp_optimal_time(), bn12_tate(), and bn12_x_ate().
FINALEXP_PLAIN
double FINALEXP_PLAIN
Referenced by bn12_print_final_exp_plain_time().
G1SCM_2SPLIT
double G1SCM_2SPLIT
Referenced by bn12_print_G1_2split_time().
G1SCM_PLAIN
double G1SCM_PLAIN
Referenced by bn12_print_G1_plain_time().
G2SCM_2SPLIT
double G2SCM_2SPLIT
Referenced by bn12_print_G2_2split_time().
G2SCM_4SPLIT
double G2SCM_4SPLIT
Referenced by bn12_print_G2_4split_time().
G2SCM_PLAIN
double G2SCM_PLAIN
Referenced by bn12_print_G2_plain_time().
G3SCM_2SPLIT
double G3SCM_2SPLIT
Referenced by bn12_print_G3_2split_time().
G3SCM_4SPLIT
double G3SCM_4SPLIT
Referenced by bn12_print_G3_4split_time().
G3SCM_PLAIN
double G3SCM_PLAIN
Referenced by bn12_print_G3_plain_time().
MILLER_OPTATE
double MILLER_OPTATE
Referenced by bn12_opt_ate(), and bn12_print_opt_ate_time().
MILLER_PLAINATE
double MILLER_PLAINATE
Referenced by bn12_plain_ate(), and bn12_print_plain_ate_time().
MILLER_TATE
double MILLER_TATE
Referenced by bn12_print_tate_time(), and bn12_tate().
MILLER_XATE
double MILLER_XATE
Referenced by bn12_print_x_ate_time(), and bn12_x_ate().
t1
struct timeval t0 t1
Referenced by bls12_2split_G1_scm(), bls12_2split_G2_scm(), bls12_2split_G3_exp(), bls12_4split_G2_scm(), bls12_4split_G3_exp(), bls12_finalexp_optimal(), bls12_opt_ate(), bls12_plain_ate(), bls12_plain_G1_scm(), bls12_plain_G2_scm(), bls12_plain_G3_exp(), bls12_tate(), bn12_opt_ate(), bn12_plain_ate(), bn12_tate(), bn12_x_ate(), Final_exp_optimal(), Final_exp_plain(), and Fp6_mul().