src/bn_bls12_precoms.c File Reference
#include <ELiPS_bn_bls/bn_bls12_precoms.h>
Functions
void init_precoms (int curvetype)
void get_epsilon ()
void set_basis ()
void set_frobenius_constant ()
Variables
gmp_randstate_t state
struct Fp Fp_basis
struct Fp2 Fp2_basis
struct Fp2 Fp2_basis_inv
struct Fp6 Fp6_basis
mpz_t epsilon1
mpz_t epsilon2
Fp2 d12_frobenius_constant [d12][6]
Fp2 d12_skew_frobenius_constant [d12][2]
static mpz_t prime_p
Function Documentation
get_epsilon()
void get_epsilon (void)
Calculate primitive cubic root of 1 in Fp.
References epsilon1, epsilon2, Fp_clear(), Fp_init(), Fp_inv(), Fp_mul(), Fp_set_ui(), Fp_sqrt(), Fp_sub_ui(), prime_p, and Fp::x0.
Referenced by init_precoms().
                  {
    Fp inv,buf,result1,result2;
    Fp_init(&inv);
    Fp_init(&buf);
    Fp_init(&result1);
    Fp_init(&result2);
    
    Fp_set_ui(&buf,2);
    Fp_inv(&inv,&buf);
    mpz_sub_ui(buf.x0,prime_p,3);
    
    Fp_sqrt(&buf,&buf);
    Fp_sub_ui(&buf,&buf,1);
    Fp_mul(&result1,&buf,&inv);
    Fp_mul(&result2,&result1,&result1);
    
    mpz_set(epsilon1,result1.x0);
    mpz_set(epsilon2,result2.x0);
    
    Fp_clear(&inv);
    Fp_clear(&buf);
    Fp_clear(&result1);
    Fp_clear(&result2);
}
init_precoms()
void init_precoms (int curvetype)
Initialize BLS12 curve pre-computations
Parameters
in curvetype - send 2 for BLS12 and 1 for BN
References curve_parameters, d12, epsilon1, epsilon2, Fp2_basis, Fp2_basis_inv, Fp2_init(), Fp6_basis, Fp6_init(), Fp_basis, Fp_init(), get_epsilon(), curve_params::prime, prime_p, set_basis(), and set_frobenius_constant().
Referenced by bls12_inits(), and init_bn().
                                {
    
    mpz_init(prime_p);
    if (curvetype == 1) {
        mpz_set(prime_p,curve_parameters.prime);
    }
    else if (curvetype == 2){
        mpz_set(prime_p,curve_parameters.prime);
    }
    
    Fp_init(&Fp_basis);
    Fp2_init(&Fp2_basis);
    Fp2_init(&Fp2_basis_inv);
    Fp6_init(&Fp6_basis);
    mpz_init(epsilon1);
    mpz_init(epsilon2);
    
    int i,j;
    for(i=0; i<d12; i++){
        for(j=0; j<6; j++){
            Fp2_init(&d12_frobenius_constant[i][j]);
        }
        for(j=0; j<2; j++){
            Fp2_init(&d12_skew_frobenius_constant[i][j]);
        }
    }
    
    
    get_epsilon();
    set_basis();
    set_frobenius_constant();
}
set_basis()
void set_basis (void)
Set basis elements
References Fp2_basis, Fp2_basis_inv, Fp2_inv(), Fp2_set_ui(), Fp6_basis, Fp6_set_ui(), Fp_basis, Fp_set_ui(), and Fp6::x1.
Referenced by init_precoms().
                {
    Fp_set_ui(&Fp_basis,1);
    Fp2_set_ui(&Fp2_basis,1);
    Fp6_set_ui(&Fp6_basis,0);
    Fp_set_ui(&Fp6_basis.x1.x0,1);
    Fp2_inv(&Fp2_basis_inv,&Fp2_basis);
}
set_frobenius_constant()
void set_frobenius_constant (void)
Set Frobenius map constants
References f_p1, f_p10, f_p2, f_p3, f_p4, f_p8, Fp2_basis, Fp2_clear(), Fp2_init(), Fp2_inv(), Fp2_mul(), Fp2_pow(), Fp2_set(), Fp_set_ui(), prime_p, and Fp6::x0.
Referenced by init_precoms().
                             {
    Fp2 tmp1,tmp2,tmp3;
    Fp2_init(&tmp1);
    Fp2_init(&tmp2);
    Fp2_init(&tmp3);
    
    mpz_t exp,buf,p2,p3,p4,p6,p8,p10;
    mpz_init(exp);
    mpz_init(buf);
    mpz_init(p2);
    mpz_init(p3);
    mpz_init(p4);
    mpz_init(p6);
    mpz_init(p8);
    mpz_init(p10);
    
    mpz_mul(p2,prime_p,prime_p);
    mpz_mul(p3,p2,prime_p);
    mpz_mul(p4,p3,prime_p);
    mpz_mul(p6,p4,p2);
    mpz_mul(p8,p6,p2);
    mpz_mul(p10,p8,p2);
    
    //frobenius_1
    mpz_sub_ui(exp,prime_p,1);
    mpz_tdiv_q_ui(exp,exp,3);
    Fp2_pow(&tmp1,&Fp2_basis,exp);
    Fp2_mul(&tmp2,&tmp1,&tmp1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp3,&Fp2_basis,exp);
    //set f_p1
    Fp_set_ui(&d12_frobenius_constant[f_p1][0].x0,1);
    Fp2_set(&d12_frobenius_constant[f_p1][1],&tmp1);
    Fp2_set(&d12_frobenius_constant[f_p1][2],&tmp2);
    Fp2_set(&d12_frobenius_constant[f_p1][3],&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p1][4],&tmp1,&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p1][5],&tmp2,&tmp3);
    //set skew_f_p1
    Fp2_inv(&tmp1,&tmp1);
    mpz_sub_ui(exp,prime_p,1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp2,&Fp2_basis,exp);
    Fp2_inv(&tmp2,&tmp2);
    Fp2_set(&d12_skew_frobenius_constant[f_p1][0],&tmp1);
    Fp2_set(&d12_skew_frobenius_constant[f_p1][1],&tmp2);
    
    //frobenius_2
    mpz_sub_ui(exp,p2,1);
    mpz_tdiv_q_ui(exp,exp,3);
    Fp2_pow(&tmp1,&Fp2_basis,exp);
    Fp2_mul(&tmp2,&tmp1,&tmp1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp3,&Fp2_basis,exp);
    //set f_p2
    Fp_set_ui(&d12_frobenius_constant[f_p2][0].x0,1);
    Fp2_set(&d12_frobenius_constant[f_p2][1],&tmp1);
    Fp2_set(&d12_frobenius_constant[f_p2][2],&tmp2);
    Fp2_set(&d12_frobenius_constant[f_p2][3],&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p2][4],&tmp1,&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p2][5],&tmp2,&tmp3);
    //set skew_f_p2
    Fp2_inv(&tmp1,&tmp1);
    mpz_sub_ui(exp,p2,1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp2,&Fp2_basis,exp);
    Fp2_inv(&tmp2,&tmp2);
    Fp2_set(&d12_skew_frobenius_constant[f_p2][0],&tmp1);
    Fp2_set(&d12_skew_frobenius_constant[f_p2][1],&tmp2);
    
    //frobenius_3
    mpz_sub_ui(exp,p3,1);
    mpz_tdiv_q_ui(exp,exp,3);
    Fp2_pow(&tmp1,&Fp2_basis,exp);
    Fp2_mul(&tmp2,&tmp1,&tmp1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp3,&Fp2_basis,exp);
    //set f_p3
    Fp_set_ui(&d12_frobenius_constant[f_p3][0].x0,1);
    Fp2_set(&d12_frobenius_constant[f_p3][1],&tmp1);
    Fp2_set(&d12_frobenius_constant[f_p3][2],&tmp2);
    Fp2_set(&d12_frobenius_constant[f_p3][3],&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p3][4],&tmp1,&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p3][5],&tmp2,&tmp3);
    //set skew_f_p3
    Fp2_inv(&tmp1,&tmp1);
    mpz_sub_ui(exp,p3,1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp2,&Fp2_basis,exp);
    Fp2_inv(&tmp2,&tmp2);
    Fp2_set(&d12_skew_frobenius_constant[f_p3][0],&tmp1);
    Fp2_set(&d12_skew_frobenius_constant[f_p3][1],&tmp2);
    
    //d12_frobenius_constant[f_p4]
    mpz_sub_ui(exp,p4,1);
    mpz_tdiv_q_ui(exp,exp,3);
    Fp2_pow(&tmp1,&Fp2_basis,exp);
    Fp2_mul(&tmp2,&tmp1,&tmp1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp3,&Fp2_basis,exp);
    //set d12_frobenius_constant[f_p4]
    Fp_set_ui(&d12_frobenius_constant[f_p4][0].x0,1);
    Fp2_set(&d12_frobenius_constant[f_p4][1],&tmp1);
    Fp2_set(&d12_frobenius_constant[f_p4][2],&tmp2);
    Fp2_set(&d12_frobenius_constant[f_p4][3],&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p4][4],&tmp1,&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p4][5],&tmp2,&tmp3);
    
    //d12_frobenius_constant[f_p8]
    mpz_sub_ui(exp,p8,1);
    mpz_tdiv_q_ui(exp,exp,3);
    Fp2_pow(&tmp1,&Fp2_basis,exp);
    Fp2_mul(&tmp2,&tmp1,&tmp1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp3,&Fp2_basis,exp);
    //set d12_frobenius_constant[f_p8]
    Fp_set_ui(&d12_frobenius_constant[f_p8][0].x0,1);
    Fp2_set(&d12_frobenius_constant[f_p8][1],&tmp1);
    Fp2_set(&d12_frobenius_constant[f_p8][2],&tmp2);
    Fp2_set(&d12_frobenius_constant[f_p8][3],&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p8][4],&tmp1,&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p8][5],&tmp2,&tmp3);
    
    //frobenius_10
    mpz_sub_ui(exp,p10,1);
    mpz_tdiv_q_ui(exp,exp,3);
    Fp2_pow(&tmp1,&Fp2_basis,exp);
    Fp2_mul(&tmp2,&tmp1,&tmp1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp3,&Fp2_basis,exp);
    //set frobenius_10
    Fp_set_ui(&d12_frobenius_constant[f_p10][0].x0,1);
    Fp2_set(&d12_frobenius_constant[f_p10][1],&tmp1);
    Fp2_set(&d12_frobenius_constant[f_p10][2],&tmp2);
    Fp2_set(&d12_frobenius_constant[f_p10][3],&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p10][4],&tmp1,&tmp3);
    Fp2_mul(&d12_frobenius_constant[f_p10][5],&tmp2,&tmp3);
    //set skew_f_10
    Fp2_inv(&tmp1,&tmp1);
    mpz_sub_ui(exp,p10,1);
    mpz_tdiv_q_ui(exp,exp,2);
    Fp2_pow(&tmp2,&Fp2_basis,exp);
    Fp2_inv(&tmp2,&tmp2);
    Fp2_set(&d12_skew_frobenius_constant[f_p10][0],&tmp1);
    Fp2_set(&d12_skew_frobenius_constant[f_p10][1],&tmp2);
    
    Fp2_clear(&tmp1);
    Fp2_clear(&tmp2);
    Fp2_clear(&tmp3);
    mpz_clear(exp);
    mpz_clear(buf);
    mpz_clear(p2);
    mpz_clear(p3);
    mpz_clear(p4);
    mpz_clear(p6);
    mpz_clear(p8);
    mpz_clear(p10);
}
Variable Documentation
d12_frobenius_constant
Fp2 d12_frobenius_constant[d12][6]
Constant values for Frobenius map (FM) to multiplied during FM calculations.
Referenced by bls12_Fp12_frobenius_map_p1(), bls12_Fp12_frobenius_map_p10(), bls12_Fp12_frobenius_map_p2(), bls12_Fp12_frobenius_map_p3(), bls12_Fp12_frobenius_map_p4(), bls12_Fp12_frobenius_map_p8(), clear_parameters(), Fp12_frobenius_map_p1(), Fp12_frobenius_map_p10(), Fp12_frobenius_map_p2(), Fp12_frobenius_map_p3(), Fp12_frobenius_map_p4(), and Fp12_frobenius_map_p8().
d12_skew_frobenius_constant
Fp2 d12_skew_frobenius_constant[d12][2]
Constant values for skew Frobenius map (FM) to multiplied during skew FM calculations.
Referenced by bls12_EFp2_skew_frobenius_map_p1(), bls12_EFp2_skew_frobenius_map_p10(), bls12_EFp2_skew_frobenius_map_p2(), bls12_EFp2_skew_frobenius_map_p3(), clear_parameters(), EFp2_skew_frobenius_map_p1(), EFp2_skew_frobenius_map_p10(), EFp2_skew_frobenius_map_p2(), and EFp2_skew_frobenius_map_p3().
epsilon1
mpz_t epsilon1
Primitive Cube root of 1.
Referenced by bls12_EFp_skew_frobenius_map_p2(), clear_parameters(), EFp_skew_frobenius_map_p2(), Fp6_inv(), get_epsilon(), and init_precoms().
epsilon2
mpz_t epsilon2
Referenced by clear_parameters(), Fp6_inv(), get_epsilon(), and init_precoms().
Fp2_basis
struct Fp2 Fp2_basis
Basis element in Fp2 extension field.
Referenced by clear_parameters(), init_precoms(), set_basis(), and set_frobenius_constant().
Fp2_basis_inv
struct Fp2 Fp2_basis_inv
Inverted Fp2 basis element.
Referenced by Fp2_inv_basis(), init_precoms(), and set_basis().
Fp6_basis
struct Fp6 Fp6_basis
Basis element in Fp6 extension field.
Referenced by clear_parameters(), init_precoms(), and set_basis().
Fp_basis
struct Fp Fp_basis
Basis element in prime field.
Referenced by clear_parameters(), init_precoms(), and set_basis().
prime_p
mpz_t prime_p [static]
Referenced by get_epsilon(), init_precoms(), and set_frobenius_constant().
state
gmp_randstate_t state