include/ELiPS_bn_bls/bn_efp12.h File Reference
#include <ELiPS_bn_bls/bn_efp6.h>
Functions
void EFp12_init (EFp12 *P)
void EFp12_clear (EFp12 *P)
void EFp12_printf (EFp12 *P, char *str)
void EFp12_set (EFp12 *ANS, EFp12 *P)
void EFp12_set_ui (EFp12 *ANS, unsigned long int UI)
void EFp12_set_mpz (EFp12 *ANS, mpz_t A)
void EFp12_set_neg (EFp12 *ANS, EFp12 *P)
void EFp12_rational_point_bn (EFp12 *P)
void EFp12_rational_point_bls12 (EFp12 *P)
void EFp12_ECD (EFp12 *ANS, EFp12 *P)
void EFp12_ECA (EFp12 *ANS, EFp12 *P1, EFp12 *P2)
void EFp12_SCM (EFp12 *ANS, EFp12 *P, mpz_t scalar)
Function Documentation
EFp12_clear()
void EFp12_clear (EFp12 * P)
References Fp12_clear(), EFp12::x, and EFp12::y.
Referenced by bls12_2split_G1_scm(), bls12_generate_G2_point(), bls12_Miller_algo_for_plain_ate(), bls12_test_G1_scm(), bls12_test_G2_scm(), bls12_test_G3_exp(), bls12_test_opt_ate_pairing(), bls12_test_plain_ate_pairing(), bls12_test_tate_pairing(), bn12_generate_G2_point(), bn12_test_opt_ate_pairing(), bn12_test_plain_ate_pairing(), bn12_test_tate_pairing(), bn12_test_x_ate_pairing(), EFp12_ECA(), EFp12_ECD(), and EFp12_SCM().
                          {
    Fp12_clear(&P->x);
    Fp12_clear(&P->y);
}
EFp12_ECA()
void EFp12_ECA (EFp12 * ANS, EFp12 * P1, EFp12 * P2)
References EFp12_clear(), EFp12_ECD(), EFp12_init(), EFp12_set(), Fp12_clear(), Fp12_cmp(), Fp12_init(), Fp12_inv(), Fp12_mul(), Fp12_sqr(), Fp12_sub(), EFp12::infinity, EFp12::x, and EFp12::y.
Referenced by bls12_generate_G2_point(), bn12_generate_G2_point(), and EFp12_SCM().
                                              {
    if(P1->infinity==1){
        EFp12_set(ANS,P2);
        return;
    }else if(P2->infinity==1){
        EFp12_set(ANS,P1);
        return;
    }else if(Fp12_cmp(&P1->x,&P2->x)==0){
        if(Fp12_cmp(&P1->y,&P2->y)!=0){
            ANS->infinity=1;
            return;
        }else{
            EFp12_ECD(ANS,P1);
            return;
        }
    }
    
    EFp12 Tmp_P1,Tmp_P2;
    EFp12_init(&Tmp_P1);
    EFp12_set(&Tmp_P1,P1);
    EFp12_init(&Tmp_P2);
    EFp12_set(&Tmp_P2,P2);
    Fp12 tmp1,tmp2,lambda;
    Fp12_init(&tmp1);
    Fp12_init(&tmp2);
    Fp12_init(&lambda);
    
    Fp12_sub(&tmp1,&Tmp_P2.x,&Tmp_P1.x);
    Fp12_inv(&tmp1,&tmp1);
    Fp12_sub(&tmp2,&Tmp_P2.y,&Tmp_P1.y);
    Fp12_mul(&lambda,&tmp1,&tmp2);
    Fp12_sqr(&tmp1,&lambda);
    Fp12_sub(&tmp2,&tmp1,&Tmp_P1.x);
    Fp12_sub(&ANS->x,&tmp2,&Tmp_P2.x);
    Fp12_sub(&tmp1,&Tmp_P1.x,&ANS->x);
    Fp12_mul(&tmp2,&lambda,&tmp1);
    Fp12_sub(&ANS->y,&tmp2,&Tmp_P1.y);
    
    //clear
    Fp12_clear(&tmp1);
    Fp12_clear(&tmp2);
    Fp12_clear(&lambda);
    EFp12_clear(&Tmp_P1);
    EFp12_clear(&Tmp_P2);
}
EFp12_ECD()
void EFp12_ECD (EFp12 * ANS, EFp12 * P)
References EFp12_clear(), EFp12_init(), EFp12_set(), Fp12_clear(), Fp12_cmp_zero(), Fp12_init(), Fp12_inv(), Fp12_mul(), Fp12_mul_ui(), Fp12_sqr(), Fp12_sub(), EFp12::infinity, EFp12::x, and EFp12::y.
Referenced by EFp12_ECA(), and EFp12_SCM().
                                   {
    if(Fp12_cmp_zero(&P->y)==0){
        ANS->infinity=1;
        return;
        
    }
    
    EFp12 Tmp_P;
    EFp12_init(&Tmp_P);
    EFp12_set(&Tmp_P,P);
    Fp12 tmp1,tmp2,lambda;
    Fp12_init(&tmp1);
    Fp12_init(&tmp2);
    Fp12_init(&lambda);
    
    Fp12_mul_ui(&tmp1,&Tmp_P.y,2);
    Fp12_inv(&tmp1,&tmp1);
    Fp12_sqr(&tmp2,&Tmp_P.x);
    Fp12_mul_ui(&tmp2,&tmp2,3);
    Fp12_mul(&lambda,&tmp1,&tmp2);
    Fp12_sqr(&tmp1,&lambda);
    Fp12_mul_ui(&tmp2,&Tmp_P.x,2);
    Fp12_sub(&ANS->x,&tmp1,&tmp2);
    Fp12_sub(&tmp1,&Tmp_P.x,&ANS->x);
    Fp12_mul(&tmp2,&lambda,&tmp1);
    Fp12_sub(&ANS->y,&tmp2,&Tmp_P.y);
    
    Fp12_clear(&tmp1);
    Fp12_clear(&tmp2);
    Fp12_clear(&lambda);
    EFp12_clear(&Tmp_P);
}
EFp12_init()
void EFp12_init (EFp12 * P)
References Fp12_init(), EFp12::infinity, EFp12::x, and EFp12::y.
Referenced by bls12_2split_G1_scm(), bls12_generate_G2_point(), bls12_generate_random_point(), bls12_Miller_algo_for_plain_ate(), bls12_test_G1_scm(), bls12_test_G2_scm(), bls12_test_G3_exp(), bls12_test_opt_ate_pairing(), bls12_test_plain_ate_pairing(), bls12_test_tate_pairing(), bn12_generate_G1_point(), bn12_generate_G2_point(), bn12_generate_random_point(), bn12_test_opt_ate_pairing(), bn12_test_plain_ate_pairing(), bn12_test_tate_pairing(), bn12_test_x_ate_pairing(), EFp12_ECA(), EFp12_ECD(), and EFp12_SCM().
                         {
    Fp12_init(&P->x);
    Fp12_init(&P->y);
    P->infinity=0;
}
EFp12_printf()
void EFp12_printf (EFp12 * P, char * str)
References Fp12_printf(), EFp12::infinity, EFp12::x, and EFp12::y.
Referenced by bls12_test_G1_scm(), bls12_test_G2_scm(), bls12_test_opt_ate_pairing(), bls12_test_plain_ate_pairing(), bls12_test_tate_pairing(), bn12_print_G1_point(), bn12_print_G2_point(), bn12_test_opt_ate_pairing(), bn12_test_plain_ate_pairing(), bn12_test_tate_pairing(), and bn12_test_x_ate_pairing().
                                     {
    gmp_printf("%s",str);
    if(P->infinity==0){
        gmp_printf("(");
        Fp12_printf(&P->x,"");
        gmp_printf(",");
        Fp12_printf(&P->y,"");
        gmp_printf(")");
    }else{
        gmp_printf("infinity");
    }
}
EFp12_rational_point_bls12()
void EFp12_rational_point_bls12 (EFp12 * P)
References curve_params::curve_b, curve_parameters, Fp12_clear(), Fp12_init(), Fp12_legendre(), Fp12_mul(), Fp12_set_random(), Fp12_sqr(), Fp12_sqrt(), EFp12::x, Fp6::x0, Fp12::x0, and EFp12::y.
Referenced by bls12_generate_G2_point(), bls12_generate_random_point(), and bls12_test_tate_pairing().
                                         {
    Fp12 tmp1,tmp2;
    Fp12_init(&tmp1);
    Fp12_init(&tmp2);
    gmp_randstate_t state;
    gmp_randinit_default (state);
    gmp_randseed_ui(state,(unsigned long)time(NULL));
    
    while(1){
        Fp12_set_random(&P->x,state);
        Fp12_sqr(&tmp1,&P->x);
        Fp12_mul(&tmp2,&tmp1,&P->x);
        mpz_add(tmp2.x0.x0.x0.x0,tmp2.x0.x0.x0.x0, curve_parameters.
      curve_b);
        if(Fp12_legendre(&tmp2)==1){
            Fp12_sqrt(&P->y,&tmp2);
            break;
        }
    }
    
    Fp12_clear(&tmp1);
    Fp12_clear(&tmp2);
}
EFp12_rational_point_bn()
void EFp12_rational_point_bn (EFp12 * P)
References curve_params::curve_b, curve_parameters, Fp12_clear(), Fp12_init(), Fp12_legendre(), Fp12_mul(), Fp12_set_random(), Fp12_sqr(), Fp12_sqrt(), EFp12::x, Fp6::x0, Fp12::x0, and EFp12::y.
Referenced by bn12_generate_G2_point(), bn12_generate_random_point(), and bn12_test_tate_pairing().
                                      {
    Fp12 tmp1,tmp2;
    Fp12_init(&tmp1);
    Fp12_init(&tmp2);
    gmp_randstate_t state;
    gmp_randinit_default (state);
    gmp_randseed_ui(state,(unsigned long)time(NULL));
    
    while(1){
        Fp12_set_random(&P->x,state);
        Fp12_sqr(&tmp1,&P->x);
        Fp12_mul(&tmp2,&tmp1,&P->x);
        mpz_sub(tmp2.x0.x0.x0.x0,tmp2.x0.x0.x0.x0,curve_parameters.
      curve_b);
        if(Fp12_legendre(&tmp2)==1){
            Fp12_sqrt(&P->y,&tmp2);
            break;
        }
    }
    
    Fp12_clear(&tmp1);
    Fp12_clear(&tmp2);
}
EFp12_SCM()
void EFp12_SCM (EFp12 * ANS, EFp12 * P, mpz_t scalar)
References EFp12_clear(), EFp12_ECA(), EFp12_ECD(), EFp12_init(), EFp12_set(), and EFp12::infinity.
Referenced by bls12_generate_G1_point(), bls12_generate_G2_point(), bls12_test_opt_ate_pairing(), bls12_test_plain_ate_pairing(), bls12_test_tate_pairing(), bn12_generate_G2_point(), bn12_test_opt_ate_pairing(), bn12_test_plain_ate_pairing(), bn12_test_tate_pairing(), and bn12_test_x_ate_pairing().
                                                {
    if(mpz_cmp_ui(scalar,0)==0){
        ANS->infinity=1;
        return;
    }else if(mpz_cmp_ui(scalar,1)==0){
        EFp12_set(ANS,P);
        return;
    }
    
    EFp12 Tmp_P,Next_P;
    EFp12_init(&Tmp_P);
    EFp12_set(&Tmp_P,P);
    EFp12_init(&Next_P);
    int i,length;
    length=(int)mpz_sizeinbase(scalar,2);
    char binary[length];
    mpz_get_str(binary,2,scalar);
    
    EFp12_set(&Next_P,&Tmp_P);
    for(i=1; i<length; i++){
        EFp12_ECD(&Next_P,&Next_P);
        if(binary[i]=='1'){
            EFp12_ECA(&Next_P,&Next_P,&Tmp_P);
        }
    }
    EFp12_set(ANS,&Next_P);
    
    EFp12_clear(&Next_P);
    EFp12_clear(&Tmp_P);
}
EFp12_set()
void EFp12_set (EFp12 * ANS, EFp12 * P)
References Fp12_set(), EFp12::infinity, EFp12::x, and EFp12::y.
Referenced by EFp12_ECA(), EFp12_ECD(), and EFp12_SCM().
                                   {
    Fp12_set(&ANS->x,&P->x);
    Fp12_set(&ANS->y,&P->y);
    ANS->infinity=P->infinity;
}
EFp12_set_mpz()
void EFp12_set_mpz (EFp12 * ANS, mpz_t A)
References Fp12_set_mpz(), EFp12::infinity, EFp12::x, and EFp12::y.
                                      {
    Fp12_set_mpz(&ANS->x,A);
    Fp12_set_mpz(&ANS->y,A);
    ANS->infinity=0;
}
EFp12_set_neg()
void EFp12_set_neg (EFp12 * ANS, EFp12 * P)
References Fp12_set(), Fp12_set_neg(), EFp12::infinity, EFp12::x, and EFp12::y.
Referenced by bls12_generate_G2_point(), and bn12_generate_G2_point().
                                       {
    Fp12_set(&ANS->x,&P->x);
    Fp12_set_neg(&ANS->y,&P->y);
    ANS->infinity=P->infinity;
}
EFp12_set_ui()
void EFp12_set_ui (EFp12 * ANS, unsigned long int UI)
References Fp12_set_ui(), EFp12::infinity, EFp12::x, and EFp12::y.
Referenced by bn12_generate_G1_point().
                                                  {
    Fp12_set_ui(&ANS->x,UI);
    Fp12_set_ui(&ANS->y,UI);
    ANS->infinity=0;
}