src/bn_generate_points.c File Reference
#include <ELiPS_bn_bls/bn_generate_points.h>
Functions
void bn12_generate_G1_point (EFp12 *P)
void bn12_generate_G2_point (EFp12 *Q)
void bn12_generate_random_point (EFp12 *R)
Variables
EFp12 G1_P
EFp12 G2_Q
EFp12 Random_R
Function Documentation
bn12_generate_G1_point()
void bn12_generate_G1_point (EFp12 * P)
References EFp12_init(), EFp12_set_ui(), EFp_clear(), EFp_init(), EFp_rational_point_bn(), Fp_set(), EFp::infinity, EFp12::infinity, EFp::x, EFp12::x, Fp6::x0, Fp12::x0, EFp::y, and EFp12::y.
Referenced by bn12_test_opt_ate_pairing(), bn12_test_plain_ate_pairing(), bn12_test_tate_pairing(), and bn12_test_x_ate_pairing().
                                     {
    EFp12_init(P);
    EFp Tmp;
    EFp_init(&Tmp);
    
    EFp_rational_point_bn(&Tmp);
    EFp12_set_ui(P,0);
    Fp_set(&P->x.x0.x0.x0,&Tmp.x);
    Fp_set(&P->y.x0.x0.x0,&Tmp.y);
    P->infinity=Tmp.infinity;
    
    EFp_clear(&Tmp);
}
bn12_generate_G2_point()
void bn12_generate_G2_point (EFp12 * Q)
References curve_parameters, EFp12_clear(), EFp12_ECA(), EFp12_init(), EFp12_rational_point_bn(), EFp12_SCM(), EFp12_set_neg(), curve_params::EFpd_total, Fp12_frobenius_map_p1(), curve_params::order, EFp12::x, and EFp12::y.
Referenced by bn12_test_opt_ate_pairing(), bn12_test_plain_ate_pairing(), and bn12_test_x_ate_pairing().
                                     {
    EFp12_init(Q);
    EFp12 random_P,P,frobenius_P;
    EFp12_init(&random_P);
    EFp12_init(&P);
    EFp12_init(&frobenius_P);
    mpz_t exp;
    mpz_init(exp);
    
    EFp12_rational_point_bn(&random_P);
    mpz_pow_ui(exp,curve_parameters.order,2);
    mpz_tdiv_q(exp,curve_parameters.EFpd_total,exp);
    EFp12_SCM(&P,&random_P,exp);
    Fp12_frobenius_map_p1(&frobenius_P.x,&P.x);
    Fp12_frobenius_map_p1(&frobenius_P.y,&P.y);
    EFp12_set_neg(&P,&P);
    EFp12_ECA(Q,&P,&frobenius_P);
    
    mpz_clear(exp);
    EFp12_clear(&random_P);
    EFp12_clear(&P);
    EFp12_clear(&frobenius_P);
}
bn12_generate_random_point()
void bn12_generate_random_point (EFp12 * R)
References EFp12_init(), and EFp12_rational_point_bn().
                                         {
    EFp12_init(R);
    EFp12_rational_point_bn(R);
}
Variable Documentation
G1_P
EFp12 G1_P
Referenced by bn12_print_G1_point().
G2_Q
EFp12 G2_Q
Referenced by bn12_print_G2_point().
Random_R
EFp12 Random_R