src/fp4.c File Reference
#include <ELiPS_bn_bls/fp4.h>
Functions
void Fp4_init (Fp4 *A)
void Fp4_set (Fp4 *ANS, Fp4 *A)
void Fp4_set_ui (Fp4 *A, signed long int B)
void Fp4_set_random (Fp4 *A, gmp_randstate_t state)
void Fp4_clear (Fp4 *A)
void Fp4_printf (Fp4 *A)
void Fp4_add (Fp4 *ANS, Fp4 *A, Fp4 *B)
void Fp4_add_ui (Fp4 *ANS, Fp4 *A, unsigned long int B)
void Fp4_sub (Fp4 *ANS, Fp4 *A, Fp4 *B)
void Fp4_sqr (Fp4 *ANS, Fp4 *A)
void Fp4_mul (Fp4 *ANS, Fp4 *A, Fp4 *B)
void Fp4_mul_basis (Fp4 *ANS, Fp4 *A)
void Fp4_mul_ui (Fp4 *ANS, Fp4 *A, unsigned long int B)
void Fp4_mul_mpz (Fp4 *ANS, Fp4 *A, mpz_t B)
void Fp4_mul_Fp (Fp4 *ANS, Fp4 *A, Fp *B)
void Fp4_invert (Fp4 *ANS, Fp4 *A)
void Fp4_div (Fp4 *ANS, Fp4 *A, Fp4 *B)
void Fp4_pow (Fp4 *ANS, Fp4 *A, mpz_t B)
void Fp4_sqrt (Fp4 *ANS, Fp4 *A)
int Fp4_legendre (Fp4 *a)
int Fp4_cmp (Fp4 *A, Fp4 *B)
int Fp4_cmp_mpz (Fp4 *A, mpz_t B)
void Fp4_neg (Fp4 *ans, Fp4 *a)
void Fp4_mul_betainv (Fp4 *ANS)
Function Documentation
Fp4_add()
void Fp4_add (Fp4 * ANS, Fp4 * A, Fp4 * B)
References Fp2_add(), and Fp4::x1.
Referenced by Fp8_add(), Fp8_mul(), and Fp8_sqr().
                                       {
    Fp2_add(&ANS->x0,&A->x0,&B->x0);
    Fp2_add(&ANS->x1,&A->x1,&B->x1);
}
Fp4_add_ui()
void Fp4_add_ui (Fp4 * ANS, Fp4 * A, unsigned long int B)
References Fp2_add_ui(), and Fp4::x1.
Referenced by Fp8_add_ui().
                                                      {
    Fp2_add_ui(&ANS->x0,&A->x0,B);
    Fp2_add_ui(&ANS->x1,&A->x1,B);
}
Fp4_clear()
void Fp4_clear (Fp4 * A)
References Fp2_clear(), and Fp4::x1.
Referenced by Fp4_div(), Fp4_invert(), Fp4_legendre(), Fp4_mul_basis(), Fp4_mul_betainv(), Fp4_pow(), Fp4_sqrt(), Fp8_clear(), Fp8_mul(), and Fp8_sqr().
                       {
    Fp2_clear(&A->x0);
    Fp2_clear(&A->x1);
}
Fp4_cmp()
int Fp4_cmp (Fp4 * A, Fp4 * B)
References Fp2_cmp(), and Fp4::x1.
Referenced by Fp8_cmp().
                            {
    if(Fp2_cmp(&A->x0,&B->x0)==0 && Fp2_cmp(&A->x1,&B->x1)==0){
        return 0;
    }
    return 1;
}
Fp4_cmp_mpz()
int Fp4_cmp_mpz (Fp4 * A, mpz_t B)
References Fp2_cmp_mpz(), and Fp4::x1.
Referenced by Fp4_legendre(), Fp4_sqrt(), and Fp8_cmp_mpz().
                                {
    if(Fp2_cmp_mpz(&A->x0,B)==0 && Fp2_cmp_mpz(&A->x1,B)==0){
        return 0;
    }
    return 1;
}
Fp4_div()
void Fp4_div (Fp4 * ANS, Fp4 * A, Fp4 * B)
References Fp4_clear(), Fp4_init(), Fp4_invert(), Fp4_mul(), and Fp4_set().
                                       {
    struct Fp4 tmp,t_ans;
    Fp4_init(&tmp);
    Fp4_init(&t_ans);
    
    Fp4_invert(&tmp,B);
    Fp4_mul(&t_ans,A,&tmp);
    
    Fp4_set(ANS,&t_ans);
    
    Fp4_clear(&tmp);
    Fp4_clear(&t_ans);
}
Fp4_init()
void Fp4_init (Fp4 * A)
References Fp2_init(), and Fp4::x1.
Referenced by Fp4_div(), Fp4_invert(), Fp4_legendre(), Fp4_mul_basis(), Fp4_mul_betainv(), Fp4_pow(), Fp4_sqrt(), Fp8_init(), Fp8_mul(), and Fp8_sqr().
                     {
    Fp2_init(&A->x0);
    Fp2_init(&A->x1);
}
Fp4_invert()
void Fp4_invert (Fp4 * ANS, Fp4 * A)
References Fp2_invert_kss16(), Fp2_mul(), Fp2_neg(), Fp2_set(), Fp4_clear(), Fp4_init(), Fp4_mul(), and Fp4::x1.
Referenced by Fp4_div(), and Fp8_invert().
                                  {
    struct Fp4 frob,buf;
    Fp4_init(&frob);
    Fp4_init(&buf);
    
    Fp2_set(&frob.x0,&A->x0);
    Fp2_neg(&frob.x1,&A->x1);
    Fp4_mul(&buf,A,&frob);
    Fp2_invert_kss16(&buf.x0,&buf.x0);
    Fp2_mul(&ANS->x0,&frob.x0,&buf.x0);
    Fp2_mul(&ANS->x1,&frob.x1,&buf.x0);
    
    Fp4_clear(&frob);
    Fp4_clear(&buf);
}
Fp4_legendre()
int Fp4_legendre (Fp4 * a)
References curve_parameters, Fp4_clear(), Fp4_cmp_mpz(), Fp4_init(), Fp4_pow(), and curve_params::prime.
Referenced by Fp4_sqrt().
                         {
    mpz_t i,cmp;
     Fp4 tmp;
    Fp4_init(&tmp);
    mpz_init(i);
    mpz_init(cmp);
    mpz_set_ui(cmp,1);
    mpz_pow_ui(i,curve_parameters.prime,4);
    mpz_sub_ui(i,i,1);
    mpz_tdiv_q_ui(i,i,2);
    Fp4_pow(&tmp,a,i);
    
    if((Fp4_cmp_mpz(&tmp,cmp))==0){
        Fp4_clear(&tmp);
        mpz_clear(i);
        mpz_clear(cmp);
        return 1;
    }else{
        Fp4_clear(&tmp);
        mpz_clear(i);
        mpz_clear(cmp);
        return -1;
    }
}
Fp4_mul()
void Fp4_mul (Fp4 * ANS, Fp4 * A, Fp4 * B)
References Fp2_add(), Fp2_clear(), Fp2_init(), Fp2_mul(), Fp2_mul_basis_KSS16(), Fp2_sub(), and Fp4::x1.
Referenced by Fp4_div(), Fp4_invert(), Fp4_pow(), Fp4_sqrt(), Fp8_invert(), Fp8_mul(), and Fp8_sqr().
                                       {
    struct Fp2 tmp1,tmp2;
    Fp2_init(&tmp1);
    Fp2_init(&tmp2);
    
    //set
    Fp2_mul(&tmp2,&A->x1,&B->x1);//b*d
    Fp2_add(&tmp1,&A->x0,&A->x1);//a+b
    Fp2_add(&ANS->x1,&B->x0,&B->x1);//c+d
    Fp2_mul(&ANS->x1,&tmp1,&ANS->x1);//(a+b)(c+d)
    Fp2_mul(&tmp1,&A->x0,&B->x0);//a*c
    //x0
    Fp2_mul_basis_KSS16(&ANS->x0,&tmp2);//b*d*v
    Fp2_add(&ANS->x0,&ANS->x0,&tmp1);//a*c+b*d*v
    //x1
    Fp2_sub(&ANS->x1,&ANS->x1,&tmp1);
    Fp2_sub(&ANS->x1,&ANS->x1,&tmp2);
    
    //clear
    Fp2_clear(&tmp1);
    Fp2_clear(&tmp2);
}
Fp4_mul_basis()
void Fp4_mul_basis (Fp4 * ANS, Fp4 * A)
References Fp4_clear(), Fp4_init(), Fp4_set(), Fp_mul_basis_KSS16(), Fp_set(), Fp2::x1, and Fp4::x1.
Referenced by Fp8_mul(), and Fp8_sqr().
                                     {
    struct Fp4 tmp;
    Fp4_init(&tmp);
    Fp4_set(&tmp,A);
    
    Fp_mul_basis_KSS16(&ANS->x0.x0,&tmp.x1.x1);
    Fp_set(&ANS->x0.x1,&tmp.x1.x0);
    Fp_set(&ANS->x1.x0,&tmp.x0.x0);
    Fp_set(&ANS->x1.x1,&tmp.x0.x1);
    
    Fp4_clear(&tmp);
}
Fp4_mul_betainv()
void Fp4_mul_betainv (Fp4 * ANS)
References C1_INV, curve_params::curve_a, curve_parameters, Fp4_clear(), Fp4_init(), Fp4_set(), Fp4_set_ui(), Fp::x0, Fp4::x1, and Fp2::x1.
{
     Fp4 tmp;
    Fp4_init(&tmp);
    Fp4_set_ui(&tmp, 0);
    mpz_set(tmp.x1.x1.x0,curve_parameters.curve_a);
    mpz_mul(tmp.x1.x1.x0,tmp.x1.x1.x0,C1_INV);
    
    Fp4_set(ANS, &tmp);
    Fp4_clear(&tmp);
}
Fp4_mul_Fp()
void Fp4_mul_Fp (Fp4 * ANS, Fp4 * A, Fp * B)
References Fp2_mul_Fp(), and Fp4::x1.
Referenced by Fp8_mul_Fp().
                                         {
    Fp2_mul_Fp(&ANS->x0,&A->x0,B);
    Fp2_mul_Fp(&ANS->x1,&A->x1,B);
}
Fp4_mul_mpz()
void Fp4_mul_mpz (Fp4 * ANS, Fp4 * A, mpz_t B)
References Fp2_mul_mpz(), and Fp4::x1.
Referenced by Fp8_mul_mpz().
                                           {
    Fp2_mul_mpz(&ANS->x0,&A->x0,B);
    Fp2_mul_mpz(&ANS->x1,&A->x1,B);
}
Fp4_mul_ui()
void Fp4_mul_ui (Fp4 * ANS, Fp4 * A, unsigned long int B)
References Fp2_mul_ui(), and Fp4::x1.
Referenced by Fp8_mul_ui().
                                                      {
    Fp2_mul_ui(&ANS->x0,&A->x0,B);
    Fp2_mul_ui(&ANS->x1,&A->x1,B);
}
Fp4_neg()
void Fp4_neg (Fp4 * ans, Fp4 * a)
References Fp2_neg(), and Fp4::x1.
Referenced by Fp8_invert(), and Fp8_neg().
                               {
    Fp2_neg(&ans->x0,&a->x0);
    Fp2_neg(&ans->x1,&a->x1);
}
Fp4_pow()
void Fp4_pow (Fp4 * ANS, Fp4 * A, mpz_t B)
References Fp4_clear(), Fp4_init(), Fp4_mul(), Fp4_set(), and Fp4_sqr().
Referenced by Fp4_legendre(), and Fp4_sqrt().
                                       {
    int i,length;
    length=(int)mpz_sizeinbase(B,2);
    char binary[length];
    mpz_get_str(binary,2,B);
     Fp4 buf;
    Fp4_init(&buf);
    Fp4_set(&buf,A);
    
    for(i=1; i<length; i++){
        //Fp2_mul(&buf,&buf,&buf);
        Fp4_sqr(&buf,&buf);
        if(binary[i]=='1'){
            Fp4_mul(&buf,A,&buf);
        }
    }
    
    Fp4_set(ANS,&buf);
    Fp4_clear(&buf);
}
Fp4_printf()
void Fp4_printf (Fp4 * A)
References Fp::x0, Fp4::x1, and Fp2::x1.
                        {
    gmp_printf("(%Zd,%Zd,%Zd,%Zd\n",A->x0.x0.x0,A->x0.x1.x0,A->x1.x0.x0,A->
      x1.x1.x0);
}
Fp4_set()
void Fp4_set (Fp4 * ANS, Fp4 * A)
References Fp2_set(), and Fp4::x1.
Referenced by Fp4_div(), Fp4_mul_basis(), Fp4_mul_betainv(), Fp4_pow(), Fp4_sqrt(), Fp8_invert(), and Fp8_set().
                               {
    Fp2_set(&ANS->x0,&A->x0);
    Fp2_set(&ANS->x1,&A->x1);
}
Fp4_set_random()
void Fp4_set_random (Fp4 * A, gmp_randstate_t state)
References Fp2_set_random(), and Fp4::x1.
Referenced by Fp4_sqrt(), and Fp8_set_random().
                                                  {
    Fp2_set_random(&A->x0, state);
    Fp2_set_random(&A->x1, state);
}
Fp4_set_ui()
void Fp4_set_ui (Fp4 * A, signed long int B)
References Fp2_set_ui(), and Fp4::x1.
Referenced by Fp4_mul_betainv(), and Fp8_set_ui().
                                          {
    Fp2_set_ui(&A->x0,B);
    Fp2_set_ui(&A->x1,B);
}
Fp4_sqr()
void Fp4_sqr (Fp4 * ANS, Fp4 * A)
References Fp2_add(), Fp2_clear(), Fp2_init(), Fp2_mul(), Fp2_mul_basis_KSS16(), Fp2_sub(), and Fp4::x1.
Referenced by Fp4_pow().
                               {
     Fp2 tmp1,tmp2,tmp3;
    Fp2_init(&tmp1);
    Fp2_init(&tmp2);
    Fp2_init(&tmp3);
    
    Fp2_add(&tmp1,&A->x0,&A->x1);
    Fp2_mul_basis_KSS16(&tmp2,&A->x1);
    Fp2_add(&tmp2,&tmp2,&A->x0);
    Fp2_mul(&tmp3,&A->x0,&A->x1);
    
    //x0
    Fp2_mul(&ANS->x0,&tmp1,&tmp2);
    Fp2_sub(&ANS->x0,&ANS->x0,&tmp3);
    Fp2_mul_basis_KSS16(&tmp1,&tmp3);
    Fp2_sub(&ANS->x0,&ANS->x0,&tmp1);
    //x1
    Fp2_add(&ANS->x1,&tmp3,&tmp3);
    
    Fp2_clear(&tmp1);
    Fp2_clear(&tmp2);
    Fp2_clear(&tmp3);
}
Fp4_sqrt()
void Fp4_sqrt (Fp4 * ANS, Fp4 * A)
References curve_parameters, Fp4_clear(), Fp4_cmp_mpz(), Fp4_init(), Fp4_legendre(), Fp4_mul(), Fp4_pow(), Fp4_set(), Fp4_set_random(), and curve_params::prime.
                                {
    struct Fp4 n,y,x,b,t,tmp_Fp4;
    Fp4_init(&n);
    Fp4_init(&y);
    Fp4_init(&x);
    Fp4_init(&b);
    Fp4_init(&t);
    Fp4_init(&tmp_Fp4);
    Fp4_set(&n,A);
    
    mpz_t tmp_mpz,q,e,r,set_1,set_2;
    mpz_init(tmp_mpz);
    mpz_init(q);
    mpz_init(e);
    mpz_init(r);
    mpz_init(set_1);
    mpz_init(set_2);
    mpz_set_ui(set_1,1);
    mpz_set_ui(set_2,2);
    
    gmp_randstate_t state;
    gmp_randinit_default(state);
    gmp_randseed_ui(state,(unsigned long)time(NULL));
    
    Fp4_set_random(&n,state);
    while(Fp4_legendre(&n)!=-1){
        Fp4_set_random(&n,state);
    }
    mpz_pow_ui(q,curve_parameters.prime,12);
    mpz_sub_ui(q,q,1);
    mpz_set_ui(e,0);
    while(mpz_odd_p(q)==0){
        mpz_add_ui(e,e,1);
        mpz_div_ui(q,q,2);
    }
    Fp4_pow(&y,&n,q);
    
    mpz_set(r,e);
    
    mpz_sub_ui(tmp_mpz,q,1);
    mpz_div_ui(tmp_mpz,tmp_mpz,2);
    
    Fp4_pow(&x,A,tmp_mpz);
    Fp4_pow(&tmp_Fp4,&x,set_2);
    Fp4_mul(&b,&tmp_Fp4,A);
    Fp4_mul(&x,&x,A);
    
    int m;
    
    while(Fp4_cmp_mpz(&b,set_1)==1){
        m=-1;
        Fp4_set(&tmp_Fp4,&b);
        while(Fp4_cmp_mpz(&tmp_Fp4,set_1)==1){
            m++;
            mpz_pow_ui(tmp_mpz,set_2,m);
            Fp4_pow(&tmp_Fp4,&b,tmp_mpz);
        }
        mpz_sub_ui(tmp_mpz,r,m);
        mpz_sub_ui(tmp_mpz,tmp_mpz,1);
        mpz_powm(tmp_mpz,set_2,tmp_mpz,curve_parameters.prime);
        // gmp_printf("%Zd,%Zd,%d\n",tmp_mpz,r,m);
        Fp4_pow(&t,&y,tmp_mpz);
        Fp4_pow(&y,&t,set_2);
        // gmp_printf("%Zd,%Zd,\n",y.x0.x0.x0,y.x0.x1.x0);
        mpz_set_ui(r,m);
        Fp4_mul(&x,&x,&t);
        Fp4_mul(&b,&b,&y);
    }
    
    Fp4_set(ANS,&x);
    
    Fp4_clear(&n);
    Fp4_clear(&y);
    Fp4_clear(&x);
    Fp4_clear(&b);
    Fp4_clear(&t);
    Fp4_clear(&tmp_Fp4);
    mpz_clear(tmp_mpz);
    mpz_clear(q);
    mpz_clear(e);
    mpz_clear(r);
    mpz_clear(set_1);
}
Fp4_sub()
void Fp4_sub (Fp4 * ANS, Fp4 * A, Fp4 * B)
References Fp2_sub(), and Fp4::x1.
Referenced by Fp8_mul(), Fp8_sqr(), and Fp8_sub().
                                       {
    Fp2_sub(&ANS->x0,&A->x0,&B->x0);
    Fp2_sub(&ANS->x1,&A->x1,&B->x1);
}