"""Emit Montgomery parameters for each curve (Phase 3, issue #4).

Generated rather than hand-written because a mistyped limb in R^2 or n0 gives
arithmetic that is wrong in a way no amount of staring detects.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from elips_ref import CURVES, _naf as _naf_digits

W = 64
MASK = (1 << W) - 1
SEP = ",\n        "

def limb_list(x, n):
    return SEP.join("UINT64_C(0x%016x)" % ((x >> (W * i)) & MASK) for i in range(n))

parts = ["""/* Generated by tools/reference/gen_params.py -- do not edit.
 *
 * Montgomery parameters, one block per curve. R = 2^(64*FP_LIMBS).
 *   FP_MONT_N0 = -p^-1 mod 2^64   the REDC multiplier
 *   FP_R2      = R^2 mod p        converts a plain residue into Montgomery form
 *   FP_ONE     = R mod p          the Montgomery representation of 1
 */
#ifndef ELIPS_FP_PARAMS_H
#define ELIPS_FP_PARAMS_H

#include <stdint.h>
#include <gmp.h>

/* Alias GMP's limb type rather than uint64_t. They are both 64 bits wide on the
 * platforms we target, but they are distinct C types (unsigned long vs unsigned
 * long long on LP64), and passing one where the other is expected is a
 * constraint violation that happens to work. The mpn_* calls in fp.c need the
 * real thing. */
typedef mp_limb_t limb_t;

#if GMP_LIMB_BITS != 64
#  error "These parameters are generated for 64-bit GMP limbs."
#endif
"""]

for macro, cname in (("ELIPS_CURVE_BLS12_381", "BLS12-381"),
                     ("ELIPS_CURVE_BLS12_461", "BLS12-461"),
                     ("ELIPS_CURVE_BN_462",    "BN-462")):
    cv = CURVES[cname]
    p = cv.p
    n = (p.bit_length() + W - 1) // W
    R = 1 << (W * n)
    n0 = (-pow(p, -1, 1 << W)) % (1 << W)
    assert (p * n0) % (1 << W) == MASK, "n0 must satisfy p*n0 == -1 mod 2^64"
    r2, one = (R * R) % p, R % p
    sign = "+" if cv.sign_b > 0 else "-"

    # Frobenius constants. In fp12 = fp6[w] with w^6 = xi = 1+u, the p-power
    # map sends sum(a_i w^i) to sum(conj(a_i) * gamma^i * w^i) where
    # gamma = w^(p-1) = xi^((p-1)/6). Emitted already in Montgomery form so the
    # library needs no initialisation step and no global state.
    def fp2_pow(base, e):
        r_ = (1, 0)
        b_ = base
        while e:
            if e & 1:
                r_ = ((r_[0]*b_[0] - r_[1]*b_[1]) % p, (r_[0]*b_[1] + r_[1]*b_[0]) % p)
            b_ = ((b_[0]*b_[0] - b_[1]*b_[1]) % p, (2*b_[0]*b_[1]) % p)
            e >>= 1
        return r_
    xi = (1, 1)
    frob = {}
    for k in (1, 2, 3):
        e = (pow(p, k) - 1) // 6
        g = fp2_pow(xi, e)
        # gamma^1 .. gamma^5
        acc, row = (1, 0), []
        for _ in range(5):
            acc = ((acc[0]*g[0] - acc[1]*g[1]) % p, (acc[0]*g[1] + acc[1]*g[0]) % p)
            row.append(acc)
        frob[k] = row
    # sanity: gamma^6 must be xi^(p^k - 1), and applying frobenius 12 times is
    # the identity, which the C-side vectors will confirm independently.
    # Miller loop parameter as signed digits, most significant last in the
    # array. BLS12 loops over X; BN loops over 6x+2.
    loop = cv.loop_digits
    top = max(loop)
    digits = [loop.get(i, 0) for i in range(top + 1)]
    # The mother parameter x, as signed digits. For BLS12 this is the same as
    # the Miller loop parameter; for BN the loop runs over 6x+2 instead, and
    # the final exponentiation needs x itself. Keeping them separate avoids the
    # obvious trap.
    xd = _naf_digits(cv.X)
    xtop = max(xd)
    xdigits = [xd.get(i, 0) for i in range(xtop + 1)]
    assert sum(d * 2**i for i, d in enumerate(xdigits)) == cv.X
    param_txt = ("  #define ELIPS_PARAM_TOP    %d\n" % xtop +
                 "  static const signed char ELIPS_PARAM[%d] = { %s };\n"
                 % (xtop + 1, ", ".join(str(d) for d in xdigits)))

    loop_txt = param_txt + ("  #define ELIPS_LOOP_TOP     %d\n" % top +
                "  #define ELIPS_FAMILY_%s   1\n" % cv.family.upper() +
                "  static const signed char ELIPS_LOOP[%d] = { %s };\n"
                % (top + 1, ", ".join(str(d) for d in digits)))

    # Hard part of the final exponentiation, (p^4 - p^2 + 1)/r, as limbs.
    # Used by the definitionally-correct slow path that validates any fast chain.
    ordr = cv.r
    hard = (p**4 - p**2 + 1) // ordr
    assert (p**4 - p**2 + 1) % ordr == 0, "r must divide p^4 - p^2 + 1"
    hn = (hard.bit_length() + W - 1) // W
    hard_txt = ("  #define ELIPS_HARD_BITS    %d\n" % hard.bit_length() +
                "  #define ELIPS_HARD_LIMBS   %d\n" % hn +
                "  static const limb_t ELIPS_HARD_EXP[%d] = {\n        %s\n  };\n"
                % (hn, limb_list(hard, hn)))

    # Skew Frobenius (psi) on the twist, needed by the BN correction lines.
    #
    # Untwisting sends (x',y') to (x'/w^2, y'/w^3); applying the p-power map
    # there and twisting back gives
    #     psi(x',y') = (conj(x') * gamma^-2, conj(y') * gamma^-3)
    # with gamma = w^(p-1) = xi^((p-1)/6). Applying psi twice leaves
    #     psi^2(x,y) = (x * N(gamma^-2), y * N(gamma^-3))
    # where N is the Fp2 norm, so the psi^2 multipliers lie in Fp.
    def fp2_inv_(a):
        n = pow((a[0]*a[0] + a[1]*a[1]) % p, p - 2, p)
        return ((a[0]*n) % p, (-a[1]*n) % p)
    def fp2_mul_(a, b):
        return ((a[0]*b[0] - a[1]*b[1]) % p, (a[0]*b[1] + a[1]*b[0]) % p)
    g1 = fp2_pow(xi, (p - 1) // 6)
    u2 = fp2_inv_(fp2_mul_(g1, g1))
    u3 = fp2_inv_(fp2_mul_(fp2_mul_(g1, g1), g1))
    w2 = fp2_mul_(u2, (u2[0], (-u2[1]) % p))
    w3 = fp2_mul_(u3, (u3[0], (-u3[1]) % p))
    def fp2_const(nm, v):
        return ("  static const limb_t %s[2][%d] = {\n    { %s },\n    { %s }\n  };\n"
                % (nm, n, limb_list((v[0]*R) % p, n), limb_list((v[1]*R) % p, n)))
    psi_txt = (fp2_const("PSI_X", u2) + fp2_const("PSI_Y", u3) +
               fp2_const("PSI2_X", w2) + fp2_const("PSI2_Y", w3))

    frob_txt = ""
    for k in (1, 2, 3):
        for i, (a, b) in enumerate(frob[k], start=1):
            am, bm = (a * R) % p, (b * R) % p
            frob_txt += ("  static const limb_t FROB_P%d_%d[2][%d] = {\n"
                         "    { %s },\n    { %s }\n  };\n"
                         % (k, i, n, limb_list(am, n), limb_list(bm, n)))
    parts.append(
        "#if defined(" + macro + ")\n"
        '  #define ELIPS_CURVE_NAME   "' + cv.name + '"\n'
        "  #define FP_LIMBS           %d\n" % n +
        "  #define FP_BITS            %d\n" % p.bit_length() +
        "  #define FP_MONT_N0         UINT64_C(0x%016x)\n" % n0 +
        "  /* y^2 = x^3 " + sign + " %d */\n" % cv.b +
        "  #define ELIPS_CURVE_B_SIGN (%d)\n" % cv.sign_b +
        "  #define ELIPS_CURVE_B      %d\n" % cv.b +
        "  #define ELIPS_HAS_CURVE    1\n"
        "  static const limb_t FP_MODULUS[%d] = {\n        %s\n  };\n" % (n, limb_list(p, n)) +
        "  static const limb_t FP_R2[%d] = {\n        %s\n  };\n" % (n, limb_list(r2, n)) +
        "  static const limb_t FP_ONE[%d] = {\n        %s\n  };\n" % (n, limb_list(one, n)) +
        "  /* Miller loop parameter, signed digits. */\n" + loop_txt +
        "  /* (p^4 - p^2 + 1)/r, the hard part of the final exponentiation. */\n" + hard_txt +
        "  /* Skew Frobenius on the twist: psi and psi^2 multipliers. */\n" + psi_txt +
        "  /* Frobenius: gamma^i for the p, p^2 and p^3 power maps, Montgomery form. */\n" +
        frob_txt +
        "#endif\n")

parts.append("""#ifndef ELIPS_HAS_CURVE
#  error "No curve selected: define ELIPS_CURVE_BLS12_381, ELIPS_CURVE_BLS12_461 or ELIPS_CURVE_BN_462"
#endif

#endif /* ELIPS_FP_PARAMS_H */
""")

open("include/elips/fp_params.h", "w").write("\n".join(parts))
print("wrote include/elips/fp_params.h")
for cname in ("BLS12-381", "BLS12-461", "BN-462"):
    cv = CURVES[cname]
    print("  %-11s %4d bits -> %d limbs" % (cname, cv.p.bit_length(),
                                            (cv.p.bit_length() + 63)//64))
