"""Emit test/kat/subgroup_<curve>.vec: points the tests must accept, and
points they must reject.

The reason this file exists. A subgroup test that is too strict fails loudly
the first time a valid point is checked, so ordinary use finds it. A test that
is too permissive fails silently: it accepts attacker-chosen points of small
order, and every existing test still passes. Nothing in the suite fed the old
[r]P tests a point outside the subgroup, because [r]P cannot be wrong in that
direction. The endomorphism tests can.

So each file carries both classes:

  ing1  / ing2    on the curve and of order r      -> must be ACCEPTED
  outg1 / outg2   on the curve, NOT of order r     -> must be REJECTED

The rejected points are [r]R for random R, which lands in the cofactor part and
is exactly the kind of point the test exists to keep out.

BN-462 has G1 cofactor 1, so no point on E(Fp) is outside G1 and the file
carries no outg1 records. That is a property of the curve, asserted by
gen_params.py, not an omission.
"""
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from elips_ref import CURVES, Fp2, EFp, EFp2
from selftest import fp2_sqrt
from h2c_ref import group_orders

CURVE_FILES = {"BLS12-381": "bls12_381", "BLS12-461": "bls12_461", "BN-462": "bn_462"}
N_EACH = 4


def rand_fp(cv):
    p = cv.p
    while True:
        x = random.randrange(p)
        y2 = (x * x * x + cv.b_signed) % p
        y = pow(y2, (p + 1) // 4, p)
        if (y * y - y2) % p == 0:
            return EFp(cv, x, y)


def rand_fp2(cv):
    p, b = cv.p, EFp2.b_twist(cv)
    while True:
        x = Fp2(p, random.randrange(p), random.randrange(p))
        y = fp2_sqrt(x.sqr() * x + b, p)
        if y is not None:
            return EFp2(cv, x, y)


def emit(cv, out_dir):
    p, r = cv.p, cv.r
    n1, n2 = group_orders(cv)
    h1, h2 = n1 // r, n2 // r
    lines = [
        "# Subgroup membership vectors for %s." % cv.name,
        "# Generated by tools/reference/gen_subgroup_vectors.py -- do not edit.",
        "#   ing1/ing2   on the curve and of order r    -> must be ACCEPTED",
        "#   outg1/outg2 on the curve, not of order r   -> must be REJECTED",
        "prime %x" % p,
    ]

    got = 0
    while got < N_EACH:
        P = rand_fp(cv).mul(h1)
        if P.inf:
            continue
        assert P.mul(r).inf, "ing1 point must have order r"
        lines.append("ing1 %x %x" % (P.x, P.y))
        got += 1

    if h1 == 1:
        lines.append("# G1 cofactor is 1: no point of E(Fp) lies outside G1.")
    else:
        got = 0
        while got < N_EACH:
            T = rand_fp(cv).mul(r)
            if T.inf:
                continue
            assert not T.mul(r).inf, "outg1 point must NOT have order r"
            assert T.is_on_curve(), "outg1 point must still be on the curve"
            lines.append("outg1 %x %x" % (T.x, T.y))
            got += 1

    got = 0
    while got < N_EACH:
        Q = rand_fp2(cv).mul(h2)
        if Q.inf:
            continue
        assert Q.mul(r).inf, "ing2 point must have order r"
        lines.append("ing2 %x %x %x %x" % (Q.x.a, Q.x.b, Q.y.a, Q.y.b))
        got += 1

    got = 0
    while got < N_EACH:
        T = rand_fp2(cv).mul(r)
        if T.inf:
            continue
        assert not T.mul(r).inf, "outg2 point must NOT have order r"
        assert T.is_on_curve(), "outg2 point must still be on the twist"
        lines.append("outg2 %x %x %x %x" % (T.x.a, T.x.b, T.y.a, T.y.b))
        got += 1

    path = os.path.join(out_dir, "subgroup_%s.vec" % CURVE_FILES[cv.name])
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("  %s" % path)


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "test/kat"
    os.makedirs(out_dir, exist_ok=True)
    for name in ("BLS12-381", "BLS12-461", "BN-462"):
        # Seeded per curve so the files are byte-reproducible and CI can check
        # that the committed vectors are what the generator still produces.
        random.seed("elips-subgroup-" + name)
        emit(CURVES[name], out_dir)


if __name__ == "__main__":
    main()
