"""Emit Montgomery parameters for each curve (Phase 3, issue #4).

Generated rather than hand-written because a mistyped limb in R^2 or n0 gives
arithmetic that is wrong in a way no amount of staring detects.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from elips_ref import CURVES, EFp, EFp2, Fp2, _naf as _naf_digits
from selftest import fp2_sqrt
import math

W = 64
MASK = (1 << W) - 1
SEP = ",\n        "

def limb_list(x, n):
    return SEP.join("UINT64_C(0x%016x)" % ((x >> (W * i)) & MASK) for i in range(n))

# Published generators, in the standard compressed encoding.
#
# BLS12-381 is the only one of the three curves with a specification, and a
# library that hands out a different generator does not interoperate with it
# even when its serialization format is byte-exact: signatures verify against
# the standard generator or not at all. So for that curve the generators are
# taken from the specification rather than from the search below, and the
# search is kept as the fallback for the two curves that have no standard.
#
# Stored as the encoding rather than as coordinates because that is the form
# the specification publishes, so a reader can compare these strings against it
# directly. The decoder below re-derives y and every assertion still runs.
STANDARD_GENERATORS = {
    "BLS12-381": {
        "g1": "97f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905"
              "a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb",
        "g2": "93e02b6052719f607dacd3a088274f65596bd0d09920b61a"
              "b5da61bbdc7f5049334cf11213945d57e5ac7d055d042b7e"
              "024aa2b2f08f0a91260805272dc51051c6e47ad4fa403b02"
              "b4510b647ae3d1770bac0326a805bbefd48056c8c121bdb8",
    },
}

def _ser_bytes(p):
    """Field-element width in the encoding: FP_BITS rounded up with three bits
    left over for the compression, infinity and sign flags. Must agree with
    FP_SER_BYTES in include/elips/serialize.h."""
    return (p.bit_length() + 3 + 7) // 8

def _lex_largest(v, p):
    return v > (p - 1) // 2

def decode_g1(hexstr, cv):
    """Decode a compressed G1 encoding into (x, y). Mirrors ep_read_compressed."""
    p = cv.p
    w = _ser_bytes(p)
    raw = bytes.fromhex(hexstr)
    assert len(raw) == w, "G1 encoding is %d bytes, expected %d" % (len(raw), w)
    assert raw[0] & 0x80, "compression flag not set"
    assert not raw[0] & 0x40, "unexpected infinity flag"
    sign = bool(raw[0] & 0x20)
    x = int.from_bytes(bytes([raw[0] & 0x1f]) + raw[1:], "big")
    assert x < p, "x is not reduced"
    rhs = (pow(x, 3, p) + cv.b_signed) % p
    y = pow(rhs, (p + 1) // 4, p)
    assert (y * y) % p == rhs, "x has no square root"
    if _lex_largest(y, p) != sign:
        y = (p - y) % p
    return x, y

def decode_g2(hexstr, cv, bt):
    """Decode a compressed G2 encoding into (x, y) over Fp2, imaginary first."""
    p = cv.p
    w = _ser_bytes(p)
    raw = bytes.fromhex(hexstr)
    assert len(raw) == 2 * w, "G2 encoding is %d bytes, expected %d" % (len(raw), 2 * w)
    assert raw[0] & 0x80, "compression flag not set"
    assert not raw[0] & 0x40, "unexpected infinity flag"
    sign = bool(raw[0] & 0x20)
    c1 = int.from_bytes(bytes([raw[0] & 0x1f]) + raw[1:w], "big")
    c0 = int.from_bytes(raw[w:], "big")
    assert c0 < p and c1 < p, "x is not reduced"
    x = Fp2(p, c0, c1)
    y = fp2_sqrt(x.sqr() * x + bt, p)
    assert y is not None, "x has no square root on the twist"
    largest = _lex_largest(y.b, p) or (y.b == 0 and _lex_largest(y.a, p))
    if largest != sign:
        y = Fp2(p, (-y.a) % p, (-y.b) % p)
    return x, y

parts = ["""/* Generated by tools/reference/gen_params.py -- do not edit.
 *
 * Montgomery parameters, one block per curve. R = 2^(64*FP_LIMBS).
 *   FP_MONT_N0 = -p^-1 mod 2^64   the REDC multiplier
 *   FP_R2      = R^2 mod p        converts a plain residue into Montgomery form
 *   FP_ONE     = R mod p          the Montgomery representation of 1
 */
#ifndef ELIPS_FP_PARAMS_H
#define ELIPS_FP_PARAMS_H

#include <stdint.h>
#include <gmp.h>

/* Alias GMP's limb type rather than uint64_t. They are both 64 bits wide on the
 * platforms we target, but they are distinct C types (unsigned long vs unsigned
 * long long on LP64), and passing one where the other is expected is a
 * constraint violation that happens to work. The mpn_* calls in fp.c need the
 * real thing. */
typedef mp_limb_t limb_t;

#if GMP_LIMB_BITS != 64
#  error "These parameters are generated for 64-bit GMP limbs."
#endif
"""]

for macro, cname in (("ELIPS_CURVE_BLS12_381", "BLS12-381"),
                     ("ELIPS_CURVE_BLS12_461", "BLS12-461"),
                     ("ELIPS_CURVE_BN_462",    "BN-462")):
    cv = CURVES[cname]
    p = cv.p
    n = (p.bit_length() + W - 1) // W
    R = 1 << (W * n)
    n0 = (-pow(p, -1, 1 << W)) % (1 << W)
    assert (p * n0) % (1 << W) == MASK, "n0 must satisfy p*n0 == -1 mod 2^64"
    r2, one = (R * R) % p, R % p
    sign = "+" if cv.sign_b > 0 else "-"

    # Frobenius constants. In fp12 = fp6[w] with w^6 = xi = 1+u, the p-power
    # map sends sum(a_i w^i) to sum(conj(a_i) * gamma^i * w^i) where
    # gamma = w^(p-1) = xi^((p-1)/6). Emitted already in Montgomery form so the
    # library needs no initialisation step and no global state.
    def fp2_pow(base, e):
        r_ = (1, 0)
        b_ = base
        while e:
            if e & 1:
                r_ = ((r_[0]*b_[0] - r_[1]*b_[1]) % p, (r_[0]*b_[1] + r_[1]*b_[0]) % p)
            b_ = ((b_[0]*b_[0] - b_[1]*b_[1]) % p, (2*b_[0]*b_[1]) % p)
            e >>= 1
        return r_
    xi = (1, 1)
    frob = {}
    for k in (1, 2, 3):
        e = (pow(p, k) - 1) // 6
        g = fp2_pow(xi, e)
        # gamma^1 .. gamma^5
        acc, row = (1, 0), []
        for _ in range(5):
            acc = ((acc[0]*g[0] - acc[1]*g[1]) % p, (acc[0]*g[1] + acc[1]*g[0]) % p)
            row.append(acc)
        frob[k] = row
    # sanity: gamma^6 must be xi^(p^k - 1), and applying frobenius 12 times is
    # the identity, which the C-side vectors will confirm independently.
    # Miller loop parameter as signed digits, most significant last in the
    # array. BLS12 loops over X; BN loops over 6x+2.
    loop = cv.loop_digits
    top = max(loop)
    digits = [loop.get(i, 0) for i in range(top + 1)]
    # The mother parameter x, as signed digits. For BLS12 this is the same as
    # the Miller loop parameter; for BN the loop runs over 6x+2 instead, and
    # the final exponentiation needs x itself. Keeping them separate avoids the
    # obvious trap.
    xd = _naf_digits(cv.X)
    xtop = max(xd)
    xdigits = [xd.get(i, 0) for i in range(xtop + 1)]
    assert sum(d * 2**i for i, d in enumerate(xdigits)) == cv.X
    param_txt = ("  #define ELIPS_PARAM_TOP    %d\n" % xtop +
                 "  static const signed char ELIPS_PARAM[%d] = { %s };\n"
                 % (xtop + 1, ", ".join(str(d) for d in xdigits)))

    absx = abs(cv.X)
    axn = (absx.bit_length() + W - 1) // W
    param_txt += ("  #define ELIPS_ABSX_BITS    %d\n" % absx.bit_length() +
                  "  #define ELIPS_X_NEGATIVE   %d\n" % (1 if cv.X < 0 else 0) +
                  "  static const limb_t ELIPS_ABSX[%d] = {\n        %s\n  };\n"
                  % (axn, limb_list(absx, axn)))

    loop_txt = param_txt + ("  #define ELIPS_LOOP_TOP     %d\n" % top +
                "  #define ELIPS_FAMILY_%s   1\n" % cv.family.upper() +
                "  static const signed char ELIPS_LOOP[%d] = { %s };\n"
                % (top + 1, ", ".join(str(d) for d in digits)))

    # Hard part of the final exponentiation, (p^4 - p^2 + 1)/r, as limbs.
    # Used by the definitionally-correct slow path that validates any fast chain.
    ordr = cv.r
    hard = (p**4 - p**2 + 1) // ordr
    assert (p**4 - p**2 + 1) % ordr == 0, "r must divide p^4 - p^2 + 1"
    hn = (hard.bit_length() + W - 1) // W
    hard_txt = ("  #define ELIPS_HARD_BITS    %d\n" % hard.bit_length() +
                "  #define ELIPS_HARD_LIMBS   %d\n" % hn +
                "  static const limb_t ELIPS_HARD_EXP[%d] = {\n        %s\n  };\n"
                % (hn, limb_list(hard, hn)))

    # Skew Frobenius (psi) on the twist, needed by the BN correction lines.
    #
    # Untwisting sends (x',y') to (x'/w^2, y'/w^3); applying the p-power map
    # there and twisting back gives
    #     psi(x',y') = (conj(x') * gamma^-2, conj(y') * gamma^-3)
    # with gamma = w^(p-1) = xi^((p-1)/6). Applying psi twice leaves
    #     psi^2(x,y) = (x * N(gamma^-2), y * N(gamma^-3))
    # where N is the Fp2 norm, so the psi^2 multipliers lie in Fp.
    def fp2_inv_(a):
        n = pow((a[0]*a[0] + a[1]*a[1]) % p, p - 2, p)
        return ((a[0]*n) % p, (-a[1]*n) % p)
    def fp2_mul_(a, b):
        return ((a[0]*b[0] - a[1]*b[1]) % p, (a[0]*b[1] + a[1]*b[0]) % p)
    g1 = fp2_pow(xi, (p - 1) // 6)
    u2 = fp2_inv_(fp2_mul_(g1, g1))
    u3 = fp2_inv_(fp2_mul_(fp2_mul_(g1, g1), g1))
    w2 = fp2_mul_(u2, (u2[0], (-u2[1]) % p))
    w3 = fp2_mul_(u3, (u3[0], (-u3[1]) % p))
    def fp2_const_pair(nm, a):
        return ("  static const limb_t %s[2][%d] = {\n    { %s },\n    { %s }\n  };\n"
                % (nm, n, limb_list((a.a * R) % p, n), limb_list((a.b * R) % p, n)))

    def fp2_const(nm, v):
        return ("  static const limb_t %s[2][%d] = {\n    { %s },\n    { %s }\n  };\n"
                % (nm, n, limb_list((v[0]*R) % p, n), limb_list((v[1]*R) % p, n)))
    psi_txt = (fp2_const("PSI_X", u2) + fp2_const("PSI_Y", u3) +
               fp2_const("PSI2_X", w2) + fp2_const("PSI2_Y", w3))

    # Group generators.
    #
    # G1: smallest x making x^3 + b a square, lifted and multiplied by the
    # cofactor. G2: the same on the sextic twist. Both are asserted to be
    # on-curve, non-trivial and of order exactly r before being emitted, so a
    # generator that silently landed in the wrong subgroup cannot ship.
    tr = (cv.X + 1) if cv.family == "bls12" else (6 * cv.X**2 + 1)
    n1 = p + 1 - tr
    assert n1 % ordr == 0
    h1 = n1 // ordr
    g1 = None
    for xx in range(1, 4000):
        rhs = (xx**3 + cv.b_signed) % p
        if pow(rhs, (p - 1) // 2, p) != 1:
            continue
        cand = EFp(cv, xx, pow(rhs, (p + 1) // 4, p)).mul(h1)
        if not cand.inf and cand.mul(ordr).inf:
            g1 = cand; break
    assert g1 is not None and g1.is_on_curve(), "no G1 generator found"

    std = STANDARD_GENERATORS.get(cname)
    if std:
        sx, sy = decode_g1(std["g1"], cv)
        std_g1 = EFp(cv, sx, sy)
        assert std_g1.is_on_curve(), "published G1 generator is not on the curve"
        assert not std_g1.inf and std_g1.mul(ordr).inf, \
            "published G1 generator is not of order r"
        g1 = std_g1

    t2_ = tr*tr - 2*p
    f2_ = math.isqrt((4*p*p - t2_*t2_) // 3)
    assert 3*f2_*f2_ == 4*p*p - t2_*t2_
    n2 = None
    bt = EFp2.b_twist(cv)
    probe = None
    for k in range(1, 4000):
        xx = Fp2(p, k, 1)
        yy = fp2_sqrt(xx.sqr()*xx + bt, p)
        if yy is not None:
            probe = EFp2(cv, xx, yy); break
    for c in {(3*f2_ + t2_)//2, (-3*f2_ + t2_)//2}:
        cand_n = p*p + 1 - c
        if cand_n % ordr == 0 and probe.mul(cand_n).inf:
            n2 = cand_n; break
    assert n2 is not None, "could not identify the twist order"
    h2 = n2 // ordr
    g2 = None
    for k in range(1, 4000):
        xx = Fp2(p, k, 1)
        yy = fp2_sqrt(xx.sqr()*xx + bt, p)
        if yy is None:
            continue
        cand = EFp2(cv, xx, yy).mul(h2)
        if not cand.inf and cand.mul(ordr).inf:
            g2 = cand; break
    assert g2 is not None and g2.is_on_curve(), "no G2 generator found"

    if std:
        sx2, sy2 = decode_g2(std["g2"], cv, bt)
        std_g2 = EFp2(cv, sx2, sy2)
        assert std_g2.is_on_curve(), "published G2 generator is not on the twist"
        assert not std_g2.inf and std_g2.mul(ordr).inf, \
            "published G2 generator is not of order r"
        g2 = std_g2

    def fp_const(nm, v):
        return "  static const limb_t %s[%d] = {\n        %s\n  };\n" % (nm, n, limb_list((v * R) % p, n))
    def fp2_pair_const(nm, a):
        return ("  static const limb_t %s[2][%d] = {\n    { %s },\n    { %s }\n  };\n"
                % (nm, n, limb_list((a.a * R) % p, n), limb_list((a.b * R) % p, n)))
    on = (ordr.bit_length() + W - 1) // W
    gen_txt = (fp_const("EP_GEN_X", g1.x) + fp_const("EP_GEN_Y", g1.y) +
               fp2_pair_const("EP2_GEN_X", g2.x) + fp2_pair_const("EP2_GEN_Y", g2.y) +
               "  #define ELIPS_ORDER_BITS   %d\n" % ordr.bit_length() +
               "  static const limb_t ELIPS_ORDER[%d] = {\n        %s\n  };\n"
               % (on, limb_list(ordr, on)))

    frob_txt = ""
    for k in (1, 2, 3):
        for i, (a, b) in enumerate(frob[k], start=1):
            am, bm = (a * R) % p, (b * R) % p
            frob_txt += ("  static const limb_t FROB_P%d_%d[2][%d] = {\n"
                         "    { %s },\n    { %s }\n  };\n"
                         % (k, i, n, limb_list(am, n), limb_list(bm, n)))
    parts.append(
        "#if defined(" + macro + ")\n"
        '  #define ELIPS_CURVE_NAME   "' + cv.name + '"\n'
        "  #define FP_LIMBS           %d\n" % n +
        "  #define FP_BITS            %d\n" % p.bit_length() +
        "  #define FP_MONT_N0         UINT64_C(0x%016x)\n" % n0 +
        "  /* y^2 = x^3 " + sign + " %d */\n" % cv.b +
        "  #define ELIPS_CURVE_B_SIGN (%d)\n" % cv.sign_b +
        "  #define ELIPS_CURVE_B      %d\n" % cv.b +
        "  #define ELIPS_HAS_CURVE    1\n"
        "  static const limb_t FP_MODULUS[%d] = {\n        %s\n  };\n" % (n, limb_list(p, n)) +
        "  static const limb_t FP_R2[%d] = {\n        %s\n  };\n" % (n, limb_list(r2, n)) +
        "  static const limb_t FP_ONE[%d] = {\n        %s\n  };\n" % (n, limb_list(one, n)) +
        "  /* Miller loop parameter, signed digits. */\n" + loop_txt +
        "  /* (p^4 - p^2 + 1)/r, the hard part of the final exponentiation. */\n" + hard_txt +
        "  /* Group generators, verified on-curve and of order exactly r. */\n" + gen_txt +
        "  /* Skew Frobenius on the twist: psi and psi^2 multipliers. */\n" + psi_txt +
        "  /* Frobenius: gamma^i for the p, p^2 and p^3 power maps, Montgomery form. */\n" +
        frob_txt +
        "#endif\n")

parts.append("""#ifndef ELIPS_HAS_CURVE
#  error "No curve selected: define ELIPS_CURVE_BLS12_381, ELIPS_CURVE_BLS12_461 or ELIPS_CURVE_BN_462"
#endif

#endif /* ELIPS_FP_PARAMS_H */
""")

open("include/elips/fp_params.h", "w").write("\n".join(parts))
print("wrote include/elips/fp_params.h")
for cname in ("BLS12-381", "BLS12-461", "BN-462"):
    cv = CURVES[cname]
    print("  %-11s %4d bits -> %d limbs" % (cname, cv.p.bit_length(),
                                            (cv.p.bit_length() + 63)//64))
