"""Emit optimal-ate pairing known-answer vectors, one file per curve.

Issue #17. Until now the reference side of test/pairing_test.c was the legacy
mpz layer: the new pairing was declared correct because it agreed with the old
one. That is the weaker of the two available checks and it is the last thing
keeping the legacy layer alive.

These vectors come from tools/reference/pairing_ref.py instead -- an independent
optimal ate written from the defining equations, computing the final
exponentiation as a single exponentiation by (p^12-1)/r rather than by any
addition chain. So the C implementation is checked against the specification of
the pairing, not against another implementation of it. It also covers
BLS12-381, which the legacy layer never supported and which therefore had no
pairing reference at all.

The points are read out of the generated include/elips/fp_params.h, so the
vectors pin the pairing on exactly the generators the library ships rather than
on some other valid pair.

Only the value AFTER the full final exponentiation is recorded. A raw Miller
value depends on how the line functions are normalised -- the constants cancel
in the final exponentiation -- so it would pin a convention rather than the
pairing, and the convention changed when the curve layer moved to RCB.

  usage: python3 tools/reference/gen_pairing_vectors.py [outdir]
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from elips_ref import CURVES, EFp, EFp2, Fp2, fp12_to_list    # noqa: E402
from pairing_ref import optimal_ate                           # noqa: E402

FILES = {"BLS12-381": ("ELIPS_CURVE_BLS12_381", "pairing_bls12_381.vec"),
         "BLS12-461": ("ELIPS_CURVE_BLS12_461", "pairing_bls12_461.vec"),
         "BN-462":    ("ELIPS_CURVE_BN_462",    "pairing_bn_462.vec")}

# Small scalars, so the vectors also witness bilinearity with concrete values
# rather than only asserting it. Distinct and not 1, which would test nothing.
SCALARS = [(1, 1), (7, 1), (1, 11), (5, 9)]

HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "..", "..", "include", "elips", "fp_params.h")


def generators(curve, macro):
    """The library's own G1 and G2 generators, read back out of the generated
    header and converted out of Montgomery form."""
    src = open(HEADER).read()
    i = src.index("#if defined(%s)" % macro)
    block = src[i:src.index("#endif", i)]

    p = curve.p
    n = (p.bit_length() + 63) // 64
    r_inv = pow(1 << (64 * n), -1, p)

    def limbs(tag):
        m = re.search(r"static const limb_t " + tag + r"\[(?:2\])?\[?\d*\] *= *\{(.*?)\n  \};",
                      block, re.S)
        if not m:
            raise KeyError(tag)
        vals = [int(x, 16) for x in re.findall(r"UINT64_C\((0x[0-9a-f]+)\)", m.group(1))]
        return vals

    def demont(vals):
        acc = 0
        for k, v in enumerate(vals):
            acc |= v << (64 * k)
        return acc * r_inv % p

    gx, gy = demont(limbs("EP_GEN_X")), demont(limbs("EP_GEN_Y"))
    x2, y2 = limbs("EP2_GEN_X"), limbs("EP2_GEN_Y")
    qx = Fp2(p, demont(x2[:n]), demont(x2[n:]))
    qy = Fp2(p, demont(y2[:n]), demont(y2[n:]))

    g1, g2 = EFp(curve, gx, gy), EFp2(curve, qx, qy)
    # The header claims these are generators; check rather than trust, since a
    # wrong point here would produce vectors that are self-consistent and wrong.
    assert g1.is_on_curve() and not g1.inf and g1.mul(curve.r).inf, "bad G1"
    assert g2.is_on_curve() and not g2.inf and g2.mul(curve.r).inf, "bad G2"
    return g1, g2


def emit(name, out_dir):
    cv = CURVES[name]
    macro, fname = FILES[name]
    g1, g2 = generators(cv, macro)

    lines = ["# optimal ate pairing known-answer vectors for %s" % cv.name,
             "# generated by tools/reference/gen_pairing_vectors.py -- do not edit",
             "#",
             "# The reference is tools/reference/pairing_ref.py, which computes the",
             "# final exponentiation as one exponentiation by (p^12-1)/r. So these",
             "# are the exact value e(P, Q), with no addition chain and no stray",
             "# cofactor -- what the library's pairing_final_exp_plain must return.",
             "#",
             "# fields: pair px py qx0 qx1 qy0 qy1 = twelve fp coefficients,",
             "# ordered d0.c0.a d0.c0.b d0.c1.a ... d1.c2.b",
             "prime %x" % cv.p]

    for a, b in SCALARS:
        P, Q = g1.mul(a), g2.mul(b)
        z = optimal_ate(cv, P.x, P.y, Q.x, Q.y)
        assert z.pow(cv.r).is_one(), "pairing value is not in mu_r"
        assert not z.is_one(), "pairing value is degenerate"
        coeffs = " ".join("%x" % c for c in fp12_to_list(z))
        lines.append("# e([%d]G1, [%d]G2)" % (a, b))
        lines.append("pair %x %x %x %x %x %x = %s"
                     % (P.x, P.y, Q.x.a, Q.x.b, Q.y.a, Q.y.b, coeffs))

    path = os.path.join(out_dir, fname)
    open(path, "w").write("\n".join(lines) + "\n")
    return path, len(SCALARS)


if __name__ == "__main__":
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "test/kat"
    os.makedirs(out_dir, exist_ok=True)
    for name in FILES:
        path, n = emit(name, out_dir)
        print("  %-32s %d pairings" % (path, n))
