"""Emit Montgomery parameters for each curve (Phase 3, issue #4).

Generated rather than hand-written because a mistyped limb in R^2 or n0 gives
arithmetic that is wrong in a way no amount of staring detects.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from elips_ref import CURVES

W = 64
MASK = (1 << W) - 1
SEP = ",\n        "

def limb_list(x, n):
    return SEP.join("UINT64_C(0x%016x)" % ((x >> (W * i)) & MASK) for i in range(n))

parts = ["""/* Generated by tools/reference/gen_params.py -- do not edit.
 *
 * Montgomery parameters, one block per curve. R = 2^(64*FP_LIMBS).
 *   FP_MONT_N0 = -p^-1 mod 2^64   the REDC multiplier
 *   FP_R2      = R^2 mod p        converts a plain residue into Montgomery form
 *   FP_ONE     = R mod p          the Montgomery representation of 1
 */
#ifndef ELIPS_FP_PARAMS_H
#define ELIPS_FP_PARAMS_H

#include <stdint.h>
#include <gmp.h>

/* Alias GMP's limb type rather than uint64_t. They are both 64 bits wide on the
 * platforms we target, but they are distinct C types (unsigned long vs unsigned
 * long long on LP64), and passing one where the other is expected is a
 * constraint violation that happens to work. The mpn_* calls in fp.c need the
 * real thing. */
typedef mp_limb_t limb_t;

#if GMP_LIMB_BITS != 64
#  error "These parameters are generated for 64-bit GMP limbs."
#endif
"""]

for macro, cname in (("ELIPS_CURVE_BLS12_381", "BLS12-381"),
                     ("ELIPS_CURVE_BLS12_461", "BLS12-461"),
                     ("ELIPS_CURVE_BN_462",    "BN-462")):
    cv = CURVES[cname]
    p = cv.p
    n = (p.bit_length() + W - 1) // W
    R = 1 << (W * n)
    n0 = (-pow(p, -1, 1 << W)) % (1 << W)
    assert (p * n0) % (1 << W) == MASK, "n0 must satisfy p*n0 == -1 mod 2^64"
    r2, one = (R * R) % p, R % p
    sign = "+" if cv.sign_b > 0 else "-"
    parts.append(
        "#if defined(" + macro + ")\n"
        '  #define ELIPS_CURVE_NAME   "' + cv.name + '"\n'
        "  #define FP_LIMBS           %d\n" % n +
        "  #define FP_BITS            %d\n" % p.bit_length() +
        "  #define FP_MONT_N0         UINT64_C(0x%016x)\n" % n0 +
        "  /* y^2 = x^3 " + sign + " %d */\n" % cv.b +
        "  #define ELIPS_CURVE_B_SIGN (%d)\n" % cv.sign_b +
        "  #define ELIPS_CURVE_B      %d\n" % cv.b +
        "  #define ELIPS_HAS_CURVE    1\n"
        "  static const limb_t FP_MODULUS[%d] = {\n        %s\n  };\n" % (n, limb_list(p, n)) +
        "  static const limb_t FP_R2[%d] = {\n        %s\n  };\n" % (n, limb_list(r2, n)) +
        "  static const limb_t FP_ONE[%d] = {\n        %s\n  };\n" % (n, limb_list(one, n)) +
        "#endif\n")

parts.append("""#ifndef ELIPS_HAS_CURVE
#  error "No curve selected: define ELIPS_CURVE_BLS12_381, ELIPS_CURVE_BLS12_461 or ELIPS_CURVE_BN_462"
#endif

#endif /* ELIPS_FP_PARAMS_H */
""")

open("include/elips/fp_params.h", "w").write("\n".join(parts))
print("wrote include/elips/fp_params.h")
for cname in ("BLS12-381", "BLS12-461", "BN-462"):
    cv = CURVES[cname]
    print("  %-11s %4d bits -> %d limbs" % (cname, cv.p.bit_length(),
                                            (cv.p.bit_length() + 63)//64))
