"""Emit hash-to-curve known-answer vectors, one file per curve.

Same idea as gen_vectors.py: the C implementation is checked against a Python
reference written from the specification, not against itself.

For BLS12-381 the file also carries the RFC 9380 J.9.1 and J.10.1 vectors under
the specification's own domain separation tag, so that file pins interoperability
and not merely internal agreement. The other two curves have no published
vectors -- there is no registered suite for them -- so theirs come from the
reference alone, and the file says so.

  usage: python3 tools/reference/gen_h2c_vectors.py [outdir]
"""
import hashlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from elips_ref import CURVES                                    # noqa: E402
import h2c_ref                                                  # noqa: E402

FILES = {"BLS12-381": "h2c_bls12_381.vec",
         "BLS12-461": "h2c_bls12_461.vec",
         "BN-462":    "h2c_bn_462.vec"}

# Messages chosen to cover the shapes that break implementations: empty, short,
# exactly one and exactly two SHA-256 blocks of expand_message_xmd output, and
# the two long ones RFC 9380 uses.
MESSAGES = [b"", b"abc", b"abcdef0123456789",
            b"q128_" + b"q" * 128,
            b"a512_" + b"a" * 512,
            bytes(range(256))]

# expand_message_xmd on its own, so a failure there is distinguishable from a
# failure in the map.
XMD_CASES = [(b"", 32), (b"abc", 32), (b"abc", 128), (b"", 65),
             (b"a" * 300, 96)]


def hx(b):
    return b.hex() if b else "-"


def emit(cv_name, out_dir):
    cv = CURVES[cv_name]
    g1 = h2c_ref.suite(cv, "G1")
    g2 = h2c_ref.suite(cv, "G2")
    lines = []
    A = lines.append

    A("# hash-to-curve known-answer vectors for %s" % cv.name)
    A("# generated by tools/reference/gen_h2c_vectors.py -- do not edit")
    A("# suite_g1 %s" % g1.suite_id)
    A("# suite_g2 %s" % g2.suite_id)
    if cv.name == "BLS12-381":
        A("# The DST below is RFC 9380's own, so the h2c_g1 and h2c_g2 records")
        A("# for the five specification messages ARE the published vectors of")
        A("# J.9.1 and J.10.1. Byte-for-byte interoperability lives here.")
    else:
        A("# No registered suite exists for this curve, so these come from the")
        A("# reference implementation and pin self-consistency, not interop.")
    A("# fields: op dst_hex msg_hex [len] = outputs (hex, '-' is the empty string)")
    A("prime %x" % cv.p)

    dst1 = g1.default_dst()
    dst2 = g2.default_dst()
    if cv.name == "BLS12-381":
        dst1 = h2c_ref.DST_G1_RFC
        dst2 = h2c_ref.DST_G2_RFC

    # SHA-256 on its own, so a broken compression function is distinguishable
    # from a broken expand_message_xmd. Generated rather than transcribed from
    # FIPS 180-4, for the same reason as everything else here.
    for msg in (b"", b"abc",
                b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
                b"a" * 1000):
        A("sha256 %s = %s" % (hx(msg), hashlib.sha256(msg).hexdigest()))

    for msg, n in XMD_CASES:
        got = h2c_ref.expand_message_xmd(msg, dst1, n)
        A("xmd %s %s %d = %s" % (hx(dst1), hx(msg), n, hx(got)))

    for msg in MESSAGES:
        u = g1.hash_to_field(msg, dst1, 2)
        A("h2f_g1 %s %s = %x %x" % (hx(dst1), hx(msg), u[0].v, u[1].v))
        P = g1.hash_to_curve(msg, dst1)
        A("h2c_g1 %s %s = %x %x" % (hx(dst1), hx(msg), P.x, P.y))
        Q = g1.encode_to_curve(msg, dst1)
        A("enc_g1 %s %s = %x %x" % (hx(dst1), hx(msg), Q.x, Q.y))

    for msg in MESSAGES:
        u = g2.hash_to_field(msg, dst2, 2)
        A("h2f_g2 %s %s = %x %x %x %x"
          % (hx(dst2), hx(msg), u[0].v.a, u[0].v.b, u[1].v.a, u[1].v.b))
        P = g2.hash_to_curve(msg, dst2)
        A("h2c_g2 %s %s = %x %x %x %x"
          % (hx(dst2), hx(msg), P.x.a, P.x.b, P.y.a, P.y.b))
        Q = g2.encode_to_curve(msg, dst2)
        A("enc_g2 %s %s = %x %x %x %x"
          % (hx(dst2), hx(msg), Q.x.a, Q.x.b, Q.y.a, Q.y.b))

    # A tag longer than 255 bytes must be hashed down (RFC 9380 5.3.3) rather
    # than rejected, and that path is easy to leave untested.
    long_dst = b"LONG-" + b"D" * 300
    P = g1.hash_to_curve(b"oversize", long_dst)
    A("h2c_g1 %s %s = %x %x" % (hx(long_dst), hx(b"oversize"), P.x, P.y))

    path = os.path.join(out_dir, FILES[cv.name])
    open(path, "w").write("\n".join(lines) + "\n")
    return path, len(lines)


if __name__ == "__main__":
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "test/kat"
    os.makedirs(out_dir, exist_ok=True)
    if h2c_ref.selftest(verbose=False):
        sys.exit("h2c_ref self-test failed; refusing to emit vectors")
    for name in FILES:
        path, n = emit(name, out_dir)
        print("  %-28s %d records" % (path, n))
